/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.e.onboarding.model.impl;

import com.e.onboarding.model.EOnBoarding;
import com.e.onboarding.service.EOnBoardingLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the EOnBoarding service. Represents a row in the &quot;vgcapon_EOnBoarding&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EOnBoardingImpl}.
 * </p>
 *
 * @author sanguine
 * @see EOnBoardingImpl
 * @see com.e.onboarding.model.EOnBoarding
 * @generated
 */
public abstract class EOnBoardingBaseImpl extends EOnBoardingModelImpl
	implements EOnBoarding {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a e on boarding model instance should use the {@link EOnBoarding} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			EOnBoardingLocalServiceUtil.addEOnBoarding(this);
		}
		else {
			EOnBoardingLocalServiceUtil.updateEOnBoarding(this);
		}
	}
}