create table vgcapon_SeatOffice (
	seatId LONG not null primary key,
	groupId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	companyId LONG,
	ticketNo VARCHAR(75) null,
	staffName VARCHAR(75) null,
	staffCode LONG,
	companyName VARCHAR(75) null,
	division VARCHAR(75) null,
	department VARCHAR(75) null,
	costCenter VARCHAR(75) null,
	officePhone VARCHAR(75) null,
	mobilePhone VARCHAR(75) null,
	officeSite VARCHAR(75) null,
	currentCategory LONG,
	currentSeatNo VARCHAR(75) null,
	movingDate DATE null,
	expectedSeatNo VARCHAR(75) null,
	reasonForChange VARCHAR(250) null,
	officeKey BOOLEAN,
	plant BOOLEAN,
	telephoneAndExtNo BOOLEAN,
	namePlate BOOLEAN,
	cabinet BOOLEAN,
	isOnBehalfOf BOOLEAN,
	nowCategory LONG,
	newSeatNo VARCHAR(75) null,
	workspaceId LONG,
	seatStatus VARCHAR(75) null,
	sg VARCHAR(75) null,
	leadingMark VARCHAR(75) null,
	positionFlag VARCHAR(75) null,
	isApplicantAgent BOOLEAN,
	isApproverAgent BOOLEAN,
	candidateName VARCHAR(75) null,
	desiredStartingDate DATE null,
	comments VARCHAR(250) null,
	contractType VARCHAR(75) null,
	processType VARCHAR(75) null,
	subProcessType VARCHAR(75) null,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null
);