/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.company.car.model.impl;

import com.company.car.model.SecondCompanyCar;
import com.company.car.service.SecondCompanyCarLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the SecondCompanyCar service. Represents a row in the &quot;vgcapon_SecondCompanyCar&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SecondCompanyCarImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SecondCompanyCarImpl
 * @see com.company.car.model.SecondCompanyCar
 * @generated
 */
public abstract class SecondCompanyCarBaseImpl extends SecondCompanyCarModelImpl
	implements SecondCompanyCar {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a second company car model instance should use the {@link SecondCompanyCar} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			SecondCompanyCarLocalServiceUtil.addSecondCompanyCar(this);
		}
		else {
			SecondCompanyCarLocalServiceUtil.updateSecondCompanyCar(this);
		}
	}
}