/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.business.trip.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BtCostList service. Represents a row in the &quot;vgcapon_BtCostList&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.business.trip.model.impl.BtCostListModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.business.trip.model.impl.BtCostListImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BtCostList
 * @see com.business.trip.model.impl.BtCostListImpl
 * @see com.business.trip.model.impl.BtCostListModelImpl
 * @generated
 */
public interface BtCostListModel extends BaseModel<BtCostList> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bt cost list model instance should use the {@link BtCostList} interface instead.
	 */

	/**
	 * Returns the primary key of this bt cost list.
	 *
	 * @return the primary key of this bt cost list
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bt cost list.
	 *
	 * @param primaryKey the primary key of this bt cost list
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the bt cost list ID of this bt cost list.
	 *
	 * @return the bt cost list ID of this bt cost list
	 */
	public long getBtCostListId();

	/**
	 * Sets the bt cost list ID of this bt cost list.
	 *
	 * @param btCostListId the bt cost list ID of this bt cost list
	 */
	public void setBtCostListId(long btCostListId);

	/**
	 * Returns the business trip pk ID of this bt cost list.
	 *
	 * @return the business trip pk ID of this bt cost list
	 */
	public long getBusinessTripPkId();

	/**
	 * Sets the business trip pk ID of this bt cost list.
	 *
	 * @param businessTripPkId the business trip pk ID of this bt cost list
	 */
	public void setBusinessTripPkId(long businessTripPkId);

	/**
	 * Returns the ticket no of this bt cost list.
	 *
	 * @return the ticket no of this bt cost list
	 */
	@AutoEscape
	public String getTicketNo();

	/**
	 * Sets the ticket no of this bt cost list.
	 *
	 * @param ticketNo the ticket no of this bt cost list
	 */
	public void setTicketNo(String ticketNo);

	/**
	 * Returns the item of this bt cost list.
	 *
	 * @return the item of this bt cost list
	 */
	@AutoEscape
	public String getItem();

	/**
	 * Sets the item of this bt cost list.
	 *
	 * @param item the item of this bt cost list
	 */
	public void setItem(String item);

	/**
	 * Returns the invoice currency of this bt cost list.
	 *
	 * @return the invoice currency of this bt cost list
	 */
	@AutoEscape
	public String getInvoiceCurrency();

	/**
	 * Sets the invoice currency of this bt cost list.
	 *
	 * @param invoiceCurrency the invoice currency of this bt cost list
	 */
	public void setInvoiceCurrency(String invoiceCurrency);

	/**
	 * Returns the payment amount of this bt cost list.
	 *
	 * @return the payment amount of this bt cost list
	 */
	public double getPaymentAmount();

	/**
	 * Sets the payment amount of this bt cost list.
	 *
	 * @param paymentAmount the payment amount of this bt cost list
	 */
	public void setPaymentAmount(double paymentAmount);

	/**
	 * Returns the payment currency of this bt cost list.
	 *
	 * @return the payment currency of this bt cost list
	 */
	@AutoEscape
	public String getPaymentCurrency();

	/**
	 * Sets the payment currency of this bt cost list.
	 *
	 * @param paymentCurrency the payment currency of this bt cost list
	 */
	public void setPaymentCurrency(String paymentCurrency);

	/**
	 * Returns the country city of this bt cost list.
	 *
	 * @return the country city of this bt cost list
	 */
	@AutoEscape
	public String getCountryCity();

	/**
	 * Sets the country city of this bt cost list.
	 *
	 * @param countryCity the country city of this bt cost list
	 */
	public void setCountryCity(String countryCity);

	/**
	 * Returns the type of this bt cost list.
	 *
	 * @return the type of this bt cost list
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this bt cost list.
	 *
	 * @param type the type of this bt cost list
	 */
	public void setType(String type);

	/**
	 * Returns the invoice amount of this bt cost list.
	 *
	 * @return the invoice amount of this bt cost list
	 */
	public double getInvoiceAmount();

	/**
	 * Sets the invoice amount of this bt cost list.
	 *
	 * @param invoiceAmount the invoice amount of this bt cost list
	 */
	public void setInvoiceAmount(double invoiceAmount);

	/**
	 * Returns the tax rate of this bt cost list.
	 *
	 * @return the tax rate of this bt cost list
	 */
	public double getTaxRate();

	/**
	 * Sets the tax rate of this bt cost list.
	 *
	 * @param taxRate the tax rate of this bt cost list
	 */
	public void setTaxRate(double taxRate);

	/**
	 * Returns the net amount of this bt cost list.
	 *
	 * @return the net amount of this bt cost list
	 */
	public double getNetAmount();

	/**
	 * Sets the net amount of this bt cost list.
	 *
	 * @param netAmount the net amount of this bt cost list
	 */
	public void setNetAmount(double netAmount);

	/**
	 * Returns the tax amount of this bt cost list.
	 *
	 * @return the tax amount of this bt cost list
	 */
	public double getTaxAmount();

	/**
	 * Sets the tax amount of this bt cost list.
	 *
	 * @param taxAmount the tax amount of this bt cost list
	 */
	public void setTaxAmount(double taxAmount);

	/**
	 * Returns the net amount rmb of this bt cost list.
	 *
	 * @return the net amount rmb of this bt cost list
	 */
	public double getNetAmountRmb();

	/**
	 * Sets the net amount rmb of this bt cost list.
	 *
	 * @param netAmountRmb the net amount rmb of this bt cost list
	 */
	public void setNetAmountRmb(double netAmountRmb);

	/**
	 * Returns the entertainment date of this bt cost list.
	 *
	 * @return the entertainment date of this bt cost list
	 */
	public Date getEntertainmentDate();

	/**
	 * Sets the entertainment date of this bt cost list.
	 *
	 * @param entertainmentDate the entertainment date of this bt cost list
	 */
	public void setEntertainmentDate(Date entertainmentDate);

	/**
	 * Returns the entertainment place of this bt cost list.
	 *
	 * @return the entertainment place of this bt cost list
	 */
	@AutoEscape
	public String getEntertainmentPlace();

	/**
	 * Sets the entertainment place of this bt cost list.
	 *
	 * @param entertainmentPlace the entertainment place of this bt cost list
	 */
	public void setEntertainmentPlace(String entertainmentPlace);

	/**
	 * Returns the reasones info of this bt cost list.
	 *
	 * @return the reasones info of this bt cost list
	 */
	@AutoEscape
	public String getReasonesInfo();

	/**
	 * Sets the reasones info of this bt cost list.
	 *
	 * @param reasonesInfo the reasones info of this bt cost list
	 */
	public void setReasonesInfo(String reasonesInfo);

	/**
	 * Returns the attendees total of this bt cost list.
	 *
	 * @return the attendees total of this bt cost list
	 */
	public int getAttendeesTotal();

	/**
	 * Sets the attendees total of this bt cost list.
	 *
	 * @param attendeesTotal the attendees total of this bt cost list
	 */
	public void setAttendeesTotal(int attendeesTotal);

	/**
	 * Returns the average spend of this bt cost list.
	 *
	 * @return the average spend of this bt cost list
	 */
	public double getAverageSpend();

	/**
	 * Sets the average spend of this bt cost list.
	 *
	 * @param averageSpend the average spend of this bt cost list
	 */
	public void setAverageSpend(double averageSpend);

	/**
	 * Returns the meal category of this bt cost list.
	 *
	 * @return the meal category of this bt cost list
	 */
	@AutoEscape
	public String getMealCategory();

	/**
	 * Sets the meal category of this bt cost list.
	 *
	 * @param mealCategory the meal category of this bt cost list
	 */
	public void setMealCategory(String mealCategory);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.business.trip.model.BtCostList btCostList);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.business.trip.model.BtCostList> toCacheModel();

	@Override
	public com.business.trip.model.BtCostList toEscapedModel();

	@Override
	public com.business.trip.model.BtCostList toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}