/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.business.trip.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the BtEntertainmentDetail service. Represents a row in the &quot;vgcapon_BtEntertainmentDetail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.business.trip.model.impl.BtEntertainmentDetailModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.business.trip.model.impl.BtEntertainmentDetailImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BtEntertainmentDetail
 * @see com.business.trip.model.impl.BtEntertainmentDetailImpl
 * @see com.business.trip.model.impl.BtEntertainmentDetailModelImpl
 * @generated
 */
public interface BtEntertainmentDetailModel extends BaseModel<BtEntertainmentDetail> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bt entertainment detail model instance should use the {@link BtEntertainmentDetail} interface instead.
	 */

	/**
	 * Returns the primary key of this bt entertainment detail.
	 *
	 * @return the primary key of this bt entertainment detail
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bt entertainment detail.
	 *
	 * @param primaryKey the primary key of this bt entertainment detail
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the bt entertainment detail ID of this bt entertainment detail.
	 *
	 * @return the bt entertainment detail ID of this bt entertainment detail
	 */
	public long getBtEntertainmentDetailId();

	/**
	 * Sets the bt entertainment detail ID of this bt entertainment detail.
	 *
	 * @param btEntertainmentDetailId the bt entertainment detail ID of this bt entertainment detail
	 */
	public void setBtEntertainmentDetailId(long btEntertainmentDetailId);

	/**
	 * Returns the bt cost list ID of this bt entertainment detail.
	 *
	 * @return the bt cost list ID of this bt entertainment detail
	 */
	public long getBtCostListId();

	/**
	 * Sets the bt cost list ID of this bt entertainment detail.
	 *
	 * @param btCostListId the bt cost list ID of this bt entertainment detail
	 */
	public void setBtCostListId(long btCostListId);

	/**
	 * Returns the business trip pk ID of this bt entertainment detail.
	 *
	 * @return the business trip pk ID of this bt entertainment detail
	 */
	public long getBusinessTripPkId();

	/**
	 * Sets the business trip pk ID of this bt entertainment detail.
	 *
	 * @param businessTripPkId the business trip pk ID of this bt entertainment detail
	 */
	public void setBusinessTripPkId(long businessTripPkId);

	/**
	 * Returns the full name of this bt entertainment detail.
	 *
	 * @return the full name of this bt entertainment detail
	 */
	@AutoEscape
	public String getFullName();

	/**
	 * Sets the full name of this bt entertainment detail.
	 *
	 * @param fullName the full name of this bt entertainment detail
	 */
	public void setFullName(String fullName);

	/**
	 * Returns the position title of this bt entertainment detail.
	 *
	 * @return the position title of this bt entertainment detail
	 */
	@AutoEscape
	public String getPositionTitle();

	/**
	 * Sets the position title of this bt entertainment detail.
	 *
	 * @param positionTitle the position title of this bt entertainment detail
	 */
	public void setPositionTitle(String positionTitle);

	/**
	 * Returns the company of this bt entertainment detail.
	 *
	 * @return the company of this bt entertainment detail
	 */
	@AutoEscape
	public String getCompany();

	/**
	 * Sets the company of this bt entertainment detail.
	 *
	 * @param company the company of this bt entertainment detail
	 */
	public void setCompany(String company);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.business.trip.model.BtEntertainmentDetail btEntertainmentDetail);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.business.trip.model.BtEntertainmentDetail> toCacheModel();

	@Override
	public com.business.trip.model.BtEntertainmentDetail toEscapedModel();

	@Override
	public com.business.trip.model.BtEntertainmentDetail toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}