/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.business.trip.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BtExchangeRate service. Represents a row in the &quot;vgcapon_BtExchangeRate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.business.trip.model.impl.BtExchangeRateModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.business.trip.model.impl.BtExchangeRateImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BtExchangeRate
 * @see com.business.trip.model.impl.BtExchangeRateImpl
 * @see com.business.trip.model.impl.BtExchangeRateModelImpl
 * @generated
 */
public interface BtExchangeRateModel extends BaseModel<BtExchangeRate> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bt exchange rate model instance should use the {@link BtExchangeRate} interface instead.
	 */

	/**
	 * Returns the primary key of this bt exchange rate.
	 *
	 * @return the primary key of this bt exchange rate
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bt exchange rate.
	 *
	 * @param primaryKey the primary key of this bt exchange rate
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the bt exchange rate ID of this bt exchange rate.
	 *
	 * @return the bt exchange rate ID of this bt exchange rate
	 */
	public long getBtExchangeRateId();

	/**
	 * Sets the bt exchange rate ID of this bt exchange rate.
	 *
	 * @param btExchangeRateId the bt exchange rate ID of this bt exchange rate
	 */
	public void setBtExchangeRateId(long btExchangeRateId);

	/**
	 * Returns the first currency of this bt exchange rate.
	 *
	 * @return the first currency of this bt exchange rate
	 */
	@AutoEscape
	public String getFirstCurrency();

	/**
	 * Sets the first currency of this bt exchange rate.
	 *
	 * @param firstCurrency the first currency of this bt exchange rate
	 */
	public void setFirstCurrency(String firstCurrency);

	/**
	 * Returns the second currency of this bt exchange rate.
	 *
	 * @return the second currency of this bt exchange rate
	 */
	@AutoEscape
	public String getSecondCurrency();

	/**
	 * Sets the second currency of this bt exchange rate.
	 *
	 * @param secondCurrency the second currency of this bt exchange rate
	 */
	public void setSecondCurrency(String secondCurrency);

	/**
	 * Returns the fir to sec exchange rate of this bt exchange rate.
	 *
	 * @return the fir to sec exchange rate of this bt exchange rate
	 */
	public double getFirToSecExchangeRate();

	/**
	 * Sets the fir to sec exchange rate of this bt exchange rate.
	 *
	 * @param firToSecExchangeRate the fir to sec exchange rate of this bt exchange rate
	 */
	public void setFirToSecExchangeRate(double firToSecExchangeRate);

	/**
	 * Returns the sec to fir exchange rate of this bt exchange rate.
	 *
	 * @return the sec to fir exchange rate of this bt exchange rate
	 */
	public double getSecToFirExchangeRate();

	/**
	 * Sets the sec to fir exchange rate of this bt exchange rate.
	 *
	 * @param secToFirExchangeRate the sec to fir exchange rate of this bt exchange rate
	 */
	public void setSecToFirExchangeRate(double secToFirExchangeRate);

	/**
	 * Returns the user ID of this bt exchange rate.
	 *
	 * @return the user ID of this bt exchange rate
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this bt exchange rate.
	 *
	 * @param userId the user ID of this bt exchange rate
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this bt exchange rate.
	 *
	 * @return the user uuid of this bt exchange rate
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this bt exchange rate.
	 *
	 * @param userUuid the user uuid of this bt exchange rate
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this bt exchange rate.
	 *
	 * @return the user name of this bt exchange rate
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this bt exchange rate.
	 *
	 * @param userName the user name of this bt exchange rate
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this bt exchange rate.
	 *
	 * @return the create date of this bt exchange rate
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this bt exchange rate.
	 *
	 * @param createDate the create date of this bt exchange rate
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this bt exchange rate.
	 *
	 * @return the modified date of this bt exchange rate
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this bt exchange rate.
	 *
	 * @param modifiedDate the modified date of this bt exchange rate
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this bt exchange rate.
	 *
	 * @return the status of this bt exchange rate
	 */
	public int getStatus();

	/**
	 * Sets the status of this bt exchange rate.
	 *
	 * @param status the status of this bt exchange rate
	 */
	public void setStatus(int status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.business.trip.model.BtExchangeRate btExchangeRate);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.business.trip.model.BtExchangeRate> toCacheModel();

	@Override
	public com.business.trip.model.BtExchangeRate toEscapedModel();

	@Override
	public com.business.trip.model.BtExchangeRate toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}