/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.business.trip.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BtExchangeSAPRate service. Represents a row in the &quot;vgcapon_BtExchangeSAPRate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.business.trip.model.impl.BtExchangeSAPRateModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.business.trip.model.impl.BtExchangeSAPRateImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BtExchangeSAPRate
 * @see com.business.trip.model.impl.BtExchangeSAPRateImpl
 * @see com.business.trip.model.impl.BtExchangeSAPRateModelImpl
 * @generated
 */
public interface BtExchangeSAPRateModel extends BaseModel<BtExchangeSAPRate> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bt exchange s a p rate model instance should use the {@link BtExchangeSAPRate} interface instead.
	 */

	/**
	 * Returns the primary key of this bt exchange s a p rate.
	 *
	 * @return the primary key of this bt exchange s a p rate
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bt exchange s a p rate.
	 *
	 * @param primaryKey the primary key of this bt exchange s a p rate
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the bt exchange s a p rate ID of this bt exchange s a p rate.
	 *
	 * @return the bt exchange s a p rate ID of this bt exchange s a p rate
	 */
	public long getBtExchangeSAPRateId();

	/**
	 * Sets the bt exchange s a p rate ID of this bt exchange s a p rate.
	 *
	 * @param btExchangeSAPRateId the bt exchange s a p rate ID of this bt exchange s a p rate
	 */
	public void setBtExchangeSAPRateId(long btExchangeSAPRateId);

	/**
	 * Returns the from currency of this bt exchange s a p rate.
	 *
	 * @return the from currency of this bt exchange s a p rate
	 */
	@AutoEscape
	public String getFromCurrency();

	/**
	 * Sets the from currency of this bt exchange s a p rate.
	 *
	 * @param fromCurrency the from currency of this bt exchange s a p rate
	 */
	public void setFromCurrency(String fromCurrency);

	/**
	 * Returns the to currency of this bt exchange s a p rate.
	 *
	 * @return the to currency of this bt exchange s a p rate
	 */
	@AutoEscape
	public String getToCurrency();

	/**
	 * Sets the to currency of this bt exchange s a p rate.
	 *
	 * @param toCurrency the to currency of this bt exchange s a p rate
	 */
	public void setToCurrency(String toCurrency);

	/**
	 * Returns the currency rate of this bt exchange s a p rate.
	 *
	 * @return the currency rate of this bt exchange s a p rate
	 */
	public double getCurrencyRate();

	/**
	 * Sets the currency rate of this bt exchange s a p rate.
	 *
	 * @param currencyRate the currency rate of this bt exchange s a p rate
	 */
	public void setCurrencyRate(double currencyRate);

	/**
	 * Returns the rate type of this bt exchange s a p rate.
	 *
	 * @return the rate type of this bt exchange s a p rate
	 */
	@AutoEscape
	public String getRateType();

	/**
	 * Sets the rate type of this bt exchange s a p rate.
	 *
	 * @param rateType the rate type of this bt exchange s a p rate
	 */
	public void setRateType(String rateType);

	/**
	 * Returns the sap date of this bt exchange s a p rate.
	 *
	 * @return the sap date of this bt exchange s a p rate
	 */
	public Date getSapDate();

	/**
	 * Sets the sap date of this bt exchange s a p rate.
	 *
	 * @param sapDate the sap date of this bt exchange s a p rate
	 */
	public void setSapDate(Date sapDate);

	/**
	 * Returns the import date of this bt exchange s a p rate.
	 *
	 * @return the import date of this bt exchange s a p rate
	 */
	public Date getImportDate();

	/**
	 * Sets the import date of this bt exchange s a p rate.
	 *
	 * @param importDate the import date of this bt exchange s a p rate
	 */
	public void setImportDate(Date importDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.business.trip.model.BtExchangeSAPRate btExchangeSAPRate);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.business.trip.model.BtExchangeSAPRate> toCacheModel();

	@Override
	public com.business.trip.model.BtExchangeSAPRate toEscapedModel();

	@Override
	public com.business.trip.model.BtExchangeSAPRate toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}