/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.business.trip.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BtHotelInfo service. Represents a row in the &quot;vgcapon_BtHotelInfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.business.trip.model.impl.BtHotelInfoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.business.trip.model.impl.BtHotelInfoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BtHotelInfo
 * @see com.business.trip.model.impl.BtHotelInfoImpl
 * @see com.business.trip.model.impl.BtHotelInfoModelImpl
 * @generated
 */
public interface BtHotelInfoModel extends BaseModel<BtHotelInfo> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bt hotel info model instance should use the {@link BtHotelInfo} interface instead.
	 */

	/**
	 * Returns the primary key of this bt hotel info.
	 *
	 * @return the primary key of this bt hotel info
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bt hotel info.
	 *
	 * @param primaryKey the primary key of this bt hotel info
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the bt hotel info ID of this bt hotel info.
	 *
	 * @return the bt hotel info ID of this bt hotel info
	 */
	public long getBtHotelInfoId();

	/**
	 * Sets the bt hotel info ID of this bt hotel info.
	 *
	 * @param btHotelInfoId the bt hotel info ID of this bt hotel info
	 */
	public void setBtHotelInfoId(long btHotelInfoId);

	/**
	 * Returns the business trip pk ID of this bt hotel info.
	 *
	 * @return the business trip pk ID of this bt hotel info
	 */
	public long getBusinessTripPkId();

	/**
	 * Sets the business trip pk ID of this bt hotel info.
	 *
	 * @param businessTripPkId the business trip pk ID of this bt hotel info
	 */
	public void setBusinessTripPkId(long businessTripPkId);

	/**
	 * Returns the ticket no of this bt hotel info.
	 *
	 * @return the ticket no of this bt hotel info
	 */
	@AutoEscape
	public String getTicketNo();

	/**
	 * Sets the ticket no of this bt hotel info.
	 *
	 * @param ticketNo the ticket no of this bt hotel info
	 */
	public void setTicketNo(String ticketNo);

	/**
	 * Returns the city of this bt hotel info.
	 *
	 * @return the city of this bt hotel info
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this bt hotel info.
	 *
	 * @param city the city of this bt hotel info
	 */
	public void setCity(String city);

	/**
	 * Returns the city type of this bt hotel info.
	 *
	 * @return the city type of this bt hotel info
	 */
	@AutoEscape
	public String getCityType();

	/**
	 * Sets the city type of this bt hotel info.
	 *
	 * @param cityType the city type of this bt hotel info
	 */
	public void setCityType(String cityType);

	/**
	 * Returns the hotel of this bt hotel info.
	 *
	 * @return the hotel of this bt hotel info
	 */
	@AutoEscape
	public String getHotel();

	/**
	 * Sets the hotel of this bt hotel info.
	 *
	 * @param hotel the hotel of this bt hotel info
	 */
	public void setHotel(String hotel);

	/**
	 * Returns the check in of this bt hotel info.
	 *
	 * @return the check in of this bt hotel info
	 */
	public Date getCheckIn();

	/**
	 * Sets the check in of this bt hotel info.
	 *
	 * @param checkIn the check in of this bt hotel info
	 */
	public void setCheckIn(Date checkIn);

	/**
	 * Returns the check out of this bt hotel info.
	 *
	 * @return the check out of this bt hotel info
	 */
	public Date getCheckOut();

	/**
	 * Sets the check out of this bt hotel info.
	 *
	 * @param checkOut the check out of this bt hotel info
	 */
	public void setCheckOut(Date checkOut);

	/**
	 * Returns the room category of this bt hotel info.
	 *
	 * @return the room category of this bt hotel info
	 */
	@AutoEscape
	public String getRoomCategory();

	/**
	 * Sets the room category of this bt hotel info.
	 *
	 * @param roomCategory the room category of this bt hotel info
	 */
	public void setRoomCategory(String roomCategory);

	/**
	 * Returns the price of this bt hotel info.
	 *
	 * @return the price of this bt hotel info
	 */
	public double getPrice();

	/**
	 * Sets the price of this bt hotel info.
	 *
	 * @param price the price of this bt hotel info
	 */
	public void setPrice(double price);

	/**
	 * Returns the currency of this bt hotel info.
	 *
	 * @return the currency of this bt hotel info
	 */
	@AutoEscape
	public String getCurrency();

	/**
	 * Sets the currency of this bt hotel info.
	 *
	 * @param currency the currency of this bt hotel info
	 */
	public void setCurrency(String currency);

	/**
	 * Returns the other reason info of this bt hotel info.
	 *
	 * @return the other reason info of this bt hotel info
	 */
	@AutoEscape
	public String getOtherReasonInfo();

	/**
	 * Sets the other reason info of this bt hotel info.
	 *
	 * @param otherReasonInfo the other reason info of this bt hotel info
	 */
	public void setOtherReasonInfo(String otherReasonInfo);

	/**
	 * Returns the is not booked from t a of this bt hotel info.
	 *
	 * @return the is not booked from t a of this bt hotel info
	 */
	public boolean getIsNotBookedFromTA();

	/**
	 * Returns <code>true</code> if this bt hotel info is is not booked from t a.
	 *
	 * @return <code>true</code> if this bt hotel info is is not booked from t a; <code>false</code> otherwise
	 */
	public boolean isIsNotBookedFromTA();

	/**
	 * Sets whether this bt hotel info is is not booked from t a.
	 *
	 * @param isNotBookedFromTA the is not booked from t a of this bt hotel info
	 */
	public void setIsNotBookedFromTA(boolean isNotBookedFromTA);

	/**
	 * Returns the is over budget of this bt hotel info.
	 *
	 * @return the is over budget of this bt hotel info
	 */
	public int getIsOverBudget();

	/**
	 * Sets the is over budget of this bt hotel info.
	 *
	 * @param isOverBudget the is over budget of this bt hotel info
	 */
	public void setIsOverBudget(int isOverBudget);

	/**
	 * Returns the others specify of this bt hotel info.
	 *
	 * @return the others specify of this bt hotel info
	 */
	@AutoEscape
	public String getOthersSpecify();

	/**
	 * Sets the others specify of this bt hotel info.
	 *
	 * @param othersSpecify the others specify of this bt hotel info
	 */
	public void setOthersSpecify(String othersSpecify);

	/**
	 * Returns the trip type of this bt hotel info.
	 *
	 * @return the trip type of this bt hotel info
	 */
	@AutoEscape
	public String getTripType();

	/**
	 * Sets the trip type of this bt hotel info.
	 *
	 * @param tripType the trip type of this bt hotel info
	 */
	public void setTripType(String tripType);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.business.trip.model.BtHotelInfo btHotelInfo);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.business.trip.model.BtHotelInfo> toCacheModel();

	@Override
	public com.business.trip.model.BtHotelInfo toEscapedModel();

	@Override
	public com.business.trip.model.BtHotelInfo toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}