/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.business.trip.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BtReimbursementSAPInfo service. Represents a row in the &quot;vgcapon_BtReimbursementSAPInfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.business.trip.model.impl.BtReimbursementSAPInfoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.business.trip.model.impl.BtReimbursementSAPInfoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BtReimbursementSAPInfo
 * @see com.business.trip.model.impl.BtReimbursementSAPInfoImpl
 * @see com.business.trip.model.impl.BtReimbursementSAPInfoModelImpl
 * @generated
 */
public interface BtReimbursementSAPInfoModel extends BaseModel<BtReimbursementSAPInfo> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bt reimbursement s a p info model instance should use the {@link BtReimbursementSAPInfo} interface instead.
	 */

	/**
	 * Returns the primary key of this bt reimbursement s a p info.
	 *
	 * @return the primary key of this bt reimbursement s a p info
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bt reimbursement s a p info.
	 *
	 * @param primaryKey the primary key of this bt reimbursement s a p info
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the bt reimbursement s a p info ID of this bt reimbursement s a p info.
	 *
	 * @return the bt reimbursement s a p info ID of this bt reimbursement s a p info
	 */
	public long getBtReimbursementSAPInfoId();

	/**
	 * Sets the bt reimbursement s a p info ID of this bt reimbursement s a p info.
	 *
	 * @param btReimbursementSAPInfoId the bt reimbursement s a p info ID of this bt reimbursement s a p info
	 */
	public void setBtReimbursementSAPInfoId(long btReimbursementSAPInfoId);

	/**
	 * Returns the business trip pk ID of this bt reimbursement s a p info.
	 *
	 * @return the business trip pk ID of this bt reimbursement s a p info
	 */
	public long getBusinessTripPkId();

	/**
	 * Sets the business trip pk ID of this bt reimbursement s a p info.
	 *
	 * @param businessTripPkId the business trip pk ID of this bt reimbursement s a p info
	 */
	public void setBusinessTripPkId(long businessTripPkId);

	/**
	 * Returns the ticket no of this bt reimbursement s a p info.
	 *
	 * @return the ticket no of this bt reimbursement s a p info
	 */
	@AutoEscape
	public String getTicketNo();

	/**
	 * Sets the ticket no of this bt reimbursement s a p info.
	 *
	 * @param ticketNo the ticket no of this bt reimbursement s a p info
	 */
	public void setTicketNo(String ticketNo);

	/**
	 * Returns the currency of this bt reimbursement s a p info.
	 *
	 * @return the currency of this bt reimbursement s a p info
	 */
	@AutoEscape
	public String getCurrency();

	/**
	 * Sets the currency of this bt reimbursement s a p info.
	 *
	 * @param currency the currency of this bt reimbursement s a p info
	 */
	public void setCurrency(String currency);

	/**
	 * Returns the step of this bt reimbursement s a p info.
	 *
	 * @return the step of this bt reimbursement s a p info
	 */
	public int getStep();

	/**
	 * Sets the step of this bt reimbursement s a p info.
	 *
	 * @param step the step of this bt reimbursement s a p info
	 */
	public void setStep(int step);

	/**
	 * Returns the message type of this bt reimbursement s a p info.
	 *
	 * @return the message type of this bt reimbursement s a p info
	 */
	@AutoEscape
	public String getMessageType();

	/**
	 * Sets the message type of this bt reimbursement s a p info.
	 *
	 * @param messageType the message type of this bt reimbursement s a p info
	 */
	public void setMessageType(String messageType);

	/**
	 * Returns the message of this bt reimbursement s a p info.
	 *
	 * @return the message of this bt reimbursement s a p info
	 */
	@AutoEscape
	public String getMessage();

	/**
	 * Sets the message of this bt reimbursement s a p info.
	 *
	 * @param message the message of this bt reimbursement s a p info
	 */
	public void setMessage(String message);

	/**
	 * Returns the certificate no of this bt reimbursement s a p info.
	 *
	 * @return the certificate no of this bt reimbursement s a p info
	 */
	@AutoEscape
	public String getCertificateNo();

	/**
	 * Sets the certificate no of this bt reimbursement s a p info.
	 *
	 * @param certificateNo the certificate no of this bt reimbursement s a p info
	 */
	public void setCertificateNo(String certificateNo);

	/**
	 * Returns the company of this bt reimbursement s a p info.
	 *
	 * @return the company of this bt reimbursement s a p info
	 */
	@AutoEscape
	public String getCompany();

	/**
	 * Sets the company of this bt reimbursement s a p info.
	 *
	 * @param company the company of this bt reimbursement s a p info
	 */
	public void setCompany(String company);

	/**
	 * Returns the year of this bt reimbursement s a p info.
	 *
	 * @return the year of this bt reimbursement s a p info
	 */
	@AutoEscape
	public String getYear();

	/**
	 * Sets the year of this bt reimbursement s a p info.
	 *
	 * @param year the year of this bt reimbursement s a p info
	 */
	public void setYear(String year);

	/**
	 * Returns the create date of this bt reimbursement s a p info.
	 *
	 * @return the create date of this bt reimbursement s a p info
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this bt reimbursement s a p info.
	 *
	 * @param createDate the create date of this bt reimbursement s a p info
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this bt reimbursement s a p info.
	 *
	 * @return the modified date of this bt reimbursement s a p info
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this bt reimbursement s a p info.
	 *
	 * @param modifiedDate the modified date of this bt reimbursement s a p info
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.business.trip.model.BtReimbursementSAPInfo btReimbursementSAPInfo);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.business.trip.model.BtReimbursementSAPInfo> toCacheModel();

	@Override
	public com.business.trip.model.BtReimbursementSAPInfo toEscapedModel();

	@Override
	public com.business.trip.model.BtReimbursementSAPInfo toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}