/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.business.trip.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the BtTravelExpense service. Represents a row in the &quot;vgcapon_BtTravelExpense&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.business.trip.model.impl.BtTravelExpenseModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.business.trip.model.impl.BtTravelExpenseImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BtTravelExpense
 * @see com.business.trip.model.impl.BtTravelExpenseImpl
 * @see com.business.trip.model.impl.BtTravelExpenseModelImpl
 * @generated
 */
public interface BtTravelExpenseModel extends BaseModel<BtTravelExpense> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bt travel expense model instance should use the {@link BtTravelExpense} interface instead.
	 */

	/**
	 * Returns the primary key of this bt travel expense.
	 *
	 * @return the primary key of this bt travel expense
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bt travel expense.
	 *
	 * @param primaryKey the primary key of this bt travel expense
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the bt travel expense ID of this bt travel expense.
	 *
	 * @return the bt travel expense ID of this bt travel expense
	 */
	public long getBtTravelExpenseId();

	/**
	 * Sets the bt travel expense ID of this bt travel expense.
	 *
	 * @param btTravelExpenseId the bt travel expense ID of this bt travel expense
	 */
	public void setBtTravelExpenseId(long btTravelExpenseId);

	/**
	 * Returns the business trip pk ID of this bt travel expense.
	 *
	 * @return the business trip pk ID of this bt travel expense
	 */
	public long getBusinessTripPkId();

	/**
	 * Sets the business trip pk ID of this bt travel expense.
	 *
	 * @param businessTripPkId the business trip pk ID of this bt travel expense
	 */
	public void setBusinessTripPkId(long businessTripPkId);

	/**
	 * Returns the ticket no of this bt travel expense.
	 *
	 * @return the ticket no of this bt travel expense
	 */
	@AutoEscape
	public String getTicketNo();

	/**
	 * Sets the ticket no of this bt travel expense.
	 *
	 * @param ticketNo the ticket no of this bt travel expense
	 */
	public void setTicketNo(String ticketNo);

	/**
	 * Returns the travel date of this bt travel expense.
	 *
	 * @return the travel date of this bt travel expense
	 */
	@AutoEscape
	public String getTravelDate();

	/**
	 * Sets the travel date of this bt travel expense.
	 *
	 * @param travelDate the travel date of this bt travel expense
	 */
	public void setTravelDate(String travelDate);

	/**
	 * Returns the departure of this bt travel expense.
	 *
	 * @return the departure of this bt travel expense
	 */
	@AutoEscape
	public String getDeparture();

	/**
	 * Sets the departure of this bt travel expense.
	 *
	 * @param departure the departure of this bt travel expense
	 */
	public void setDeparture(String departure);

	/**
	 * Returns the arrival of this bt travel expense.
	 *
	 * @return the arrival of this bt travel expense
	 */
	@AutoEscape
	public String getArrival();

	/**
	 * Sets the arrival of this bt travel expense.
	 *
	 * @param arrival the arrival of this bt travel expense
	 */
	public void setArrival(String arrival);

	/**
	 * Returns the from city of this bt travel expense.
	 *
	 * @return the from city of this bt travel expense
	 */
	@AutoEscape
	public String getFromCity();

	/**
	 * Sets the from city of this bt travel expense.
	 *
	 * @param fromCity the from city of this bt travel expense
	 */
	public void setFromCity(String fromCity);

	/**
	 * Returns the to city of this bt travel expense.
	 *
	 * @return the to city of this bt travel expense
	 */
	@AutoEscape
	public String getToCity();

	/**
	 * Sets the to city of this bt travel expense.
	 *
	 * @param toCity the to city of this bt travel expense
	 */
	public void setToCity(String toCity);

	/**
	 * Returns the is has breakfast of this bt travel expense.
	 *
	 * @return the is has breakfast of this bt travel expense
	 */
	public boolean getIsHasBreakfast();

	/**
	 * Returns <code>true</code> if this bt travel expense is is has breakfast.
	 *
	 * @return <code>true</code> if this bt travel expense is is has breakfast; <code>false</code> otherwise
	 */
	public boolean isIsHasBreakfast();

	/**
	 * Sets whether this bt travel expense is is has breakfast.
	 *
	 * @param isHasBreakfast the is has breakfast of this bt travel expense
	 */
	public void setIsHasBreakfast(boolean isHasBreakfast);

	/**
	 * Returns the is has lunch of this bt travel expense.
	 *
	 * @return the is has lunch of this bt travel expense
	 */
	public boolean getIsHasLunch();

	/**
	 * Returns <code>true</code> if this bt travel expense is is has lunch.
	 *
	 * @return <code>true</code> if this bt travel expense is is has lunch; <code>false</code> otherwise
	 */
	public boolean isIsHasLunch();

	/**
	 * Sets whether this bt travel expense is is has lunch.
	 *
	 * @param isHasLunch the is has lunch of this bt travel expense
	 */
	public void setIsHasLunch(boolean isHasLunch);

	/**
	 * Returns the is has dinner of this bt travel expense.
	 *
	 * @return the is has dinner of this bt travel expense
	 */
	public boolean getIsHasDinner();

	/**
	 * Returns <code>true</code> if this bt travel expense is is has dinner.
	 *
	 * @return <code>true</code> if this bt travel expense is is has dinner; <code>false</code> otherwise
	 */
	public boolean isIsHasDinner();

	/**
	 * Sets whether this bt travel expense is is has dinner.
	 *
	 * @param isHasDinner the is has dinner of this bt travel expense
	 */
	public void setIsHasDinner(boolean isHasDinner);

	/**
	 * Returns the country of this bt travel expense.
	 *
	 * @return the country of this bt travel expense
	 */
	@AutoEscape
	public String getCountry();

	/**
	 * Sets the country of this bt travel expense.
	 *
	 * @param country the country of this bt travel expense
	 */
	public void setCountry(String country);

	/**
	 * Returns the city of this bt travel expense.
	 *
	 * @return the city of this bt travel expense
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this bt travel expense.
	 *
	 * @param city the city of this bt travel expense
	 */
	public void setCity(String city);

	/**
	 * Returns the rate of dma of this bt travel expense.
	 *
	 * @return the rate of dma of this bt travel expense
	 */
	public double getRateOfDma();

	/**
	 * Sets the rate of dma of this bt travel expense.
	 *
	 * @param rateOfDma the rate of dma of this bt travel expense
	 */
	public void setRateOfDma(double rateOfDma);

	/**
	 * Returns the currency of this bt travel expense.
	 *
	 * @return the currency of this bt travel expense
	 */
	@AutoEscape
	public String getCurrency();

	/**
	 * Sets the currency of this bt travel expense.
	 *
	 * @param currency the currency of this bt travel expense
	 */
	public void setCurrency(String currency);

	/**
	 * Returns the allowance of this bt travel expense.
	 *
	 * @return the allowance of this bt travel expense
	 */
	public double getAllowance();

	/**
	 * Sets the allowance of this bt travel expense.
	 *
	 * @param allowance the allowance of this bt travel expense
	 */
	public void setAllowance(double allowance);

	/**
	 * Returns the comments of this bt travel expense.
	 *
	 * @return the comments of this bt travel expense
	 */
	@AutoEscape
	public String getComments();

	/**
	 * Sets the comments of this bt travel expense.
	 *
	 * @param comments the comments of this bt travel expense
	 */
	public void setComments(String comments);

	/**
	 * Returns the trip type of this bt travel expense.
	 *
	 * @return the trip type of this bt travel expense
	 */
	@AutoEscape
	public String getTripType();

	/**
	 * Sets the trip type of this bt travel expense.
	 *
	 * @param tripType the trip type of this bt travel expense
	 */
	public void setTripType(String tripType);

	/**
	 * Returns the allowance rmb of this bt travel expense.
	 *
	 * @return the allowance rmb of this bt travel expense
	 */
	public double getAllowanceRmb();

	/**
	 * Sets the allowance rmb of this bt travel expense.
	 *
	 * @param allowanceRmb the allowance rmb of this bt travel expense
	 */
	public void setAllowanceRmb(double allowanceRmb);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.business.trip.model.BtTravelExpense btTravelExpense);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.business.trip.model.BtTravelExpense> toCacheModel();

	@Override
	public com.business.trip.model.BtTravelExpense toEscapedModel();

	@Override
	public com.business.trip.model.BtTravelExpense toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}