/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.e.closing.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.model.WorkflowedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EClosing service. Represents a row in the &quot;vgcapon_EClosing&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.e.closing.model.impl.EClosingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.e.closing.model.impl.EClosingImpl}.
 * </p>
 *
 * @author t.a.jiang
 * @see EClosing
 * @see com.e.closing.model.impl.EClosingImpl
 * @see com.e.closing.model.impl.EClosingModelImpl
 * @generated
 */
public interface EClosingModel extends BaseModel<EClosing>, GroupedModel,
	WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e closing model instance should use the {@link EClosing} interface instead.
	 */

	/**
	 * Returns the primary key of this e closing.
	 *
	 * @return the primary key of this e closing
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e closing.
	 *
	 * @param primaryKey the primary key of this e closing
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the eclosing ID of this e closing.
	 *
	 * @return the eclosing ID of this e closing
	 */
	public long getEclosingId();

	/**
	 * Sets the eclosing ID of this e closing.
	 *
	 * @param eclosingId the eclosing ID of this e closing
	 */
	public void setEclosingId(long eclosingId);

	/**
	 * Returns the group ID of this e closing.
	 *
	 * @return the group ID of this e closing
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this e closing.
	 *
	 * @param groupId the group ID of this e closing
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this e closing.
	 *
	 * @return the company ID of this e closing
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this e closing.
	 *
	 * @param companyId the company ID of this e closing
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this e closing.
	 *
	 * @return the user ID of this e closing
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this e closing.
	 *
	 * @param userId the user ID of this e closing
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this e closing.
	 *
	 * @return the user uuid of this e closing
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this e closing.
	 *
	 * @param userUuid the user uuid of this e closing
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this e closing.
	 *
	 * @return the user name of this e closing
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this e closing.
	 *
	 * @param userName the user name of this e closing
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this e closing.
	 *
	 * @return the create date of this e closing
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this e closing.
	 *
	 * @param createDate the create date of this e closing
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this e closing.
	 *
	 * @return the modified date of this e closing
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this e closing.
	 *
	 * @param modifiedDate the modified date of this e closing
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the ticket no of this e closing.
	 *
	 * @return the ticket no of this e closing
	 */
	@AutoEscape
	public String getTicketNo();

	/**
	 * Sets the ticket no of this e closing.
	 *
	 * @param ticketNo the ticket no of this e closing
	 */
	public void setTicketNo(String ticketNo);

	/**
	 * Returns the staff code of this e closing.
	 *
	 * @return the staff code of this e closing
	 */
	public int getStaffCode();

	/**
	 * Sets the staff code of this e closing.
	 *
	 * @param staffCode the staff code of this e closing
	 */
	public void setStaffCode(int staffCode);

	/**
	 * Returns the staff name of this e closing.
	 *
	 * @return the staff name of this e closing
	 */
	@AutoEscape
	public String getStaffName();

	/**
	 * Sets the staff name of this e closing.
	 *
	 * @param staffName the staff name of this e closing
	 */
	public void setStaffName(String staffName);

	/**
	 * Returns the company of this e closing.
	 *
	 * @return the company of this e closing
	 */
	@AutoEscape
	public String getCompany();

	/**
	 * Sets the company of this e closing.
	 *
	 * @param company the company of this e closing
	 */
	public void setCompany(String company);

	/**
	 * Returns the division of this e closing.
	 *
	 * @return the division of this e closing
	 */
	@AutoEscape
	public String getDivision();

	/**
	 * Sets the division of this e closing.
	 *
	 * @param division the division of this e closing
	 */
	public void setDivision(String division);

	/**
	 * Returns the department of this e closing.
	 *
	 * @return the department of this e closing
	 */
	@AutoEscape
	public String getDepartment();

	/**
	 * Sets the department of this e closing.
	 *
	 * @param department the department of this e closing
	 */
	public void setDepartment(String department);

	/**
	 * Returns the cost center of this e closing.
	 *
	 * @return the cost center of this e closing
	 */
	@AutoEscape
	public String getCostCenter();

	/**
	 * Sets the cost center of this e closing.
	 *
	 * @param costCenter the cost center of this e closing
	 */
	public void setCostCenter(String costCenter);

	/**
	 * Returns the function name of this e closing.
	 *
	 * @return the function name of this e closing
	 */
	@AutoEscape
	public String getFunctionName();

	/**
	 * Sets the function name of this e closing.
	 *
	 * @param functionName the function name of this e closing
	 */
	public void setFunctionName(String functionName);

	/**
	 * Returns the position code of this e closing.
	 *
	 * @return the position code of this e closing
	 */
	@AutoEscape
	public String getPositionCode();

	/**
	 * Sets the position code of this e closing.
	 *
	 * @param positionCode the position code of this e closing
	 */
	public void setPositionCode(String positionCode);

	/**
	 * Returns the employee group ID of this e closing.
	 *
	 * @return the employee group ID of this e closing
	 */
	@AutoEscape
	public String getEmployeeGroupId();

	/**
	 * Sets the employee group ID of this e closing.
	 *
	 * @param employeeGroupId the employee group ID of this e closing
	 */
	public void setEmployeeGroupId(String employeeGroupId);

	/**
	 * Returns the employee group name of this e closing.
	 *
	 * @return the employee group name of this e closing
	 */
	@AutoEscape
	public String getEmployeeGroupName();

	/**
	 * Sets the employee group name of this e closing.
	 *
	 * @param employeeGroupName the employee group name of this e closing
	 */
	public void setEmployeeGroupName(String employeeGroupName);

	/**
	 * Returns the private email address of this e closing.
	 *
	 * @return the private email address of this e closing
	 */
	@AutoEscape
	public String getPrivateEmailAddress();

	/**
	 * Sets the private email address of this e closing.
	 *
	 * @param privateEmailAddress the private email address of this e closing
	 */
	public void setPrivateEmailAddress(String privateEmailAddress);

	/**
	 * Returns the starting date of this e closing.
	 *
	 * @return the starting date of this e closing
	 */
	public Date getStartingDate();

	/**
	 * Sets the starting date of this e closing.
	 *
	 * @param startingDate the starting date of this e closing
	 */
	public void setStartingDate(Date startingDate);

	/**
	 * Returns the last working day of this e closing.
	 *
	 * @return the last working day of this e closing
	 */
	public Date getLastWorkingDay();

	/**
	 * Sets the last working day of this e closing.
	 *
	 * @param lastWorkingDay the last working day of this e closing
	 */
	public void setLastWorkingDay(Date lastWorkingDay);

	/**
	 * Returns the finish contract date of this e closing.
	 *
	 * @return the finish contract date of this e closing
	 */
	public Date getFinishContractDate();

	/**
	 * Sets the finish contract date of this e closing.
	 *
	 * @param finishContractDate the finish contract date of this e closing
	 */
	public void setFinishContractDate(Date finishContractDate);

	/**
	 * Returns the seat office number of this e closing.
	 *
	 * @return the seat office number of this e closing
	 */
	@AutoEscape
	public String getSeatOfficeNumber();

	/**
	 * Sets the seat office number of this e closing.
	 *
	 * @param seatOfficeNumber the seat office number of this e closing
	 */
	public void setSeatOfficeNumber(String seatOfficeNumber);

	/**
	 * Returns the permanent address of this e closing.
	 *
	 * @return the permanent address of this e closing
	 */
	@AutoEscape
	public String getPermanentAddress();

	/**
	 * Sets the permanent address of this e closing.
	 *
	 * @param permanentAddress the permanent address of this e closing
	 */
	public void setPermanentAddress(String permanentAddress);

	/**
	 * Returns the dm option1 of this e closing.
	 *
	 * @return the dm option1 of this e closing
	 */
	public boolean getDmOption1();

	/**
	 * Returns <code>true</code> if this e closing is dm option1.
	 *
	 * @return <code>true</code> if this e closing is dm option1; <code>false</code> otherwise
	 */
	public boolean isDmOption1();

	/**
	 * Sets whether this e closing is dm option1.
	 *
	 * @param dmOption1 the dm option1 of this e closing
	 */
	public void setDmOption1(boolean dmOption1);

	/**
	 * Returns the dm option2 of this e closing.
	 *
	 * @return the dm option2 of this e closing
	 */
	public boolean getDmOption2();

	/**
	 * Returns <code>true</code> if this e closing is dm option2.
	 *
	 * @return <code>true</code> if this e closing is dm option2; <code>false</code> otherwise
	 */
	public boolean isDmOption2();

	/**
	 * Sets whether this e closing is dm option2.
	 *
	 * @param dmOption2 the dm option2 of this e closing
	 */
	public void setDmOption2(boolean dmOption2);

	/**
	 * Returns the dm status of this e closing.
	 *
	 * @return the dm status of this e closing
	 */
	@AutoEscape
	public String getDmStatus();

	/**
	 * Sets the dm status of this e closing.
	 *
	 * @param dmStatus the dm status of this e closing
	 */
	public void setDmStatus(String dmStatus);

	/**
	 * Returns the dm comments of this e closing.
	 *
	 * @return the dm comments of this e closing
	 */
	@AutoEscape
	public String getDmComments();

	/**
	 * Sets the dm comments of this e closing.
	 *
	 * @param dmComments the dm comments of this e closing
	 */
	public void setDmComments(String dmComments);

	/**
	 * Returns the ad option1 of this e closing.
	 *
	 * @return the ad option1 of this e closing
	 */
	public boolean getAdOption1();

	/**
	 * Returns <code>true</code> if this e closing is ad option1.
	 *
	 * @return <code>true</code> if this e closing is ad option1; <code>false</code> otherwise
	 */
	public boolean isAdOption1();

	/**
	 * Sets whether this e closing is ad option1.
	 *
	 * @param adOption1 the ad option1 of this e closing
	 */
	public void setAdOption1(boolean adOption1);

	/**
	 * Returns the ad option2 of this e closing.
	 *
	 * @return the ad option2 of this e closing
	 */
	public boolean getAdOption2();

	/**
	 * Returns <code>true</code> if this e closing is ad option2.
	 *
	 * @return <code>true</code> if this e closing is ad option2; <code>false</code> otherwise
	 */
	public boolean isAdOption2();

	/**
	 * Sets whether this e closing is ad option2.
	 *
	 * @param adOption2 the ad option2 of this e closing
	 */
	public void setAdOption2(boolean adOption2);

	/**
	 * Returns the ad option3 of this e closing.
	 *
	 * @return the ad option3 of this e closing
	 */
	public boolean getAdOption3();

	/**
	 * Returns <code>true</code> if this e closing is ad option3.
	 *
	 * @return <code>true</code> if this e closing is ad option3; <code>false</code> otherwise
	 */
	public boolean isAdOption3();

	/**
	 * Sets whether this e closing is ad option3.
	 *
	 * @param adOption3 the ad option3 of this e closing
	 */
	public void setAdOption3(boolean adOption3);

	/**
	 * Returns the ad option4 of this e closing.
	 *
	 * @return the ad option4 of this e closing
	 */
	public boolean getAdOption4();

	/**
	 * Returns <code>true</code> if this e closing is ad option4.
	 *
	 * @return <code>true</code> if this e closing is ad option4; <code>false</code> otherwise
	 */
	public boolean isAdOption4();

	/**
	 * Sets whether this e closing is ad option4.
	 *
	 * @param adOption4 the ad option4 of this e closing
	 */
	public void setAdOption4(boolean adOption4);

	/**
	 * Returns the ad finance fee of this e closing.
	 *
	 * @return the ad finance fee of this e closing
	 */
	public double getAdFinanceFee();

	/**
	 * Sets the ad finance fee of this e closing.
	 *
	 * @param adFinanceFee the ad finance fee of this e closing
	 */
	public void setAdFinanceFee(double adFinanceFee);

	/**
	 * Returns the ad status of this e closing.
	 *
	 * @return the ad status of this e closing
	 */
	@AutoEscape
	public String getAdStatus();

	/**
	 * Sets the ad status of this e closing.
	 *
	 * @param adStatus the ad status of this e closing
	 */
	public void setAdStatus(String adStatus);

	/**
	 * Returns the ad comments of this e closing.
	 *
	 * @return the ad comments of this e closing
	 */
	@AutoEscape
	public String getAdComments();

	/**
	 * Sets the ad comments of this e closing.
	 *
	 * @param adComments the ad comments of this e closing
	 */
	public void setAdComments(String adComments);

	/**
	 * Returns the fs option1 of this e closing.
	 *
	 * @return the fs option1 of this e closing
	 */
	public boolean getFsOption1();

	/**
	 * Returns <code>true</code> if this e closing is fs option1.
	 *
	 * @return <code>true</code> if this e closing is fs option1; <code>false</code> otherwise
	 */
	public boolean isFsOption1();

	/**
	 * Sets whether this e closing is fs option1.
	 *
	 * @param fsOption1 the fs option1 of this e closing
	 */
	public void setFsOption1(boolean fsOption1);

	/**
	 * Returns the fs status of this e closing.
	 *
	 * @return the fs status of this e closing
	 */
	@AutoEscape
	public String getFsStatus();

	/**
	 * Sets the fs status of this e closing.
	 *
	 * @param fsStatus the fs status of this e closing
	 */
	public void setFsStatus(String fsStatus);

	/**
	 * Returns the fs comments of this e closing.
	 *
	 * @return the fs comments of this e closing
	 */
	@AutoEscape
	public String getFsComments();

	/**
	 * Sets the fs comments of this e closing.
	 *
	 * @param fsComments the fs comments of this e closing
	 */
	public void setFsComments(String fsComments);

	/**
	 * Returns the flc option1 of this e closing.
	 *
	 * @return the flc option1 of this e closing
	 */
	public boolean getFlcOption1();

	/**
	 * Returns <code>true</code> if this e closing is flc option1.
	 *
	 * @return <code>true</code> if this e closing is flc option1; <code>false</code> otherwise
	 */
	public boolean isFlcOption1();

	/**
	 * Sets whether this e closing is flc option1.
	 *
	 * @param flcOption1 the flc option1 of this e closing
	 */
	public void setFlcOption1(boolean flcOption1);

	/**
	 * Returns the flc option2 of this e closing.
	 *
	 * @return the flc option2 of this e closing
	 */
	public boolean getFlcOption2();

	/**
	 * Returns <code>true</code> if this e closing is flc option2.
	 *
	 * @return <code>true</code> if this e closing is flc option2; <code>false</code> otherwise
	 */
	public boolean isFlcOption2();

	/**
	 * Sets whether this e closing is flc option2.
	 *
	 * @param flcOption2 the flc option2 of this e closing
	 */
	public void setFlcOption2(boolean flcOption2);

	/**
	 * Returns the flc status of this e closing.
	 *
	 * @return the flc status of this e closing
	 */
	@AutoEscape
	public String getFlcStatus();

	/**
	 * Sets the flc status of this e closing.
	 *
	 * @param flcStatus the flc status of this e closing
	 */
	public void setFlcStatus(String flcStatus);

	/**
	 * Returns the flc comments of this e closing.
	 *
	 * @return the flc comments of this e closing
	 */
	@AutoEscape
	public String getFlcComments();

	/**
	 * Sets the flc comments of this e closing.
	 *
	 * @param flcComments the flc comments of this e closing
	 */
	public void setFlcComments(String flcComments);

	/**
	 * Returns the security option1 of this e closing.
	 *
	 * @return the security option1 of this e closing
	 */
	public boolean getSecurityOption1();

	/**
	 * Returns <code>true</code> if this e closing is security option1.
	 *
	 * @return <code>true</code> if this e closing is security option1; <code>false</code> otherwise
	 */
	public boolean isSecurityOption1();

	/**
	 * Sets whether this e closing is security option1.
	 *
	 * @param securityOption1 the security option1 of this e closing
	 */
	public void setSecurityOption1(boolean securityOption1);

	/**
	 * Returns the security finance fee of this e closing.
	 *
	 * @return the security finance fee of this e closing
	 */
	public double getSecurityFinanceFee();

	/**
	 * Sets the security finance fee of this e closing.
	 *
	 * @param securityFinanceFee the security finance fee of this e closing
	 */
	public void setSecurityFinanceFee(double securityFinanceFee);

	/**
	 * Returns the security status of this e closing.
	 *
	 * @return the security status of this e closing
	 */
	@AutoEscape
	public String getSecurityStatus();

	/**
	 * Sets the security status of this e closing.
	 *
	 * @param securityStatus the security status of this e closing
	 */
	public void setSecurityStatus(String securityStatus);

	/**
	 * Returns the security comments of this e closing.
	 *
	 * @return the security comments of this e closing
	 */
	@AutoEscape
	public String getSecurityComments();

	/**
	 * Sets the security comments of this e closing.
	 *
	 * @param securityComments the security comments of this e closing
	 */
	public void setSecurityComments(String securityComments);

	/**
	 * Returns the id option1 of this e closing.
	 *
	 * @return the id option1 of this e closing
	 */
	public boolean getIdOption1();

	/**
	 * Returns <code>true</code> if this e closing is id option1.
	 *
	 * @return <code>true</code> if this e closing is id option1; <code>false</code> otherwise
	 */
	public boolean isIdOption1();

	/**
	 * Sets whether this e closing is id option1.
	 *
	 * @param idOption1 the id option1 of this e closing
	 */
	public void setIdOption1(boolean idOption1);

	/**
	 * Returns the id option2 of this e closing.
	 *
	 * @return the id option2 of this e closing
	 */
	public boolean getIdOption2();

	/**
	 * Returns <code>true</code> if this e closing is id option2.
	 *
	 * @return <code>true</code> if this e closing is id option2; <code>false</code> otherwise
	 */
	public boolean isIdOption2();

	/**
	 * Sets whether this e closing is id option2.
	 *
	 * @param idOption2 the id option2 of this e closing
	 */
	public void setIdOption2(boolean idOption2);

	/**
	 * Returns the id option3 of this e closing.
	 *
	 * @return the id option3 of this e closing
	 */
	public boolean getIdOption3();

	/**
	 * Returns <code>true</code> if this e closing is id option3.
	 *
	 * @return <code>true</code> if this e closing is id option3; <code>false</code> otherwise
	 */
	public boolean isIdOption3();

	/**
	 * Sets whether this e closing is id option3.
	 *
	 * @param idOption3 the id option3 of this e closing
	 */
	public void setIdOption3(boolean idOption3);

	/**
	 * Returns the id option4 of this e closing.
	 *
	 * @return the id option4 of this e closing
	 */
	public boolean getIdOption4();

	/**
	 * Returns <code>true</code> if this e closing is id option4.
	 *
	 * @return <code>true</code> if this e closing is id option4; <code>false</code> otherwise
	 */
	public boolean isIdOption4();

	/**
	 * Sets whether this e closing is id option4.
	 *
	 * @param idOption4 the id option4 of this e closing
	 */
	public void setIdOption4(boolean idOption4);

	/**
	 * Returns the id option5 of this e closing.
	 *
	 * @return the id option5 of this e closing
	 */
	public boolean getIdOption5();

	/**
	 * Returns <code>true</code> if this e closing is id option5.
	 *
	 * @return <code>true</code> if this e closing is id option5; <code>false</code> otherwise
	 */
	public boolean isIdOption5();

	/**
	 * Sets whether this e closing is id option5.
	 *
	 * @param idOption5 the id option5 of this e closing
	 */
	public void setIdOption5(boolean idOption5);

	/**
	 * Returns the id option6 of this e closing.
	 *
	 * @return the id option6 of this e closing
	 */
	public boolean getIdOption6();

	/**
	 * Returns <code>true</code> if this e closing is id option6.
	 *
	 * @return <code>true</code> if this e closing is id option6; <code>false</code> otherwise
	 */
	public boolean isIdOption6();

	/**
	 * Sets whether this e closing is id option6.
	 *
	 * @param idOption6 the id option6 of this e closing
	 */
	public void setIdOption6(boolean idOption6);

	/**
	 * Returns the id option7 of this e closing.
	 *
	 * @return the id option7 of this e closing
	 */
	public boolean getIdOption7();

	/**
	 * Returns <code>true</code> if this e closing is id option7.
	 *
	 * @return <code>true</code> if this e closing is id option7; <code>false</code> otherwise
	 */
	public boolean isIdOption7();

	/**
	 * Sets whether this e closing is id option7.
	 *
	 * @param idOption7 the id option7 of this e closing
	 */
	public void setIdOption7(boolean idOption7);

	/**
	 * Returns the id option8 of this e closing.
	 *
	 * @return the id option8 of this e closing
	 */
	public boolean getIdOption8();

	/**
	 * Returns <code>true</code> if this e closing is id option8.
	 *
	 * @return <code>true</code> if this e closing is id option8; <code>false</code> otherwise
	 */
	public boolean isIdOption8();

	/**
	 * Sets whether this e closing is id option8.
	 *
	 * @param idOption8 the id option8 of this e closing
	 */
	public void setIdOption8(boolean idOption8);

	/**
	 * Returns the id option9 of this e closing.
	 *
	 * @return the id option9 of this e closing
	 */
	public boolean getIdOption9();

	/**
	 * Returns <code>true</code> if this e closing is id option9.
	 *
	 * @return <code>true</code> if this e closing is id option9; <code>false</code> otherwise
	 */
	public boolean isIdOption9();

	/**
	 * Sets whether this e closing is id option9.
	 *
	 * @param idOption9 the id option9 of this e closing
	 */
	public void setIdOption9(boolean idOption9);

	/**
	 * Returns the id hr fee of this e closing.
	 *
	 * @return the id hr fee of this e closing
	 */
	public double getIdHrFee();

	/**
	 * Sets the id hr fee of this e closing.
	 *
	 * @param idHrFee the id hr fee of this e closing
	 */
	public void setIdHrFee(double idHrFee);

	/**
	 * Returns the id finance fee of this e closing.
	 *
	 * @return the id finance fee of this e closing
	 */
	public double getIdFinanceFee();

	/**
	 * Sets the id finance fee of this e closing.
	 *
	 * @param idFinanceFee the id finance fee of this e closing
	 */
	public void setIdFinanceFee(double idFinanceFee);

	/**
	 * Returns the id status of this e closing.
	 *
	 * @return the id status of this e closing
	 */
	@AutoEscape
	public String getIdStatus();

	/**
	 * Sets the id status of this e closing.
	 *
	 * @param idStatus the id status of this e closing
	 */
	public void setIdStatus(String idStatus);

	/**
	 * Returns the id comments of this e closing.
	 *
	 * @return the id comments of this e closing
	 */
	@AutoEscape
	public String getIdComments();

	/**
	 * Sets the id comments of this e closing.
	 *
	 * @param idComments the id comments of this e closing
	 */
	public void setIdComments(String idComments);

	/**
	 * Returns the htd option1 of this e closing.
	 *
	 * @return the htd option1 of this e closing
	 */
	public boolean getHtdOption1();

	/**
	 * Returns <code>true</code> if this e closing is htd option1.
	 *
	 * @return <code>true</code> if this e closing is htd option1; <code>false</code> otherwise
	 */
	public boolean isHtdOption1();

	/**
	 * Sets whether this e closing is htd option1.
	 *
	 * @param htdOption1 the htd option1 of this e closing
	 */
	public void setHtdOption1(boolean htdOption1);

	/**
	 * Returns the htd hr fee of this e closing.
	 *
	 * @return the htd hr fee of this e closing
	 */
	public double getHtdHrFee();

	/**
	 * Sets the htd hr fee of this e closing.
	 *
	 * @param htdHrFee the htd hr fee of this e closing
	 */
	public void setHtdHrFee(double htdHrFee);

	/**
	 * Returns the htd finance fee of this e closing.
	 *
	 * @return the htd finance fee of this e closing
	 */
	public double getHtdFinanceFee();

	/**
	 * Sets the htd finance fee of this e closing.
	 *
	 * @param htdFinanceFee the htd finance fee of this e closing
	 */
	public void setHtdFinanceFee(double htdFinanceFee);

	/**
	 * Returns the htd status of this e closing.
	 *
	 * @return the htd status of this e closing
	 */
	@AutoEscape
	public String getHtdStatus();

	/**
	 * Sets the htd status of this e closing.
	 *
	 * @param htdStatus the htd status of this e closing
	 */
	public void setHtdStatus(String htdStatus);

	/**
	 * Returns the htd comments of this e closing.
	 *
	 * @return the htd comments of this e closing
	 */
	@AutoEscape
	public String getHtdComments();

	/**
	 * Sets the htd comments of this e closing.
	 *
	 * @param htdComments the htd comments of this e closing
	 */
	public void setHtdComments(String htdComments);

	/**
	 * Returns the hd option1 of this e closing.
	 *
	 * @return the hd option1 of this e closing
	 */
	public boolean getHdOption1();

	/**
	 * Returns <code>true</code> if this e closing is hd option1.
	 *
	 * @return <code>true</code> if this e closing is hd option1; <code>false</code> otherwise
	 */
	public boolean isHdOption1();

	/**
	 * Sets whether this e closing is hd option1.
	 *
	 * @param hdOption1 the hd option1 of this e closing
	 */
	public void setHdOption1(boolean hdOption1);

	/**
	 * Returns the hd option2 of this e closing.
	 *
	 * @return the hd option2 of this e closing
	 */
	public boolean getHdOption2();

	/**
	 * Returns <code>true</code> if this e closing is hd option2.
	 *
	 * @return <code>true</code> if this e closing is hd option2; <code>false</code> otherwise
	 */
	public boolean isHdOption2();

	/**
	 * Sets whether this e closing is hd option2.
	 *
	 * @param hdOption2 the hd option2 of this e closing
	 */
	public void setHdOption2(boolean hdOption2);

	/**
	 * Returns the hd option2 text of this e closing.
	 *
	 * @return the hd option2 text of this e closing
	 */
	@AutoEscape
	public String getHdOption2Text();

	/**
	 * Sets the hd option2 text of this e closing.
	 *
	 * @param hdOption2Text the hd option2 text of this e closing
	 */
	public void setHdOption2Text(String hdOption2Text);

	/**
	 * Returns the hd option3 of this e closing.
	 *
	 * @return the hd option3 of this e closing
	 */
	public boolean getHdOption3();

	/**
	 * Returns <code>true</code> if this e closing is hd option3.
	 *
	 * @return <code>true</code> if this e closing is hd option3; <code>false</code> otherwise
	 */
	public boolean isHdOption3();

	/**
	 * Sets whether this e closing is hd option3.
	 *
	 * @param hdOption3 the hd option3 of this e closing
	 */
	public void setHdOption3(boolean hdOption3);

	/**
	 * Returns the hd option3 money of this e closing.
	 *
	 * @return the hd option3 money of this e closing
	 */
	public double getHdOption3Money();

	/**
	 * Sets the hd option3 money of this e closing.
	 *
	 * @param hdOption3Money the hd option3 money of this e closing
	 */
	public void setHdOption3Money(double hdOption3Money);

	/**
	 * Returns the hd option4 of this e closing.
	 *
	 * @return the hd option4 of this e closing
	 */
	public boolean getHdOption4();

	/**
	 * Returns <code>true</code> if this e closing is hd option4.
	 *
	 * @return <code>true</code> if this e closing is hd option4; <code>false</code> otherwise
	 */
	public boolean isHdOption4();

	/**
	 * Sets whether this e closing is hd option4.
	 *
	 * @param hdOption4 the hd option4 of this e closing
	 */
	public void setHdOption4(boolean hdOption4);

	/**
	 * Returns the hd option4 money of this e closing.
	 *
	 * @return the hd option4 money of this e closing
	 */
	public double getHdOption4Money();

	/**
	 * Sets the hd option4 money of this e closing.
	 *
	 * @param hdOption4Money the hd option4 money of this e closing
	 */
	public void setHdOption4Money(double hdOption4Money);

	/**
	 * Returns the hd status of this e closing.
	 *
	 * @return the hd status of this e closing
	 */
	@AutoEscape
	public String getHdStatus();

	/**
	 * Sets the hd status of this e closing.
	 *
	 * @param hdStatus the hd status of this e closing
	 */
	public void setHdStatus(String hdStatus);

	/**
	 * Returns the hd comments of this e closing.
	 *
	 * @return the hd comments of this e closing
	 */
	@AutoEscape
	public String getHdComments();

	/**
	 * Sets the hd comments of this e closing.
	 *
	 * @param hdComments the hd comments of this e closing
	 */
	public void setHdComments(String hdComments);

	/**
	 * Returns the hdleave text of this e closing.
	 *
	 * @return the hdleave text of this e closing
	 */
	@AutoEscape
	public String getHdleaveText();

	/**
	 * Sets the hdleave text of this e closing.
	 *
	 * @param hdleaveText the hdleave text of this e closing
	 */
	public void setHdleaveText(String hdleaveText);

	/**
	 * Returns the fd option1 of this e closing.
	 *
	 * @return the fd option1 of this e closing
	 */
	public boolean getFdOption1();

	/**
	 * Returns <code>true</code> if this e closing is fd option1.
	 *
	 * @return <code>true</code> if this e closing is fd option1; <code>false</code> otherwise
	 */
	public boolean isFdOption1();

	/**
	 * Sets whether this e closing is fd option1.
	 *
	 * @param fdOption1 the fd option1 of this e closing
	 */
	public void setFdOption1(boolean fdOption1);

	/**
	 * Returns the fd option2 of this e closing.
	 *
	 * @return the fd option2 of this e closing
	 */
	public boolean getFdOption2();

	/**
	 * Returns <code>true</code> if this e closing is fd option2.
	 *
	 * @return <code>true</code> if this e closing is fd option2; <code>false</code> otherwise
	 */
	public boolean isFdOption2();

	/**
	 * Sets whether this e closing is fd option2.
	 *
	 * @param fdOption2 the fd option2 of this e closing
	 */
	public void setFdOption2(boolean fdOption2);

	/**
	 * Returns the fd option3 of this e closing.
	 *
	 * @return the fd option3 of this e closing
	 */
	public boolean getFdOption3();

	/**
	 * Returns <code>true</code> if this e closing is fd option3.
	 *
	 * @return <code>true</code> if this e closing is fd option3; <code>false</code> otherwise
	 */
	public boolean isFdOption3();

	/**
	 * Sets whether this e closing is fd option3.
	 *
	 * @param fdOption3 the fd option3 of this e closing
	 */
	public void setFdOption3(boolean fdOption3);

	/**
	 * Returns the fd option4 of this e closing.
	 *
	 * @return the fd option4 of this e closing
	 */
	public boolean getFdOption4();

	/**
	 * Returns <code>true</code> if this e closing is fd option4.
	 *
	 * @return <code>true</code> if this e closing is fd option4; <code>false</code> otherwise
	 */
	public boolean isFdOption4();

	/**
	 * Sets whether this e closing is fd option4.
	 *
	 * @param fdOption4 the fd option4 of this e closing
	 */
	public void setFdOption4(boolean fdOption4);

	/**
	 * Returns the fd option4 text of this e closing.
	 *
	 * @return the fd option4 text of this e closing
	 */
	@AutoEscape
	public String getFdOption4Text();

	/**
	 * Sets the fd option4 text of this e closing.
	 *
	 * @param fdOption4Text the fd option4 text of this e closing
	 */
	public void setFdOption4Text(String fdOption4Text);

	/**
	 * Returns the fd status of this e closing.
	 *
	 * @return the fd status of this e closing
	 */
	@AutoEscape
	public String getFdStatus();

	/**
	 * Sets the fd status of this e closing.
	 *
	 * @param fdStatus the fd status of this e closing
	 */
	public void setFdStatus(String fdStatus);

	/**
	 * Returns the fd comments of this e closing.
	 *
	 * @return the fd comments of this e closing
	 */
	@AutoEscape
	public String getFdComments();

	/**
	 * Sets the fd comments of this e closing.
	 *
	 * @param fdComments the fd comments of this e closing
	 */
	public void setFdComments(String fdComments);

	/**
	 * Returns the applicant agent of this e closing.
	 *
	 * @return the applicant agent of this e closing
	 */
	public boolean getApplicantAgent();

	/**
	 * Returns <code>true</code> if this e closing is applicant agent.
	 *
	 * @return <code>true</code> if this e closing is applicant agent; <code>false</code> otherwise
	 */
	public boolean isApplicantAgent();

	/**
	 * Sets whether this e closing is applicant agent.
	 *
	 * @param applicantAgent the applicant agent of this e closing
	 */
	public void setApplicantAgent(boolean applicantAgent);

	/**
	 * Returns the approver agent of this e closing.
	 *
	 * @return the approver agent of this e closing
	 */
	public boolean getApproverAgent();

	/**
	 * Returns <code>true</code> if this e closing is approver agent.
	 *
	 * @return <code>true</code> if this e closing is approver agent; <code>false</code> otherwise
	 */
	public boolean isApproverAgent();

	/**
	 * Sets whether this e closing is approver agent.
	 *
	 * @param approverAgent the approver agent of this e closing
	 */
	public void setApproverAgent(boolean approverAgent);

	/**
	 * Returns the process type of this e closing.
	 *
	 * @return the process type of this e closing
	 */
	@AutoEscape
	public String getProcessType();

	/**
	 * Sets the process type of this e closing.
	 *
	 * @param processType the process type of this e closing
	 */
	public void setProcessType(String processType);

	/**
	 * Returns the sub process type of this e closing.
	 *
	 * @return the sub process type of this e closing
	 */
	@AutoEscape
	public String getSubProcessType();

	/**
	 * Sets the sub process type of this e closing.
	 *
	 * @param subProcessType the sub process type of this e closing
	 */
	public void setSubProcessType(String subProcessType);

	/**
	 * Returns the status of this e closing.
	 *
	 * @return the status of this e closing
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this e closing.
	 *
	 * @param status the status of this e closing
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this e closing.
	 *
	 * @return the status by user ID of this e closing
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this e closing.
	 *
	 * @param statusByUserId the status by user ID of this e closing
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this e closing.
	 *
	 * @return the status by user uuid of this e closing
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getStatusByUserUuid() throws SystemException;

	/**
	 * Sets the status by user uuid of this e closing.
	 *
	 * @param statusByUserUuid the status by user uuid of this e closing
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this e closing.
	 *
	 * @return the status by user name of this e closing
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this e closing.
	 *
	 * @param statusByUserName the status by user name of this e closing
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this e closing.
	 *
	 * @return the status date of this e closing
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this e closing.
	 *
	 * @param statusDate the status date of this e closing
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * @deprecated As of 6.1.0, replaced by {@link #isApproved()}
	 */
	@Override
	public boolean getApproved();

	/**
	 * Returns <code>true</code> if this e closing is approved.
	 *
	 * @return <code>true</code> if this e closing is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this e closing is denied.
	 *
	 * @return <code>true</code> if this e closing is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this e closing is a draft.
	 *
	 * @return <code>true</code> if this e closing is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this e closing is expired.
	 *
	 * @return <code>true</code> if this e closing is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this e closing is inactive.
	 *
	 * @return <code>true</code> if this e closing is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this e closing is incomplete.
	 *
	 * @return <code>true</code> if this e closing is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this e closing is pending.
	 *
	 * @return <code>true</code> if this e closing is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this e closing is scheduled.
	 *
	 * @return <code>true</code> if this e closing is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.e.closing.model.EClosing eClosing);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.e.closing.model.EClosing> toCacheModel();

	@Override
	public com.e.closing.model.EClosing toEscapedModel();

	@Override
	public com.e.closing.model.EClosing toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}