/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.company.car.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CompanyCarManagement service. Represents a row in the &quot;vgcapon_CompanyCarManagement&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.company.car.model.impl.CompanyCarManagementModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.company.car.model.impl.CompanyCarManagementImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CompanyCarManagement
 * @see com.company.car.model.impl.CompanyCarManagementImpl
 * @see com.company.car.model.impl.CompanyCarManagementModelImpl
 * @generated
 */
public interface CompanyCarManagementModel extends BaseModel<CompanyCarManagement> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a company car management model instance should use the {@link CompanyCarManagement} interface instead.
	 */

	/**
	 * Returns the primary key of this company car management.
	 *
	 * @return the primary key of this company car management
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this company car management.
	 *
	 * @param primaryKey the primary key of this company car management
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the company car management ID of this company car management.
	 *
	 * @return the company car management ID of this company car management
	 */
	public long getCompanyCarManagementId();

	/**
	 * Sets the company car management ID of this company car management.
	 *
	 * @param companyCarManagementId the company car management ID of this company car management
	 */
	public void setCompanyCarManagementId(long companyCarManagementId);

	/**
	 * Returns the create date of this company car management.
	 *
	 * @return the create date of this company car management
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this company car management.
	 *
	 * @param createDate the create date of this company car management
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this company car management.
	 *
	 * @return the modified date of this company car management
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this company car management.
	 *
	 * @param modifiedDate the modified date of this company car management
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the car no of this company car management.
	 *
	 * @return the car no of this company car management
	 */
	@AutoEscape
	public String getCarNo();

	/**
	 * Sets the car no of this company car management.
	 *
	 * @param carNo the car no of this company car management
	 */
	public void setCarNo(String carNo);

	/**
	 * Returns the car type of this company car management.
	 *
	 * @return the car type of this company car management
	 */
	@AutoEscape
	public String getCarType();

	/**
	 * Sets the car type of this company car management.
	 *
	 * @param carType the car type of this company car management
	 */
	public void setCarType(String carType);

	/**
	 * Returns the contract type of this company car management.
	 *
	 * @return the contract type of this company car management
	 */
	@AutoEscape
	public String getContractType();

	/**
	 * Sets the contract type of this company car management.
	 *
	 * @param contractType the contract type of this company car management
	 */
	public void setContractType(String contractType);

	/**
	 * Returns the grade type of this company car management.
	 *
	 * @return the grade type of this company car management
	 */
	@AutoEscape
	public String getGradeType();

	/**
	 * Sets the grade type of this company car management.
	 *
	 * @param gradeType the grade type of this company car management
	 */
	public void setGradeType(String gradeType);

	/**
	 * Returns the grade of this company car management.
	 *
	 * @return the grade of this company car management
	 */
	@AutoEscape
	public String getGrade();

	/**
	 * Sets the grade of this company car management.
	 *
	 * @param grade the grade of this company car management
	 */
	public void setGrade(String grade);

	/**
	 * Returns the car brand of this company car management.
	 *
	 * @return the car brand of this company car management
	 */
	@AutoEscape
	public String getCarBrand();

	/**
	 * Sets the car brand of this company car management.
	 *
	 * @param carBrand the car brand of this company car management
	 */
	public void setCarBrand(String carBrand);

	/**
	 * Returns the car model of this company car management.
	 *
	 * @return the car model of this company car management
	 */
	@AutoEscape
	public String getCarModel();

	/**
	 * Sets the car model of this company car management.
	 *
	 * @param carModel the car model of this company car management
	 */
	public void setCarModel(String carModel);

	/**
	 * Returns the car category of this company car management.
	 *
	 * @return the car category of this company car management
	 */
	@AutoEscape
	public String getCarCategory();

	/**
	 * Sets the car category of this company car management.
	 *
	 * @param carCategory the car category of this company car management
	 */
	public void setCarCategory(String carCategory);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.company.car.model.CompanyCarManagement companyCarManagement);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.company.car.model.CompanyCarManagement> toCacheModel();

	@Override
	public com.company.car.model.CompanyCarManagement toEscapedModel();

	@Override
	public com.company.car.model.CompanyCarManagement toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}