/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.company.car.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.model.WorkflowedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SecondCompanyCar service. Represents a row in the &quot;vgcapon_SecondCompanyCar&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.company.car.model.impl.SecondCompanyCarModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.company.car.model.impl.SecondCompanyCarImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SecondCompanyCar
 * @see com.company.car.model.impl.SecondCompanyCarImpl
 * @see com.company.car.model.impl.SecondCompanyCarModelImpl
 * @generated
 */
public interface SecondCompanyCarModel extends BaseModel<SecondCompanyCar>,
	GroupedModel, WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a second company car model instance should use the {@link SecondCompanyCar} interface instead.
	 */

	/**
	 * Returns the primary key of this second company car.
	 *
	 * @return the primary key of this second company car
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this second company car.
	 *
	 * @param primaryKey the primary key of this second company car
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the second company car ID of this second company car.
	 *
	 * @return the second company car ID of this second company car
	 */
	public long getSecondCompanyCarId();

	/**
	 * Sets the second company car ID of this second company car.
	 *
	 * @param secondCompanyCarId the second company car ID of this second company car
	 */
	public void setSecondCompanyCarId(long secondCompanyCarId);

	/**
	 * Returns the ticket no of this second company car.
	 *
	 * @return the ticket no of this second company car
	 */
	@AutoEscape
	public String getTicketNo();

	/**
	 * Sets the ticket no of this second company car.
	 *
	 * @param ticketNo the ticket no of this second company car
	 */
	public void setTicketNo(String ticketNo);

	/**
	 * Returns the group ID of this second company car.
	 *
	 * @return the group ID of this second company car
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this second company car.
	 *
	 * @param groupId the group ID of this second company car
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this second company car.
	 *
	 * @return the user ID of this second company car
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this second company car.
	 *
	 * @param userId the user ID of this second company car
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this second company car.
	 *
	 * @return the user uuid of this second company car
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this second company car.
	 *
	 * @param userUuid the user uuid of this second company car
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this second company car.
	 *
	 * @return the user name of this second company car
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this second company car.
	 *
	 * @param userName the user name of this second company car
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this second company car.
	 *
	 * @return the create date of this second company car
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this second company car.
	 *
	 * @param createDate the create date of this second company car
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this second company car.
	 *
	 * @return the modified date of this second company car
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this second company car.
	 *
	 * @param modifiedDate the modified date of this second company car
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the submitted date of this second company car.
	 *
	 * @return the submitted date of this second company car
	 */
	public Date getSubmittedDate();

	/**
	 * Sets the submitted date of this second company car.
	 *
	 * @param submittedDate the submitted date of this second company car
	 */
	public void setSubmittedDate(Date submittedDate);

	/**
	 * Returns the company ID of this second company car.
	 *
	 * @return the company ID of this second company car
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this second company car.
	 *
	 * @param companyId the company ID of this second company car
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the name of this second company car.
	 *
	 * @return the name of this second company car
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this second company car.
	 *
	 * @param name the name of this second company car
	 */
	public void setName(String name);

	/**
	 * Returns the staff code of this second company car.
	 *
	 * @return the staff code of this second company car
	 */
	public long getStaffCode();

	/**
	 * Sets the staff code of this second company car.
	 *
	 * @param staffCode the staff code of this second company car
	 */
	public void setStaffCode(long staffCode);

	/**
	 * Returns the division of this second company car.
	 *
	 * @return the division of this second company car
	 */
	@AutoEscape
	public String getDivision();

	/**
	 * Sets the division of this second company car.
	 *
	 * @param division the division of this second company car
	 */
	public void setDivision(String division);

	/**
	 * Returns the department of this second company car.
	 *
	 * @return the department of this second company car
	 */
	@AutoEscape
	public String getDepartment();

	/**
	 * Sets the department of this second company car.
	 *
	 * @param department the department of this second company car
	 */
	public void setDepartment(String department);

	/**
	 * Returns the status of this second company car.
	 *
	 * @return the status of this second company car
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this second company car.
	 *
	 * @param status the status of this second company car
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this second company car.
	 *
	 * @return the status by user ID of this second company car
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this second company car.
	 *
	 * @param statusByUserId the status by user ID of this second company car
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this second company car.
	 *
	 * @return the status by user uuid of this second company car
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getStatusByUserUuid() throws SystemException;

	/**
	 * Sets the status by user uuid of this second company car.
	 *
	 * @param statusByUserUuid the status by user uuid of this second company car
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this second company car.
	 *
	 * @return the status by user name of this second company car
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this second company car.
	 *
	 * @param statusByUserName the status by user name of this second company car
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the company name of this second company car.
	 *
	 * @return the company name of this second company car
	 */
	@AutoEscape
	public String getCompanyName();

	/**
	 * Sets the company name of this second company car.
	 *
	 * @param companyName the company name of this second company car
	 */
	public void setCompanyName(String companyName);

	/**
	 * Returns the status date of this second company car.
	 *
	 * @return the status date of this second company car
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this second company car.
	 *
	 * @param statusDate the status date of this second company car
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the contact no of this second company car.
	 *
	 * @return the contact no of this second company car
	 */
	@AutoEscape
	public String getContactNo();

	/**
	 * Sets the contact no of this second company car.
	 *
	 * @param contactNo the contact no of this second company car
	 */
	public void setContactNo(String contactNo);

	/**
	 * Returns the working location of this second company car.
	 *
	 * @return the working location of this second company car
	 */
	@AutoEscape
	public String getWorkingLocation();

	/**
	 * Sets the working location of this second company car.
	 *
	 * @param workingLocation the working location of this second company car
	 */
	public void setWorkingLocation(String workingLocation);

	/**
	 * Returns the office site of this second company car.
	 *
	 * @return the office site of this second company car
	 */
	@AutoEscape
	public String getOfficeSite();

	/**
	 * Sets the office site of this second company car.
	 *
	 * @param officeSite the office site of this second company car
	 */
	public void setOfficeSite(String officeSite);

	/**
	 * Returns the current car model of this second company car.
	 *
	 * @return the current car model of this second company car
	 */
	@AutoEscape
	public String getCurrentCarModel();

	/**
	 * Sets the current car model of this second company car.
	 *
	 * @param currentCarModel the current car model of this second company car
	 */
	public void setCurrentCarModel(String currentCarModel);

	/**
	 * Returns the current car color of this second company car.
	 *
	 * @return the current car color of this second company car
	 */
	@AutoEscape
	public String getCurrentCarColor();

	/**
	 * Sets the current car color of this second company car.
	 *
	 * @param currentCarColor the current car color of this second company car
	 */
	public void setCurrentCarColor(String currentCarColor);

	/**
	 * Returns the current plate number of this second company car.
	 *
	 * @return the current plate number of this second company car
	 */
	@AutoEscape
	public String getCurrentPlateNumber();

	/**
	 * Sets the current plate number of this second company car.
	 *
	 * @param currentPlateNumber the current plate number of this second company car
	 */
	public void setCurrentPlateNumber(String currentPlateNumber);

	/**
	 * Returns the acquiring date of this second company car.
	 *
	 * @return the acquiring date of this second company car
	 */
	public Date getAcquiringDate();

	/**
	 * Sets the acquiring date of this second company car.
	 *
	 * @param acquiringDate the acquiring date of this second company car
	 */
	public void setAcquiringDate(Date acquiringDate);

	/**
	 * Returns the expected car model of this second company car.
	 *
	 * @return the expected car model of this second company car
	 */
	@AutoEscape
	public String getExpectedCarModel();

	/**
	 * Sets the expected car model of this second company car.
	 *
	 * @param expectedCarModel the expected car model of this second company car
	 */
	public void setExpectedCarModel(String expectedCarModel);

	/**
	 * Returns the expected car color of this second company car.
	 *
	 * @return the expected car color of this second company car
	 */
	@AutoEscape
	public String getExpectedCarColor();

	/**
	 * Sets the expected car color of this second company car.
	 *
	 * @param expectedCarColor the expected car color of this second company car
	 */
	public void setExpectedCarColor(String expectedCarColor);

	/**
	 * Returns the expected last plate number of this second company car.
	 *
	 * @return the expected last plate number of this second company car
	 */
	@AutoEscape
	public String getExpectedLastPlateNumber();

	/**
	 * Sets the expected last plate number of this second company car.
	 *
	 * @param expectedLastPlateNumber the expected last plate number of this second company car
	 */
	public void setExpectedLastPlateNumber(String expectedLastPlateNumber);

	/**
	 * Returns the position cost center ID of this second company car.
	 *
	 * @return the position cost center ID of this second company car
	 */
	@AutoEscape
	public String getPositionCostCenterId();

	/**
	 * Sets the position cost center ID of this second company car.
	 *
	 * @param positionCostCenterId the position cost center ID of this second company car
	 */
	public void setPositionCostCenterId(String positionCostCenterId);

	/**
	 * Returns the employee group ID of this second company car.
	 *
	 * @return the employee group ID of this second company car
	 */
	@AutoEscape
	public String getEmployeeGroupId();

	/**
	 * Sets the employee group ID of this second company car.
	 *
	 * @param employeeGroupId the employee group ID of this second company car
	 */
	public void setEmployeeGroupId(String employeeGroupId);

	/**
	 * Returns the contract end date of this second company car.
	 *
	 * @return the contract end date of this second company car
	 */
	public Date getContractEndDate();

	/**
	 * Sets the contract end date of this second company car.
	 *
	 * @param contractEndDate the contract end date of this second company car
	 */
	public void setContractEndDate(Date contractEndDate);

	/**
	 * Returns the mobile phone of this second company car.
	 *
	 * @return the mobile phone of this second company car
	 */
	@AutoEscape
	public String getMobilePhone();

	/**
	 * Sets the mobile phone of this second company car.
	 *
	 * @param mobilePhone the mobile phone of this second company car
	 */
	public void setMobilePhone(String mobilePhone);

	/**
	 * Returns the office phone of this second company car.
	 *
	 * @return the office phone of this second company car
	 */
	@AutoEscape
	public String getOfficePhone();

	/**
	 * Sets the office phone of this second company car.
	 *
	 * @param officePhone the office phone of this second company car
	 */
	public void setOfficePhone(String officePhone);

	/**
	 * Returns the email of this second company car.
	 *
	 * @return the email of this second company car
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this second company car.
	 *
	 * @param email the email of this second company car
	 */
	public void setEmail(String email);

	/**
	 * Returns the is applicant agent of this second company car.
	 *
	 * @return the is applicant agent of this second company car
	 */
	public boolean getIsApplicantAgent();

	/**
	 * Returns <code>true</code> if this second company car is is applicant agent.
	 *
	 * @return <code>true</code> if this second company car is is applicant agent; <code>false</code> otherwise
	 */
	public boolean isIsApplicantAgent();

	/**
	 * Sets whether this second company car is is applicant agent.
	 *
	 * @param isApplicantAgent the is applicant agent of this second company car
	 */
	public void setIsApplicantAgent(boolean isApplicantAgent);

	/**
	 * Returns the is approver agent of this second company car.
	 *
	 * @return the is approver agent of this second company car
	 */
	public boolean getIsApproverAgent();

	/**
	 * Returns <code>true</code> if this second company car is is approver agent.
	 *
	 * @return <code>true</code> if this second company car is is approver agent; <code>false</code> otherwise
	 */
	public boolean isIsApproverAgent();

	/**
	 * Sets whether this second company car is is approver agent.
	 *
	 * @param isApproverAgent the is approver agent of this second company car
	 */
	public void setIsApproverAgent(boolean isApproverAgent);

	/**
	 * Returns the driving license information of this second company car.
	 *
	 * @return the driving license information of this second company car
	 */
	public int getDrivingLicenseInformation();

	/**
	 * Sets the driving license information of this second company car.
	 *
	 * @param drivingLicenseInformation the driving license information of this second company car
	 */
	public void setDrivingLicenseInformation(int drivingLicenseInformation);

	/**
	 * Returns the estimated obtaining date of this second company car.
	 *
	 * @return the estimated obtaining date of this second company car
	 */
	public Date getEstimatedObtainingDate();

	/**
	 * Sets the estimated obtaining date of this second company car.
	 *
	 * @param estimatedObtainingDate the estimated obtaining date of this second company car
	 */
	public void setEstimatedObtainingDate(Date estimatedObtainingDate);

	/**
	 * Returns the comments of this second company car.
	 *
	 * @return the comments of this second company car
	 */
	@AutoEscape
	public String getComments();

	/**
	 * Sets the comments of this second company car.
	 *
	 * @param comments the comments of this second company car
	 */
	public void setComments(String comments);

	/**
	 * Returns the process type of this second company car.
	 *
	 * @return the process type of this second company car
	 */
	@AutoEscape
	public String getProcessType();

	/**
	 * Sets the process type of this second company car.
	 *
	 * @param processType the process type of this second company car
	 */
	public void setProcessType(String processType);

	/**
	 * Returns the sub type of this second company car.
	 *
	 * @return the sub type of this second company car
	 */
	@AutoEscape
	public String getSubType();

	/**
	 * Sets the sub type of this second company car.
	 *
	 * @param subType the sub type of this second company car
	 */
	public void setSubType(String subType);

	/**
	 * @deprecated As of 6.1.0, replaced by {@link #isApproved()}
	 */
	@Override
	public boolean getApproved();

	/**
	 * Returns <code>true</code> if this second company car is approved.
	 *
	 * @return <code>true</code> if this second company car is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this second company car is denied.
	 *
	 * @return <code>true</code> if this second company car is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this second company car is a draft.
	 *
	 * @return <code>true</code> if this second company car is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this second company car is expired.
	 *
	 * @return <code>true</code> if this second company car is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this second company car is inactive.
	 *
	 * @return <code>true</code> if this second company car is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this second company car is incomplete.
	 *
	 * @return <code>true</code> if this second company car is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this second company car is pending.
	 *
	 * @return <code>true</code> if this second company car is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this second company car is scheduled.
	 *
	 * @return <code>true</code> if this second company car is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.company.car.model.SecondCompanyCar secondCompanyCar);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.company.car.model.SecondCompanyCar> toCacheModel();

	@Override
	public com.company.car.model.SecondCompanyCar toEscapedModel();

	@Override
	public com.company.car.model.SecondCompanyCar toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}