/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.e.closing.service.base;

import com.e.closing.model.EClosing;
import com.e.closing.service.EClosingService;
import com.e.closing.service.persistence.EClosingFinder;
import com.e.closing.service.persistence.EClosingPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the e closing remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.e.closing.service.impl.EClosingServiceImpl}.
 * </p>
 *
 * @author t.a.jiang
 * @see com.e.closing.service.impl.EClosingServiceImpl
 * @see com.e.closing.service.EClosingServiceUtil
 * @generated
 */
public abstract class EClosingServiceBaseImpl extends BaseServiceImpl
	implements EClosingService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.e.closing.service.EClosingServiceUtil} to access the e closing remote service.
	 */

	/**
	 * Returns the e closing local service.
	 *
	 * @return the e closing local service
	 */
	public com.e.closing.service.EClosingLocalService getEClosingLocalService() {
		return eClosingLocalService;
	}

	/**
	 * Sets the e closing local service.
	 *
	 * @param eClosingLocalService the e closing local service
	 */
	public void setEClosingLocalService(
		com.e.closing.service.EClosingLocalService eClosingLocalService) {
		this.eClosingLocalService = eClosingLocalService;
	}

	/**
	 * Returns the e closing remote service.
	 *
	 * @return the e closing remote service
	 */
	public com.e.closing.service.EClosingService getEClosingService() {
		return eClosingService;
	}

	/**
	 * Sets the e closing remote service.
	 *
	 * @param eClosingService the e closing remote service
	 */
	public void setEClosingService(
		com.e.closing.service.EClosingService eClosingService) {
		this.eClosingService = eClosingService;
	}

	/**
	 * Returns the e closing persistence.
	 *
	 * @return the e closing persistence
	 */
	public EClosingPersistence getEClosingPersistence() {
		return eClosingPersistence;
	}

	/**
	 * Sets the e closing persistence.
	 *
	 * @param eClosingPersistence the e closing persistence
	 */
	public void setEClosingPersistence(EClosingPersistence eClosingPersistence) {
		this.eClosingPersistence = eClosingPersistence;
	}

	/**
	 * Returns the e closing finder.
	 *
	 * @return the e closing finder
	 */
	public EClosingFinder getEClosingFinder() {
		return eClosingFinder;
	}

	/**
	 * Sets the e closing finder.
	 *
	 * @param eClosingFinder the e closing finder
	 */
	public void setEClosingFinder(EClosingFinder eClosingFinder) {
		this.eClosingFinder = eClosingFinder;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return EClosing.class;
	}

	protected String getModelClassName() {
		return EClosing.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = eClosingPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.e.closing.service.EClosingLocalService.class)
	protected com.e.closing.service.EClosingLocalService eClosingLocalService;
	@BeanReference(type = com.e.closing.service.EClosingService.class)
	protected com.e.closing.service.EClosingService eClosingService;
	@BeanReference(type = EClosingPersistence.class)
	protected EClosingPersistence eClosingPersistence;
	@BeanReference(type = EClosingFinder.class)
	protected EClosingFinder eClosingFinder;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private EClosingServiceClpInvoker _clpInvoker = new EClosingServiceClpInvoker();
}