/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.business.trip.model.impl;

import com.business.trip.model.BtReimbursementSAPInfo;
import com.business.trip.model.BtReimbursementSAPInfoModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the BtReimbursementSAPInfo service. Represents a row in the &quot;vgcapon_BtReimbursementSAPInfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.business.trip.model.BtReimbursementSAPInfoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BtReimbursementSAPInfoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BtReimbursementSAPInfoImpl
 * @see com.business.trip.model.BtReimbursementSAPInfo
 * @see com.business.trip.model.BtReimbursementSAPInfoModel
 * @generated
 */
public class BtReimbursementSAPInfoModelImpl extends BaseModelImpl<BtReimbursementSAPInfo>
	implements BtReimbursementSAPInfoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a bt reimbursement s a p info model instance should use the {@link com.business.trip.model.BtReimbursementSAPInfo} interface instead.
	 */
	public static final String TABLE_NAME = "vgcapon_BtReimbursementSAPInfo";
	public static final Object[][] TABLE_COLUMNS = {
			{ "btReimbursementSAPInfoId", Types.BIGINT },
			{ "businessTripPkId", Types.BIGINT },
			{ "ticketNo", Types.VARCHAR },
			{ "currency_", Types.VARCHAR },
			{ "step", Types.INTEGER },
			{ "messageType", Types.VARCHAR },
			{ "message", Types.VARCHAR },
			{ "certificateNo", Types.VARCHAR },
			{ "company", Types.VARCHAR },
			{ "year", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table vgcapon_BtReimbursementSAPInfo (btReimbursementSAPInfoId LONG not null primary key,businessTripPkId LONG,ticketNo VARCHAR(75) null,currency_ VARCHAR(75) null,step INTEGER,messageType VARCHAR(75) null,message VARCHAR(1024) null,certificateNo VARCHAR(75) null,company VARCHAR(75) null,year VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table vgcapon_BtReimbursementSAPInfo";
	public static final String ORDER_BY_JPQL = " ORDER BY btReimbursementSAPInfo.btReimbursementSAPInfoId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY vgcapon_BtReimbursementSAPInfo.btReimbursementSAPInfoId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.business.trip.model.BtReimbursementSAPInfo"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.business.trip.model.BtReimbursementSAPInfo"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.business.trip.model.BtReimbursementSAPInfo"),
			true);
	public static long BUSINESSTRIPPKID_COLUMN_BITMASK = 1L;
	public static long CURRENCY_COLUMN_BITMASK = 2L;
	public static long BTREIMBURSEMENTSAPINFOID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.business.trip.model.BtReimbursementSAPInfo"));

	public BtReimbursementSAPInfoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _btReimbursementSAPInfoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBtReimbursementSAPInfoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _btReimbursementSAPInfoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return BtReimbursementSAPInfo.class;
	}

	@Override
	public String getModelClassName() {
		return BtReimbursementSAPInfo.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("btReimbursementSAPInfoId", getBtReimbursementSAPInfoId());
		attributes.put("businessTripPkId", getBusinessTripPkId());
		attributes.put("ticketNo", getTicketNo());
		attributes.put("currency", getCurrency());
		attributes.put("step", getStep());
		attributes.put("messageType", getMessageType());
		attributes.put("message", getMessage());
		attributes.put("certificateNo", getCertificateNo());
		attributes.put("company", getCompany());
		attributes.put("year", getYear());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long btReimbursementSAPInfoId = (Long)attributes.get(
				"btReimbursementSAPInfoId");

		if (btReimbursementSAPInfoId != null) {
			setBtReimbursementSAPInfoId(btReimbursementSAPInfoId);
		}

		Long businessTripPkId = (Long)attributes.get("businessTripPkId");

		if (businessTripPkId != null) {
			setBusinessTripPkId(businessTripPkId);
		}

		String ticketNo = (String)attributes.get("ticketNo");

		if (ticketNo != null) {
			setTicketNo(ticketNo);
		}

		String currency = (String)attributes.get("currency");

		if (currency != null) {
			setCurrency(currency);
		}

		Integer step = (Integer)attributes.get("step");

		if (step != null) {
			setStep(step);
		}

		String messageType = (String)attributes.get("messageType");

		if (messageType != null) {
			setMessageType(messageType);
		}

		String message = (String)attributes.get("message");

		if (message != null) {
			setMessage(message);
		}

		String certificateNo = (String)attributes.get("certificateNo");

		if (certificateNo != null) {
			setCertificateNo(certificateNo);
		}

		String company = (String)attributes.get("company");

		if (company != null) {
			setCompany(company);
		}

		String year = (String)attributes.get("year");

		if (year != null) {
			setYear(year);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}
	}

	@Override
	public long getBtReimbursementSAPInfoId() {
		return _btReimbursementSAPInfoId;
	}

	@Override
	public void setBtReimbursementSAPInfoId(long btReimbursementSAPInfoId) {
		_btReimbursementSAPInfoId = btReimbursementSAPInfoId;
	}

	@Override
	public long getBusinessTripPkId() {
		return _businessTripPkId;
	}

	@Override
	public void setBusinessTripPkId(long businessTripPkId) {
		_columnBitmask |= BUSINESSTRIPPKID_COLUMN_BITMASK;

		if (!_setOriginalBusinessTripPkId) {
			_setOriginalBusinessTripPkId = true;

			_originalBusinessTripPkId = _businessTripPkId;
		}

		_businessTripPkId = businessTripPkId;
	}

	public long getOriginalBusinessTripPkId() {
		return _originalBusinessTripPkId;
	}

	@Override
	public String getTicketNo() {
		if (_ticketNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _ticketNo;
		}
	}

	@Override
	public void setTicketNo(String ticketNo) {
		_ticketNo = ticketNo;
	}

	@Override
	public String getCurrency() {
		if (_currency == null) {
			return StringPool.BLANK;
		}
		else {
			return _currency;
		}
	}

	@Override
	public void setCurrency(String currency) {
		_columnBitmask |= CURRENCY_COLUMN_BITMASK;

		if (_originalCurrency == null) {
			_originalCurrency = _currency;
		}

		_currency = currency;
	}

	public String getOriginalCurrency() {
		return GetterUtil.getString(_originalCurrency);
	}

	@Override
	public int getStep() {
		return _step;
	}

	@Override
	public void setStep(int step) {
		_step = step;
	}

	@Override
	public String getMessageType() {
		if (_messageType == null) {
			return StringPool.BLANK;
		}
		else {
			return _messageType;
		}
	}

	@Override
	public void setMessageType(String messageType) {
		_messageType = messageType;
	}

	@Override
	public String getMessage() {
		if (_message == null) {
			return StringPool.BLANK;
		}
		else {
			return _message;
		}
	}

	@Override
	public void setMessage(String message) {
		_message = message;
	}

	@Override
	public String getCertificateNo() {
		if (_certificateNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _certificateNo;
		}
	}

	@Override
	public void setCertificateNo(String certificateNo) {
		_certificateNo = certificateNo;
	}

	@Override
	public String getCompany() {
		if (_company == null) {
			return StringPool.BLANK;
		}
		else {
			return _company;
		}
	}

	@Override
	public void setCompany(String company) {
		_company = company;
	}

	@Override
	public String getYear() {
		if (_year == null) {
			return StringPool.BLANK;
		}
		else {
			return _year;
		}
	}

	@Override
	public void setYear(String year) {
		_year = year;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			BtReimbursementSAPInfo.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public BtReimbursementSAPInfo toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (BtReimbursementSAPInfo)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BtReimbursementSAPInfoImpl btReimbursementSAPInfoImpl = new BtReimbursementSAPInfoImpl();

		btReimbursementSAPInfoImpl.setBtReimbursementSAPInfoId(getBtReimbursementSAPInfoId());
		btReimbursementSAPInfoImpl.setBusinessTripPkId(getBusinessTripPkId());
		btReimbursementSAPInfoImpl.setTicketNo(getTicketNo());
		btReimbursementSAPInfoImpl.setCurrency(getCurrency());
		btReimbursementSAPInfoImpl.setStep(getStep());
		btReimbursementSAPInfoImpl.setMessageType(getMessageType());
		btReimbursementSAPInfoImpl.setMessage(getMessage());
		btReimbursementSAPInfoImpl.setCertificateNo(getCertificateNo());
		btReimbursementSAPInfoImpl.setCompany(getCompany());
		btReimbursementSAPInfoImpl.setYear(getYear());
		btReimbursementSAPInfoImpl.setCreateDate(getCreateDate());
		btReimbursementSAPInfoImpl.setModifiedDate(getModifiedDate());

		btReimbursementSAPInfoImpl.resetOriginalValues();

		return btReimbursementSAPInfoImpl;
	}

	@Override
	public int compareTo(BtReimbursementSAPInfo btReimbursementSAPInfo) {
		long primaryKey = btReimbursementSAPInfo.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof BtReimbursementSAPInfo)) {
			return false;
		}

		BtReimbursementSAPInfo btReimbursementSAPInfo = (BtReimbursementSAPInfo)obj;

		long primaryKey = btReimbursementSAPInfo.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		BtReimbursementSAPInfoModelImpl btReimbursementSAPInfoModelImpl = this;

		btReimbursementSAPInfoModelImpl._originalBusinessTripPkId = btReimbursementSAPInfoModelImpl._businessTripPkId;

		btReimbursementSAPInfoModelImpl._setOriginalBusinessTripPkId = false;

		btReimbursementSAPInfoModelImpl._originalCurrency = btReimbursementSAPInfoModelImpl._currency;

		btReimbursementSAPInfoModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<BtReimbursementSAPInfo> toCacheModel() {
		BtReimbursementSAPInfoCacheModel btReimbursementSAPInfoCacheModel = new BtReimbursementSAPInfoCacheModel();

		btReimbursementSAPInfoCacheModel.btReimbursementSAPInfoId = getBtReimbursementSAPInfoId();

		btReimbursementSAPInfoCacheModel.businessTripPkId = getBusinessTripPkId();

		btReimbursementSAPInfoCacheModel.ticketNo = getTicketNo();

		String ticketNo = btReimbursementSAPInfoCacheModel.ticketNo;

		if ((ticketNo != null) && (ticketNo.length() == 0)) {
			btReimbursementSAPInfoCacheModel.ticketNo = null;
		}

		btReimbursementSAPInfoCacheModel.currency = getCurrency();

		String currency = btReimbursementSAPInfoCacheModel.currency;

		if ((currency != null) && (currency.length() == 0)) {
			btReimbursementSAPInfoCacheModel.currency = null;
		}

		btReimbursementSAPInfoCacheModel.step = getStep();

		btReimbursementSAPInfoCacheModel.messageType = getMessageType();

		String messageType = btReimbursementSAPInfoCacheModel.messageType;

		if ((messageType != null) && (messageType.length() == 0)) {
			btReimbursementSAPInfoCacheModel.messageType = null;
		}

		btReimbursementSAPInfoCacheModel.message = getMessage();

		String message = btReimbursementSAPInfoCacheModel.message;

		if ((message != null) && (message.length() == 0)) {
			btReimbursementSAPInfoCacheModel.message = null;
		}

		btReimbursementSAPInfoCacheModel.certificateNo = getCertificateNo();

		String certificateNo = btReimbursementSAPInfoCacheModel.certificateNo;

		if ((certificateNo != null) && (certificateNo.length() == 0)) {
			btReimbursementSAPInfoCacheModel.certificateNo = null;
		}

		btReimbursementSAPInfoCacheModel.company = getCompany();

		String company = btReimbursementSAPInfoCacheModel.company;

		if ((company != null) && (company.length() == 0)) {
			btReimbursementSAPInfoCacheModel.company = null;
		}

		btReimbursementSAPInfoCacheModel.year = getYear();

		String year = btReimbursementSAPInfoCacheModel.year;

		if ((year != null) && (year.length() == 0)) {
			btReimbursementSAPInfoCacheModel.year = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			btReimbursementSAPInfoCacheModel.createDate = createDate.getTime();
		}
		else {
			btReimbursementSAPInfoCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			btReimbursementSAPInfoCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			btReimbursementSAPInfoCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return btReimbursementSAPInfoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{btReimbursementSAPInfoId=");
		sb.append(getBtReimbursementSAPInfoId());
		sb.append(", businessTripPkId=");
		sb.append(getBusinessTripPkId());
		sb.append(", ticketNo=");
		sb.append(getTicketNo());
		sb.append(", currency=");
		sb.append(getCurrency());
		sb.append(", step=");
		sb.append(getStep());
		sb.append(", messageType=");
		sb.append(getMessageType());
		sb.append(", message=");
		sb.append(getMessage());
		sb.append(", certificateNo=");
		sb.append(getCertificateNo());
		sb.append(", company=");
		sb.append(getCompany());
		sb.append(", year=");
		sb.append(getYear());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("com.business.trip.model.BtReimbursementSAPInfo");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>btReimbursementSAPInfoId</column-name><column-value><![CDATA[");
		sb.append(getBtReimbursementSAPInfoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>businessTripPkId</column-name><column-value><![CDATA[");
		sb.append(getBusinessTripPkId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ticketNo</column-name><column-value><![CDATA[");
		sb.append(getTicketNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>currency</column-name><column-value><![CDATA[");
		sb.append(getCurrency());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>step</column-name><column-value><![CDATA[");
		sb.append(getStep());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>messageType</column-name><column-value><![CDATA[");
		sb.append(getMessageType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>message</column-name><column-value><![CDATA[");
		sb.append(getMessage());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>certificateNo</column-name><column-value><![CDATA[");
		sb.append(getCertificateNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>company</column-name><column-value><![CDATA[");
		sb.append(getCompany());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>year</column-name><column-value><![CDATA[");
		sb.append(getYear());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = BtReimbursementSAPInfo.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			BtReimbursementSAPInfo.class
		};
	private long _btReimbursementSAPInfoId;
	private long _businessTripPkId;
	private long _originalBusinessTripPkId;
	private boolean _setOriginalBusinessTripPkId;
	private String _ticketNo;
	private String _currency;
	private String _originalCurrency;
	private int _step;
	private String _messageType;
	private String _message;
	private String _certificateNo;
	private String _company;
	private String _year;
	private Date _createDate;
	private Date _modifiedDate;
	private long _columnBitmask;
	private BtReimbursementSAPInfo _escapedModel;
}