/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.business.trip.model.impl;

import com.business.trip.model.BtTrainInfo;
import com.business.trip.model.BtTrainInfoModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the BtTrainInfo service. Represents a row in the &quot;vgcapon_BtTrainInfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.business.trip.model.BtTrainInfoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BtTrainInfoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BtTrainInfoImpl
 * @see com.business.trip.model.BtTrainInfo
 * @see com.business.trip.model.BtTrainInfoModel
 * @generated
 */
public class BtTrainInfoModelImpl extends BaseModelImpl<BtTrainInfo>
	implements BtTrainInfoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a bt train info model instance should use the {@link com.business.trip.model.BtTrainInfo} interface instead.
	 */
	public static final String TABLE_NAME = "vgcapon_BtTrainInfo";
	public static final Object[][] TABLE_COLUMNS = {
			{ "btTrainInfoId", Types.BIGINT },
			{ "businessTripPkId", Types.BIGINT },
			{ "ticketNo", Types.VARCHAR },
			{ "fromCity", Types.VARCHAR },
			{ "toCity", Types.VARCHAR },
			{ "departureDate", Types.TIMESTAMP },
			{ "departureTrain", Types.VARCHAR },
			{ "classInfo", Types.VARCHAR },
			{ "price", Types.DOUBLE },
			{ "currency_", Types.VARCHAR },
			{ "tripType", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table vgcapon_BtTrainInfo (btTrainInfoId LONG not null primary key,businessTripPkId LONG,ticketNo VARCHAR(75) null,fromCity VARCHAR(75) null,toCity VARCHAR(75) null,departureDate DATE null,departureTrain VARCHAR(75) null,classInfo VARCHAR(75) null,price DOUBLE,currency_ VARCHAR(75) null,tripType VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table vgcapon_BtTrainInfo";
	public static final String ORDER_BY_JPQL = " ORDER BY btTrainInfo.btTrainInfoId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY vgcapon_BtTrainInfo.btTrainInfoId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.business.trip.model.BtTrainInfo"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.business.trip.model.BtTrainInfo"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.business.trip.model.BtTrainInfo"),
			true);
	public static long BUSINESSTRIPPKID_COLUMN_BITMASK = 1L;
	public static long TICKETNO_COLUMN_BITMASK = 2L;
	public static long TRIPTYPE_COLUMN_BITMASK = 4L;
	public static long BTTRAININFOID_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.business.trip.model.BtTrainInfo"));

	public BtTrainInfoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _btTrainInfoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBtTrainInfoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _btTrainInfoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return BtTrainInfo.class;
	}

	@Override
	public String getModelClassName() {
		return BtTrainInfo.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("btTrainInfoId", getBtTrainInfoId());
		attributes.put("businessTripPkId", getBusinessTripPkId());
		attributes.put("ticketNo", getTicketNo());
		attributes.put("fromCity", getFromCity());
		attributes.put("toCity", getToCity());
		attributes.put("departureDate", getDepartureDate());
		attributes.put("departureTrain", getDepartureTrain());
		attributes.put("classInfo", getClassInfo());
		attributes.put("price", getPrice());
		attributes.put("currency", getCurrency());
		attributes.put("tripType", getTripType());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long btTrainInfoId = (Long)attributes.get("btTrainInfoId");

		if (btTrainInfoId != null) {
			setBtTrainInfoId(btTrainInfoId);
		}

		Long businessTripPkId = (Long)attributes.get("businessTripPkId");

		if (businessTripPkId != null) {
			setBusinessTripPkId(businessTripPkId);
		}

		String ticketNo = (String)attributes.get("ticketNo");

		if (ticketNo != null) {
			setTicketNo(ticketNo);
		}

		String fromCity = (String)attributes.get("fromCity");

		if (fromCity != null) {
			setFromCity(fromCity);
		}

		String toCity = (String)attributes.get("toCity");

		if (toCity != null) {
			setToCity(toCity);
		}

		Date departureDate = (Date)attributes.get("departureDate");

		if (departureDate != null) {
			setDepartureDate(departureDate);
		}

		String departureTrain = (String)attributes.get("departureTrain");

		if (departureTrain != null) {
			setDepartureTrain(departureTrain);
		}

		String classInfo = (String)attributes.get("classInfo");

		if (classInfo != null) {
			setClassInfo(classInfo);
		}

		Double price = (Double)attributes.get("price");

		if (price != null) {
			setPrice(price);
		}

		String currency = (String)attributes.get("currency");

		if (currency != null) {
			setCurrency(currency);
		}

		String tripType = (String)attributes.get("tripType");

		if (tripType != null) {
			setTripType(tripType);
		}
	}

	@Override
	public long getBtTrainInfoId() {
		return _btTrainInfoId;
	}

	@Override
	public void setBtTrainInfoId(long btTrainInfoId) {
		_btTrainInfoId = btTrainInfoId;
	}

	@Override
	public long getBusinessTripPkId() {
		return _businessTripPkId;
	}

	@Override
	public void setBusinessTripPkId(long businessTripPkId) {
		_columnBitmask |= BUSINESSTRIPPKID_COLUMN_BITMASK;

		if (!_setOriginalBusinessTripPkId) {
			_setOriginalBusinessTripPkId = true;

			_originalBusinessTripPkId = _businessTripPkId;
		}

		_businessTripPkId = businessTripPkId;
	}

	public long getOriginalBusinessTripPkId() {
		return _originalBusinessTripPkId;
	}

	@Override
	public String getTicketNo() {
		if (_ticketNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _ticketNo;
		}
	}

	@Override
	public void setTicketNo(String ticketNo) {
		_columnBitmask |= TICKETNO_COLUMN_BITMASK;

		if (_originalTicketNo == null) {
			_originalTicketNo = _ticketNo;
		}

		_ticketNo = ticketNo;
	}

	public String getOriginalTicketNo() {
		return GetterUtil.getString(_originalTicketNo);
	}

	@Override
	public String getFromCity() {
		if (_fromCity == null) {
			return StringPool.BLANK;
		}
		else {
			return _fromCity;
		}
	}

	@Override
	public void setFromCity(String fromCity) {
		_fromCity = fromCity;
	}

	@Override
	public String getToCity() {
		if (_toCity == null) {
			return StringPool.BLANK;
		}
		else {
			return _toCity;
		}
	}

	@Override
	public void setToCity(String toCity) {
		_toCity = toCity;
	}

	@Override
	public Date getDepartureDate() {
		return _departureDate;
	}

	@Override
	public void setDepartureDate(Date departureDate) {
		_departureDate = departureDate;
	}

	@Override
	public String getDepartureTrain() {
		if (_departureTrain == null) {
			return StringPool.BLANK;
		}
		else {
			return _departureTrain;
		}
	}

	@Override
	public void setDepartureTrain(String departureTrain) {
		_departureTrain = departureTrain;
	}

	@Override
	public String getClassInfo() {
		if (_classInfo == null) {
			return StringPool.BLANK;
		}
		else {
			return _classInfo;
		}
	}

	@Override
	public void setClassInfo(String classInfo) {
		_classInfo = classInfo;
	}

	@Override
	public double getPrice() {
		return _price;
	}

	@Override
	public void setPrice(double price) {
		_price = price;
	}

	@Override
	public String getCurrency() {
		if (_currency == null) {
			return StringPool.BLANK;
		}
		else {
			return _currency;
		}
	}

	@Override
	public void setCurrency(String currency) {
		_currency = currency;
	}

	@Override
	public String getTripType() {
		if (_tripType == null) {
			return StringPool.BLANK;
		}
		else {
			return _tripType;
		}
	}

	@Override
	public void setTripType(String tripType) {
		_columnBitmask |= TRIPTYPE_COLUMN_BITMASK;

		if (_originalTripType == null) {
			_originalTripType = _tripType;
		}

		_tripType = tripType;
	}

	public String getOriginalTripType() {
		return GetterUtil.getString(_originalTripType);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			BtTrainInfo.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public BtTrainInfo toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (BtTrainInfo)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BtTrainInfoImpl btTrainInfoImpl = new BtTrainInfoImpl();

		btTrainInfoImpl.setBtTrainInfoId(getBtTrainInfoId());
		btTrainInfoImpl.setBusinessTripPkId(getBusinessTripPkId());
		btTrainInfoImpl.setTicketNo(getTicketNo());
		btTrainInfoImpl.setFromCity(getFromCity());
		btTrainInfoImpl.setToCity(getToCity());
		btTrainInfoImpl.setDepartureDate(getDepartureDate());
		btTrainInfoImpl.setDepartureTrain(getDepartureTrain());
		btTrainInfoImpl.setClassInfo(getClassInfo());
		btTrainInfoImpl.setPrice(getPrice());
		btTrainInfoImpl.setCurrency(getCurrency());
		btTrainInfoImpl.setTripType(getTripType());

		btTrainInfoImpl.resetOriginalValues();

		return btTrainInfoImpl;
	}

	@Override
	public int compareTo(BtTrainInfo btTrainInfo) {
		long primaryKey = btTrainInfo.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof BtTrainInfo)) {
			return false;
		}

		BtTrainInfo btTrainInfo = (BtTrainInfo)obj;

		long primaryKey = btTrainInfo.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		BtTrainInfoModelImpl btTrainInfoModelImpl = this;

		btTrainInfoModelImpl._originalBusinessTripPkId = btTrainInfoModelImpl._businessTripPkId;

		btTrainInfoModelImpl._setOriginalBusinessTripPkId = false;

		btTrainInfoModelImpl._originalTicketNo = btTrainInfoModelImpl._ticketNo;

		btTrainInfoModelImpl._originalTripType = btTrainInfoModelImpl._tripType;

		btTrainInfoModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<BtTrainInfo> toCacheModel() {
		BtTrainInfoCacheModel btTrainInfoCacheModel = new BtTrainInfoCacheModel();

		btTrainInfoCacheModel.btTrainInfoId = getBtTrainInfoId();

		btTrainInfoCacheModel.businessTripPkId = getBusinessTripPkId();

		btTrainInfoCacheModel.ticketNo = getTicketNo();

		String ticketNo = btTrainInfoCacheModel.ticketNo;

		if ((ticketNo != null) && (ticketNo.length() == 0)) {
			btTrainInfoCacheModel.ticketNo = null;
		}

		btTrainInfoCacheModel.fromCity = getFromCity();

		String fromCity = btTrainInfoCacheModel.fromCity;

		if ((fromCity != null) && (fromCity.length() == 0)) {
			btTrainInfoCacheModel.fromCity = null;
		}

		btTrainInfoCacheModel.toCity = getToCity();

		String toCity = btTrainInfoCacheModel.toCity;

		if ((toCity != null) && (toCity.length() == 0)) {
			btTrainInfoCacheModel.toCity = null;
		}

		Date departureDate = getDepartureDate();

		if (departureDate != null) {
			btTrainInfoCacheModel.departureDate = departureDate.getTime();
		}
		else {
			btTrainInfoCacheModel.departureDate = Long.MIN_VALUE;
		}

		btTrainInfoCacheModel.departureTrain = getDepartureTrain();

		String departureTrain = btTrainInfoCacheModel.departureTrain;

		if ((departureTrain != null) && (departureTrain.length() == 0)) {
			btTrainInfoCacheModel.departureTrain = null;
		}

		btTrainInfoCacheModel.classInfo = getClassInfo();

		String classInfo = btTrainInfoCacheModel.classInfo;

		if ((classInfo != null) && (classInfo.length() == 0)) {
			btTrainInfoCacheModel.classInfo = null;
		}

		btTrainInfoCacheModel.price = getPrice();

		btTrainInfoCacheModel.currency = getCurrency();

		String currency = btTrainInfoCacheModel.currency;

		if ((currency != null) && (currency.length() == 0)) {
			btTrainInfoCacheModel.currency = null;
		}

		btTrainInfoCacheModel.tripType = getTripType();

		String tripType = btTrainInfoCacheModel.tripType;

		if ((tripType != null) && (tripType.length() == 0)) {
			btTrainInfoCacheModel.tripType = null;
		}

		return btTrainInfoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{btTrainInfoId=");
		sb.append(getBtTrainInfoId());
		sb.append(", businessTripPkId=");
		sb.append(getBusinessTripPkId());
		sb.append(", ticketNo=");
		sb.append(getTicketNo());
		sb.append(", fromCity=");
		sb.append(getFromCity());
		sb.append(", toCity=");
		sb.append(getToCity());
		sb.append(", departureDate=");
		sb.append(getDepartureDate());
		sb.append(", departureTrain=");
		sb.append(getDepartureTrain());
		sb.append(", classInfo=");
		sb.append(getClassInfo());
		sb.append(", price=");
		sb.append(getPrice());
		sb.append(", currency=");
		sb.append(getCurrency());
		sb.append(", tripType=");
		sb.append(getTripType());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("com.business.trip.model.BtTrainInfo");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>btTrainInfoId</column-name><column-value><![CDATA[");
		sb.append(getBtTrainInfoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>businessTripPkId</column-name><column-value><![CDATA[");
		sb.append(getBusinessTripPkId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ticketNo</column-name><column-value><![CDATA[");
		sb.append(getTicketNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fromCity</column-name><column-value><![CDATA[");
		sb.append(getFromCity());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>toCity</column-name><column-value><![CDATA[");
		sb.append(getToCity());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>departureDate</column-name><column-value><![CDATA[");
		sb.append(getDepartureDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>departureTrain</column-name><column-value><![CDATA[");
		sb.append(getDepartureTrain());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classInfo</column-name><column-value><![CDATA[");
		sb.append(getClassInfo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>price</column-name><column-value><![CDATA[");
		sb.append(getPrice());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>currency</column-name><column-value><![CDATA[");
		sb.append(getCurrency());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tripType</column-name><column-value><![CDATA[");
		sb.append(getTripType());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = BtTrainInfo.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			BtTrainInfo.class
		};
	private long _btTrainInfoId;
	private long _businessTripPkId;
	private long _originalBusinessTripPkId;
	private boolean _setOriginalBusinessTripPkId;
	private String _ticketNo;
	private String _originalTicketNo;
	private String _fromCity;
	private String _toCity;
	private Date _departureDate;
	private String _departureTrain;
	private String _classInfo;
	private double _price;
	private String _currency;
	private String _tripType;
	private String _originalTripType;
	private long _columnBitmask;
	private BtTrainInfo _escapedModel;
}