/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.business.trip.model.impl;

import com.business.trip.model.BusinessTripReimbursement;
import com.business.trip.model.BusinessTripReimbursementModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.workflow.WorkflowConstants;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the BusinessTripReimbursement service. Represents a row in the &quot;VgcApon_BtReimbursement&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.business.trip.model.BusinessTripReimbursementModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BusinessTripReimbursementImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BusinessTripReimbursementImpl
 * @see com.business.trip.model.BusinessTripReimbursement
 * @see com.business.trip.model.BusinessTripReimbursementModel
 * @generated
 */
public class BusinessTripReimbursementModelImpl extends BaseModelImpl<BusinessTripReimbursement>
	implements BusinessTripReimbursementModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a business trip reimbursement model instance should use the {@link com.business.trip.model.BusinessTripReimbursement} interface instead.
	 */
	public static final String TABLE_NAME = "VgcApon_BtReimbursement";
	public static final Object[][] TABLE_COLUMNS = {
			{ "businessTripReimbursementId", Types.BIGINT },
			{ "ticketNo", Types.VARCHAR },
			{ "bussinessTirpTicketNo", Types.VARCHAR },
			{ "processType", Types.VARCHAR },
			{ "subType", Types.VARCHAR },
			{ "printName", Types.VARCHAR },
			{ "staffCode", Types.BIGINT },
			{ "companyName", Types.VARCHAR },
			{ "division", Types.VARCHAR },
			{ "department", Types.VARCHAR },
			{ "costCenter", Types.VARCHAR },
			{ "personalID", Types.VARCHAR },
			{ "passportNo", Types.VARCHAR },
			{ "officePhone", Types.VARCHAR },
			{ "mobilePhone", Types.VARCHAR },
			{ "email", Types.VARCHAR },
			{ "officeSite", Types.VARCHAR },
			{ "approverId", Types.BIGINT },
			{ "approverName", Types.VARCHAR },
			{ "isCrossDepartment", Types.BOOLEAN },
			{ "targetDepartmentId", Types.BIGINT },
			{ "targetDepartmentName", Types.VARCHAR },
			{ "targetCostCenter", Types.VARCHAR },
			{ "targetDepartmentApproverId", Types.BIGINT },
			{ "targetDepartmentApproverName", Types.VARCHAR },
			{ "tripType", Types.INTEGER },
			{ "departureDate", Types.TIMESTAMP },
			{ "returnDate", Types.TIMESTAMP },
			{ "purposeOfTheTrip", Types.VARCHAR },
			{ "visitCountriesCities", Types.VARCHAR },
			{ "advancePayment", Types.DOUBLE },
			{ "currency_", Types.VARCHAR },
			{ "paymentMethods", Types.VARCHAR },
			{ "totalCostRmb", Types.DOUBLE },
			{ "totalCostEur", Types.DOUBLE },
			{ "orgTotalCostRmb", Types.DOUBLE },
			{ "orgTotalCostEur", Types.DOUBLE },
			{ "hotelTotalCostRmb", Types.DOUBLE },
			{ "hotelTotalCostEur", Types.DOUBLE },
			{ "carRentalTotalCostRmb", Types.DOUBLE },
			{ "carRentalTotalCostEur", Types.DOUBLE },
			{ "flightCurrency", Types.VARCHAR },
			{ "flightTotal", Types.DOUBLE },
			{ "flightAirFare", Types.DOUBLE },
			{ "flightTaxes", Types.DOUBLE },
			{ "flightTransactionFee", Types.DOUBLE },
			{ "totalTravelExpenseRmb", Types.DOUBLE },
			{ "totalTravelExpenseEur", Types.DOUBLE },
			{ "costListInlandTotalRmb", Types.DOUBLE },
			{ "costListForeignTotalEur", Types.DOUBLE },
			{ "costListForeignTotalRmb", Types.DOUBLE },
			{ "remark", Types.VARCHAR },
			{ "isPaybyRmb", Types.BOOLEAN },
			{ "evpId", Types.BIGINT },
			{ "evpName", Types.VARCHAR },
			{ "status", Types.INTEGER },
			{ "sapStatus", Types.INTEGER },
			{ "sapComments", Types.VARCHAR },
			{ "sapDocumentId", Types.VARCHAR },
			{ "statusByUserId", Types.BIGINT },
			{ "statusByUserName", Types.VARCHAR },
			{ "statusDate", Types.TIMESTAMP },
			{ "isApplicantAgent", Types.BOOLEAN },
			{ "isApproverAgent", Types.BOOLEAN },
			{ "groupId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "submittedDate", Types.TIMESTAMP },
			{ "companyId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table VgcApon_BtReimbursement (businessTripReimbursementId LONG not null primary key,ticketNo VARCHAR(75) null,bussinessTirpTicketNo VARCHAR(75) null,processType VARCHAR(75) null,subType VARCHAR(75) null,printName VARCHAR(75) null,staffCode LONG,companyName VARCHAR(75) null,division VARCHAR(75) null,department VARCHAR(75) null,costCenter VARCHAR(75) null,personalID VARCHAR(75) null,passportNo VARCHAR(75) null,officePhone VARCHAR(75) null,mobilePhone VARCHAR(75) null,email VARCHAR(75) null,officeSite VARCHAR(75) null,approverId LONG,approverName VARCHAR(75) null,isCrossDepartment BOOLEAN,targetDepartmentId LONG,targetDepartmentName VARCHAR(75) null,targetCostCenter VARCHAR(75) null,targetDepartmentApproverId LONG,targetDepartmentApproverName VARCHAR(75) null,tripType INTEGER,departureDate DATE null,returnDate DATE null,purposeOfTheTrip VARCHAR(512) null,visitCountriesCities VARCHAR(75) null,advancePayment DOUBLE,currency_ VARCHAR(75) null,paymentMethods VARCHAR(75) null,totalCostRmb DOUBLE,totalCostEur DOUBLE,orgTotalCostRmb DOUBLE,orgTotalCostEur DOUBLE,hotelTotalCostRmb DOUBLE,hotelTotalCostEur DOUBLE,carRentalTotalCostRmb DOUBLE,carRentalTotalCostEur DOUBLE,flightCurrency VARCHAR(75) null,flightTotal DOUBLE,flightAirFare DOUBLE,flightTaxes DOUBLE,flightTransactionFee DOUBLE,totalTravelExpenseRmb DOUBLE,totalTravelExpenseEur DOUBLE,costListInlandTotalRmb DOUBLE,costListForeignTotalEur DOUBLE,costListForeignTotalRmb DOUBLE,remark VARCHAR(512) null,isPaybyRmb BOOLEAN,evpId LONG,evpName VARCHAR(75) null,status INTEGER,sapStatus INTEGER,sapComments VARCHAR(1024) null,sapDocumentId VARCHAR(512) null,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,isApplicantAgent BOOLEAN,isApproverAgent BOOLEAN,groupId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,submittedDate DATE null,companyId LONG)";
	public static final String TABLE_SQL_DROP = "drop table VgcApon_BtReimbursement";
	public static final String ORDER_BY_JPQL = " ORDER BY businessTripReimbursement.createDate ASC";
	public static final String ORDER_BY_SQL = " ORDER BY VgcApon_BtReimbursement.createDate ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.business.trip.model.BusinessTripReimbursement"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.business.trip.model.BusinessTripReimbursement"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.business.trip.model.BusinessTripReimbursement"),
			true);
	public static long BUSSINESSTIRPTICKETNO_COLUMN_BITMASK = 1L;
	public static long STATUS_COLUMN_BITMASK = 2L;
	public static long TICKETNO_COLUMN_BITMASK = 4L;
	public static long USERID_COLUMN_BITMASK = 8L;
	public static long CREATEDATE_COLUMN_BITMASK = 16L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.business.trip.model.BusinessTripReimbursement"));

	public BusinessTripReimbursementModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _businessTripReimbursementId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBusinessTripReimbursementId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _businessTripReimbursementId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return BusinessTripReimbursement.class;
	}

	@Override
	public String getModelClassName() {
		return BusinessTripReimbursement.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("businessTripReimbursementId",
			getBusinessTripReimbursementId());
		attributes.put("ticketNo", getTicketNo());
		attributes.put("bussinessTirpTicketNo", getBussinessTirpTicketNo());
		attributes.put("processType", getProcessType());
		attributes.put("subType", getSubType());
		attributes.put("printName", getPrintName());
		attributes.put("staffCode", getStaffCode());
		attributes.put("companyName", getCompanyName());
		attributes.put("division", getDivision());
		attributes.put("department", getDepartment());
		attributes.put("costCenter", getCostCenter());
		attributes.put("personalID", getPersonalID());
		attributes.put("passportNo", getPassportNo());
		attributes.put("officePhone", getOfficePhone());
		attributes.put("mobilePhone", getMobilePhone());
		attributes.put("email", getEmail());
		attributes.put("officeSite", getOfficeSite());
		attributes.put("approverId", getApproverId());
		attributes.put("approverName", getApproverName());
		attributes.put("isCrossDepartment", getIsCrossDepartment());
		attributes.put("targetDepartmentId", getTargetDepartmentId());
		attributes.put("targetDepartmentName", getTargetDepartmentName());
		attributes.put("targetCostCenter", getTargetCostCenter());
		attributes.put("targetDepartmentApproverId",
			getTargetDepartmentApproverId());
		attributes.put("targetDepartmentApproverName",
			getTargetDepartmentApproverName());
		attributes.put("tripType", getTripType());
		attributes.put("departureDate", getDepartureDate());
		attributes.put("returnDate", getReturnDate());
		attributes.put("purposeOfTheTrip", getPurposeOfTheTrip());
		attributes.put("visitCountriesCities", getVisitCountriesCities());
		attributes.put("advancePayment", getAdvancePayment());
		attributes.put("currency", getCurrency());
		attributes.put("paymentMethods", getPaymentMethods());
		attributes.put("totalCostRmb", getTotalCostRmb());
		attributes.put("totalCostEur", getTotalCostEur());
		attributes.put("orgTotalCostRmb", getOrgTotalCostRmb());
		attributes.put("orgTotalCostEur", getOrgTotalCostEur());
		attributes.put("hotelTotalCostRmb", getHotelTotalCostRmb());
		attributes.put("hotelTotalCostEur", getHotelTotalCostEur());
		attributes.put("carRentalTotalCostRmb", getCarRentalTotalCostRmb());
		attributes.put("carRentalTotalCostEur", getCarRentalTotalCostEur());
		attributes.put("flightCurrency", getFlightCurrency());
		attributes.put("flightTotal", getFlightTotal());
		attributes.put("flightAirFare", getFlightAirFare());
		attributes.put("flightTaxes", getFlightTaxes());
		attributes.put("flightTransactionFee", getFlightTransactionFee());
		attributes.put("totalTravelExpenseRmb", getTotalTravelExpenseRmb());
		attributes.put("totalTravelExpenseEur", getTotalTravelExpenseEur());
		attributes.put("costListInlandTotalRmb", getCostListInlandTotalRmb());
		attributes.put("costListForeignTotalEur", getCostListForeignTotalEur());
		attributes.put("costListForeignTotalRmb", getCostListForeignTotalRmb());
		attributes.put("remark", getRemark());
		attributes.put("isPaybyRmb", getIsPaybyRmb());
		attributes.put("evpId", getEvpId());
		attributes.put("evpName", getEvpName());
		attributes.put("status", getStatus());
		attributes.put("sapStatus", getSapStatus());
		attributes.put("sapComments", getSapComments());
		attributes.put("sapDocumentId", getSapDocumentId());
		attributes.put("statusByUserId", getStatusByUserId());
		attributes.put("statusByUserName", getStatusByUserName());
		attributes.put("statusDate", getStatusDate());
		attributes.put("isApplicantAgent", getIsApplicantAgent());
		attributes.put("isApproverAgent", getIsApproverAgent());
		attributes.put("groupId", getGroupId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("submittedDate", getSubmittedDate());
		attributes.put("companyId", getCompanyId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long businessTripReimbursementId = (Long)attributes.get(
				"businessTripReimbursementId");

		if (businessTripReimbursementId != null) {
			setBusinessTripReimbursementId(businessTripReimbursementId);
		}

		String ticketNo = (String)attributes.get("ticketNo");

		if (ticketNo != null) {
			setTicketNo(ticketNo);
		}

		String bussinessTirpTicketNo = (String)attributes.get(
				"bussinessTirpTicketNo");

		if (bussinessTirpTicketNo != null) {
			setBussinessTirpTicketNo(bussinessTirpTicketNo);
		}

		String processType = (String)attributes.get("processType");

		if (processType != null) {
			setProcessType(processType);
		}

		String subType = (String)attributes.get("subType");

		if (subType != null) {
			setSubType(subType);
		}

		String printName = (String)attributes.get("printName");

		if (printName != null) {
			setPrintName(printName);
		}

		Long staffCode = (Long)attributes.get("staffCode");

		if (staffCode != null) {
			setStaffCode(staffCode);
		}

		String companyName = (String)attributes.get("companyName");

		if (companyName != null) {
			setCompanyName(companyName);
		}

		String division = (String)attributes.get("division");

		if (division != null) {
			setDivision(division);
		}

		String department = (String)attributes.get("department");

		if (department != null) {
			setDepartment(department);
		}

		String costCenter = (String)attributes.get("costCenter");

		if (costCenter != null) {
			setCostCenter(costCenter);
		}

		String personalID = (String)attributes.get("personalID");

		if (personalID != null) {
			setPersonalID(personalID);
		}

		String passportNo = (String)attributes.get("passportNo");

		if (passportNo != null) {
			setPassportNo(passportNo);
		}

		String officePhone = (String)attributes.get("officePhone");

		if (officePhone != null) {
			setOfficePhone(officePhone);
		}

		String mobilePhone = (String)attributes.get("mobilePhone");

		if (mobilePhone != null) {
			setMobilePhone(mobilePhone);
		}

		String email = (String)attributes.get("email");

		if (email != null) {
			setEmail(email);
		}

		String officeSite = (String)attributes.get("officeSite");

		if (officeSite != null) {
			setOfficeSite(officeSite);
		}

		Long approverId = (Long)attributes.get("approverId");

		if (approverId != null) {
			setApproverId(approverId);
		}

		String approverName = (String)attributes.get("approverName");

		if (approverName != null) {
			setApproverName(approverName);
		}

		Boolean isCrossDepartment = (Boolean)attributes.get("isCrossDepartment");

		if (isCrossDepartment != null) {
			setIsCrossDepartment(isCrossDepartment);
		}

		Long targetDepartmentId = (Long)attributes.get("targetDepartmentId");

		if (targetDepartmentId != null) {
			setTargetDepartmentId(targetDepartmentId);
		}

		String targetDepartmentName = (String)attributes.get(
				"targetDepartmentName");

		if (targetDepartmentName != null) {
			setTargetDepartmentName(targetDepartmentName);
		}

		String targetCostCenter = (String)attributes.get("targetCostCenter");

		if (targetCostCenter != null) {
			setTargetCostCenter(targetCostCenter);
		}

		Long targetDepartmentApproverId = (Long)attributes.get(
				"targetDepartmentApproverId");

		if (targetDepartmentApproverId != null) {
			setTargetDepartmentApproverId(targetDepartmentApproverId);
		}

		String targetDepartmentApproverName = (String)attributes.get(
				"targetDepartmentApproverName");

		if (targetDepartmentApproverName != null) {
			setTargetDepartmentApproverName(targetDepartmentApproverName);
		}

		Integer tripType = (Integer)attributes.get("tripType");

		if (tripType != null) {
			setTripType(tripType);
		}

		Date departureDate = (Date)attributes.get("departureDate");

		if (departureDate != null) {
			setDepartureDate(departureDate);
		}

		Date returnDate = (Date)attributes.get("returnDate");

		if (returnDate != null) {
			setReturnDate(returnDate);
		}

		String purposeOfTheTrip = (String)attributes.get("purposeOfTheTrip");

		if (purposeOfTheTrip != null) {
			setPurposeOfTheTrip(purposeOfTheTrip);
		}

		String visitCountriesCities = (String)attributes.get(
				"visitCountriesCities");

		if (visitCountriesCities != null) {
			setVisitCountriesCities(visitCountriesCities);
		}

		Double advancePayment = (Double)attributes.get("advancePayment");

		if (advancePayment != null) {
			setAdvancePayment(advancePayment);
		}

		String currency = (String)attributes.get("currency");

		if (currency != null) {
			setCurrency(currency);
		}

		String paymentMethods = (String)attributes.get("paymentMethods");

		if (paymentMethods != null) {
			setPaymentMethods(paymentMethods);
		}

		Double totalCostRmb = (Double)attributes.get("totalCostRmb");

		if (totalCostRmb != null) {
			setTotalCostRmb(totalCostRmb);
		}

		Double totalCostEur = (Double)attributes.get("totalCostEur");

		if (totalCostEur != null) {
			setTotalCostEur(totalCostEur);
		}

		Double orgTotalCostRmb = (Double)attributes.get("orgTotalCostRmb");

		if (orgTotalCostRmb != null) {
			setOrgTotalCostRmb(orgTotalCostRmb);
		}

		Double orgTotalCostEur = (Double)attributes.get("orgTotalCostEur");

		if (orgTotalCostEur != null) {
			setOrgTotalCostEur(orgTotalCostEur);
		}

		Double hotelTotalCostRmb = (Double)attributes.get("hotelTotalCostRmb");

		if (hotelTotalCostRmb != null) {
			setHotelTotalCostRmb(hotelTotalCostRmb);
		}

		Double hotelTotalCostEur = (Double)attributes.get("hotelTotalCostEur");

		if (hotelTotalCostEur != null) {
			setHotelTotalCostEur(hotelTotalCostEur);
		}

		Double carRentalTotalCostRmb = (Double)attributes.get(
				"carRentalTotalCostRmb");

		if (carRentalTotalCostRmb != null) {
			setCarRentalTotalCostRmb(carRentalTotalCostRmb);
		}

		Double carRentalTotalCostEur = (Double)attributes.get(
				"carRentalTotalCostEur");

		if (carRentalTotalCostEur != null) {
			setCarRentalTotalCostEur(carRentalTotalCostEur);
		}

		String flightCurrency = (String)attributes.get("flightCurrency");

		if (flightCurrency != null) {
			setFlightCurrency(flightCurrency);
		}

		Double flightTotal = (Double)attributes.get("flightTotal");

		if (flightTotal != null) {
			setFlightTotal(flightTotal);
		}

		Double flightAirFare = (Double)attributes.get("flightAirFare");

		if (flightAirFare != null) {
			setFlightAirFare(flightAirFare);
		}

		Double flightTaxes = (Double)attributes.get("flightTaxes");

		if (flightTaxes != null) {
			setFlightTaxes(flightTaxes);
		}

		Double flightTransactionFee = (Double)attributes.get(
				"flightTransactionFee");

		if (flightTransactionFee != null) {
			setFlightTransactionFee(flightTransactionFee);
		}

		Double totalTravelExpenseRmb = (Double)attributes.get(
				"totalTravelExpenseRmb");

		if (totalTravelExpenseRmb != null) {
			setTotalTravelExpenseRmb(totalTravelExpenseRmb);
		}

		Double totalTravelExpenseEur = (Double)attributes.get(
				"totalTravelExpenseEur");

		if (totalTravelExpenseEur != null) {
			setTotalTravelExpenseEur(totalTravelExpenseEur);
		}

		Double costListInlandTotalRmb = (Double)attributes.get(
				"costListInlandTotalRmb");

		if (costListInlandTotalRmb != null) {
			setCostListInlandTotalRmb(costListInlandTotalRmb);
		}

		Double costListForeignTotalEur = (Double)attributes.get(
				"costListForeignTotalEur");

		if (costListForeignTotalEur != null) {
			setCostListForeignTotalEur(costListForeignTotalEur);
		}

		Double costListForeignTotalRmb = (Double)attributes.get(
				"costListForeignTotalRmb");

		if (costListForeignTotalRmb != null) {
			setCostListForeignTotalRmb(costListForeignTotalRmb);
		}

		String remark = (String)attributes.get("remark");

		if (remark != null) {
			setRemark(remark);
		}

		Boolean isPaybyRmb = (Boolean)attributes.get("isPaybyRmb");

		if (isPaybyRmb != null) {
			setIsPaybyRmb(isPaybyRmb);
		}

		Long evpId = (Long)attributes.get("evpId");

		if (evpId != null) {
			setEvpId(evpId);
		}

		String evpName = (String)attributes.get("evpName");

		if (evpName != null) {
			setEvpName(evpName);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		Integer sapStatus = (Integer)attributes.get("sapStatus");

		if (sapStatus != null) {
			setSapStatus(sapStatus);
		}

		String sapComments = (String)attributes.get("sapComments");

		if (sapComments != null) {
			setSapComments(sapComments);
		}

		String sapDocumentId = (String)attributes.get("sapDocumentId");

		if (sapDocumentId != null) {
			setSapDocumentId(sapDocumentId);
		}

		Long statusByUserId = (Long)attributes.get("statusByUserId");

		if (statusByUserId != null) {
			setStatusByUserId(statusByUserId);
		}

		String statusByUserName = (String)attributes.get("statusByUserName");

		if (statusByUserName != null) {
			setStatusByUserName(statusByUserName);
		}

		Date statusDate = (Date)attributes.get("statusDate");

		if (statusDate != null) {
			setStatusDate(statusDate);
		}

		Boolean isApplicantAgent = (Boolean)attributes.get("isApplicantAgent");

		if (isApplicantAgent != null) {
			setIsApplicantAgent(isApplicantAgent);
		}

		Boolean isApproverAgent = (Boolean)attributes.get("isApproverAgent");

		if (isApproverAgent != null) {
			setIsApproverAgent(isApproverAgent);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Date submittedDate = (Date)attributes.get("submittedDate");

		if (submittedDate != null) {
			setSubmittedDate(submittedDate);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}
	}

	@Override
	public long getBusinessTripReimbursementId() {
		return _businessTripReimbursementId;
	}

	@Override
	public void setBusinessTripReimbursementId(long businessTripReimbursementId) {
		_businessTripReimbursementId = businessTripReimbursementId;
	}

	@Override
	public String getTicketNo() {
		if (_ticketNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _ticketNo;
		}
	}

	@Override
	public void setTicketNo(String ticketNo) {
		_columnBitmask |= TICKETNO_COLUMN_BITMASK;

		if (_originalTicketNo == null) {
			_originalTicketNo = _ticketNo;
		}

		_ticketNo = ticketNo;
	}

	public String getOriginalTicketNo() {
		return GetterUtil.getString(_originalTicketNo);
	}

	@Override
	public String getBussinessTirpTicketNo() {
		if (_bussinessTirpTicketNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _bussinessTirpTicketNo;
		}
	}

	@Override
	public void setBussinessTirpTicketNo(String bussinessTirpTicketNo) {
		_columnBitmask |= BUSSINESSTIRPTICKETNO_COLUMN_BITMASK;

		if (_originalBussinessTirpTicketNo == null) {
			_originalBussinessTirpTicketNo = _bussinessTirpTicketNo;
		}

		_bussinessTirpTicketNo = bussinessTirpTicketNo;
	}

	public String getOriginalBussinessTirpTicketNo() {
		return GetterUtil.getString(_originalBussinessTirpTicketNo);
	}

	@Override
	public String getProcessType() {
		if (_processType == null) {
			return StringPool.BLANK;
		}
		else {
			return _processType;
		}
	}

	@Override
	public void setProcessType(String processType) {
		_processType = processType;
	}

	@Override
	public String getSubType() {
		if (_subType == null) {
			return StringPool.BLANK;
		}
		else {
			return _subType;
		}
	}

	@Override
	public void setSubType(String subType) {
		_subType = subType;
	}

	@Override
	public String getPrintName() {
		if (_printName == null) {
			return StringPool.BLANK;
		}
		else {
			return _printName;
		}
	}

	@Override
	public void setPrintName(String printName) {
		_printName = printName;
	}

	@Override
	public long getStaffCode() {
		return _staffCode;
	}

	@Override
	public void setStaffCode(long staffCode) {
		_staffCode = staffCode;
	}

	@Override
	public String getCompanyName() {
		if (_companyName == null) {
			return StringPool.BLANK;
		}
		else {
			return _companyName;
		}
	}

	@Override
	public void setCompanyName(String companyName) {
		_companyName = companyName;
	}

	@Override
	public String getDivision() {
		if (_division == null) {
			return StringPool.BLANK;
		}
		else {
			return _division;
		}
	}

	@Override
	public void setDivision(String division) {
		_division = division;
	}

	@Override
	public String getDepartment() {
		if (_department == null) {
			return StringPool.BLANK;
		}
		else {
			return _department;
		}
	}

	@Override
	public void setDepartment(String department) {
		_department = department;
	}

	@Override
	public String getCostCenter() {
		if (_costCenter == null) {
			return StringPool.BLANK;
		}
		else {
			return _costCenter;
		}
	}

	@Override
	public void setCostCenter(String costCenter) {
		_costCenter = costCenter;
	}

	@Override
	public String getPersonalID() {
		if (_personalID == null) {
			return StringPool.BLANK;
		}
		else {
			return _personalID;
		}
	}

	@Override
	public void setPersonalID(String personalID) {
		_personalID = personalID;
	}

	@Override
	public String getPassportNo() {
		if (_passportNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _passportNo;
		}
	}

	@Override
	public void setPassportNo(String passportNo) {
		_passportNo = passportNo;
	}

	@Override
	public String getOfficePhone() {
		if (_officePhone == null) {
			return StringPool.BLANK;
		}
		else {
			return _officePhone;
		}
	}

	@Override
	public void setOfficePhone(String officePhone) {
		_officePhone = officePhone;
	}

	@Override
	public String getMobilePhone() {
		if (_mobilePhone == null) {
			return StringPool.BLANK;
		}
		else {
			return _mobilePhone;
		}
	}

	@Override
	public void setMobilePhone(String mobilePhone) {
		_mobilePhone = mobilePhone;
	}

	@Override
	public String getEmail() {
		if (_email == null) {
			return StringPool.BLANK;
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		_email = email;
	}

	@Override
	public String getOfficeSite() {
		if (_officeSite == null) {
			return StringPool.BLANK;
		}
		else {
			return _officeSite;
		}
	}

	@Override
	public void setOfficeSite(String officeSite) {
		_officeSite = officeSite;
	}

	@Override
	public long getApproverId() {
		return _approverId;
	}

	@Override
	public void setApproverId(long approverId) {
		_approverId = approverId;
	}

	@Override
	public String getApproverName() {
		if (_approverName == null) {
			return StringPool.BLANK;
		}
		else {
			return _approverName;
		}
	}

	@Override
	public void setApproverName(String approverName) {
		_approverName = approverName;
	}

	@Override
	public boolean getIsCrossDepartment() {
		return _isCrossDepartment;
	}

	@Override
	public boolean isIsCrossDepartment() {
		return _isCrossDepartment;
	}

	@Override
	public void setIsCrossDepartment(boolean isCrossDepartment) {
		_isCrossDepartment = isCrossDepartment;
	}

	@Override
	public long getTargetDepartmentId() {
		return _targetDepartmentId;
	}

	@Override
	public void setTargetDepartmentId(long targetDepartmentId) {
		_targetDepartmentId = targetDepartmentId;
	}

	@Override
	public String getTargetDepartmentName() {
		if (_targetDepartmentName == null) {
			return StringPool.BLANK;
		}
		else {
			return _targetDepartmentName;
		}
	}

	@Override
	public void setTargetDepartmentName(String targetDepartmentName) {
		_targetDepartmentName = targetDepartmentName;
	}

	@Override
	public String getTargetCostCenter() {
		if (_targetCostCenter == null) {
			return StringPool.BLANK;
		}
		else {
			return _targetCostCenter;
		}
	}

	@Override
	public void setTargetCostCenter(String targetCostCenter) {
		_targetCostCenter = targetCostCenter;
	}

	@Override
	public long getTargetDepartmentApproverId() {
		return _targetDepartmentApproverId;
	}

	@Override
	public void setTargetDepartmentApproverId(long targetDepartmentApproverId) {
		_targetDepartmentApproverId = targetDepartmentApproverId;
	}

	@Override
	public String getTargetDepartmentApproverName() {
		if (_targetDepartmentApproverName == null) {
			return StringPool.BLANK;
		}
		else {
			return _targetDepartmentApproverName;
		}
	}

	@Override
	public void setTargetDepartmentApproverName(
		String targetDepartmentApproverName) {
		_targetDepartmentApproverName = targetDepartmentApproverName;
	}

	@Override
	public int getTripType() {
		return _tripType;
	}

	@Override
	public void setTripType(int tripType) {
		_tripType = tripType;
	}

	@Override
	public Date getDepartureDate() {
		return _departureDate;
	}

	@Override
	public void setDepartureDate(Date departureDate) {
		_departureDate = departureDate;
	}

	@Override
	public Date getReturnDate() {
		return _returnDate;
	}

	@Override
	public void setReturnDate(Date returnDate) {
		_returnDate = returnDate;
	}

	@Override
	public String getPurposeOfTheTrip() {
		if (_purposeOfTheTrip == null) {
			return StringPool.BLANK;
		}
		else {
			return _purposeOfTheTrip;
		}
	}

	@Override
	public void setPurposeOfTheTrip(String purposeOfTheTrip) {
		_purposeOfTheTrip = purposeOfTheTrip;
	}

	@Override
	public String getVisitCountriesCities() {
		if (_visitCountriesCities == null) {
			return StringPool.BLANK;
		}
		else {
			return _visitCountriesCities;
		}
	}

	@Override
	public void setVisitCountriesCities(String visitCountriesCities) {
		_visitCountriesCities = visitCountriesCities;
	}

	@Override
	public double getAdvancePayment() {
		return _advancePayment;
	}

	@Override
	public void setAdvancePayment(double advancePayment) {
		_advancePayment = advancePayment;
	}

	@Override
	public String getCurrency() {
		if (_currency == null) {
			return StringPool.BLANK;
		}
		else {
			return _currency;
		}
	}

	@Override
	public void setCurrency(String currency) {
		_currency = currency;
	}

	@Override
	public String getPaymentMethods() {
		if (_paymentMethods == null) {
			return StringPool.BLANK;
		}
		else {
			return _paymentMethods;
		}
	}

	@Override
	public void setPaymentMethods(String paymentMethods) {
		_paymentMethods = paymentMethods;
	}

	@Override
	public double getTotalCostRmb() {
		return _totalCostRmb;
	}

	@Override
	public void setTotalCostRmb(double totalCostRmb) {
		_totalCostRmb = totalCostRmb;
	}

	@Override
	public double getTotalCostEur() {
		return _totalCostEur;
	}

	@Override
	public void setTotalCostEur(double totalCostEur) {
		_totalCostEur = totalCostEur;
	}

	@Override
	public double getOrgTotalCostRmb() {
		return _orgTotalCostRmb;
	}

	@Override
	public void setOrgTotalCostRmb(double orgTotalCostRmb) {
		_orgTotalCostRmb = orgTotalCostRmb;
	}

	@Override
	public double getOrgTotalCostEur() {
		return _orgTotalCostEur;
	}

	@Override
	public void setOrgTotalCostEur(double orgTotalCostEur) {
		_orgTotalCostEur = orgTotalCostEur;
	}

	@Override
	public double getHotelTotalCostRmb() {
		return _hotelTotalCostRmb;
	}

	@Override
	public void setHotelTotalCostRmb(double hotelTotalCostRmb) {
		_hotelTotalCostRmb = hotelTotalCostRmb;
	}

	@Override
	public double getHotelTotalCostEur() {
		return _hotelTotalCostEur;
	}

	@Override
	public void setHotelTotalCostEur(double hotelTotalCostEur) {
		_hotelTotalCostEur = hotelTotalCostEur;
	}

	@Override
	public double getCarRentalTotalCostRmb() {
		return _carRentalTotalCostRmb;
	}

	@Override
	public void setCarRentalTotalCostRmb(double carRentalTotalCostRmb) {
		_carRentalTotalCostRmb = carRentalTotalCostRmb;
	}

	@Override
	public double getCarRentalTotalCostEur() {
		return _carRentalTotalCostEur;
	}

	@Override
	public void setCarRentalTotalCostEur(double carRentalTotalCostEur) {
		_carRentalTotalCostEur = carRentalTotalCostEur;
	}

	@Override
	public String getFlightCurrency() {
		if (_flightCurrency == null) {
			return StringPool.BLANK;
		}
		else {
			return _flightCurrency;
		}
	}

	@Override
	public void setFlightCurrency(String flightCurrency) {
		_flightCurrency = flightCurrency;
	}

	@Override
	public double getFlightTotal() {
		return _flightTotal;
	}

	@Override
	public void setFlightTotal(double flightTotal) {
		_flightTotal = flightTotal;
	}

	@Override
	public double getFlightAirFare() {
		return _flightAirFare;
	}

	@Override
	public void setFlightAirFare(double flightAirFare) {
		_flightAirFare = flightAirFare;
	}

	@Override
	public double getFlightTaxes() {
		return _flightTaxes;
	}

	@Override
	public void setFlightTaxes(double flightTaxes) {
		_flightTaxes = flightTaxes;
	}

	@Override
	public double getFlightTransactionFee() {
		return _flightTransactionFee;
	}

	@Override
	public void setFlightTransactionFee(double flightTransactionFee) {
		_flightTransactionFee = flightTransactionFee;
	}

	@Override
	public double getTotalTravelExpenseRmb() {
		return _totalTravelExpenseRmb;
	}

	@Override
	public void setTotalTravelExpenseRmb(double totalTravelExpenseRmb) {
		_totalTravelExpenseRmb = totalTravelExpenseRmb;
	}

	@Override
	public double getTotalTravelExpenseEur() {
		return _totalTravelExpenseEur;
	}

	@Override
	public void setTotalTravelExpenseEur(double totalTravelExpenseEur) {
		_totalTravelExpenseEur = totalTravelExpenseEur;
	}

	@Override
	public double getCostListInlandTotalRmb() {
		return _costListInlandTotalRmb;
	}

	@Override
	public void setCostListInlandTotalRmb(double costListInlandTotalRmb) {
		_costListInlandTotalRmb = costListInlandTotalRmb;
	}

	@Override
	public double getCostListForeignTotalEur() {
		return _costListForeignTotalEur;
	}

	@Override
	public void setCostListForeignTotalEur(double costListForeignTotalEur) {
		_costListForeignTotalEur = costListForeignTotalEur;
	}

	@Override
	public double getCostListForeignTotalRmb() {
		return _costListForeignTotalRmb;
	}

	@Override
	public void setCostListForeignTotalRmb(double costListForeignTotalRmb) {
		_costListForeignTotalRmb = costListForeignTotalRmb;
	}

	@Override
	public String getRemark() {
		if (_remark == null) {
			return StringPool.BLANK;
		}
		else {
			return _remark;
		}
	}

	@Override
	public void setRemark(String remark) {
		_remark = remark;
	}

	@Override
	public boolean getIsPaybyRmb() {
		return _isPaybyRmb;
	}

	@Override
	public boolean isIsPaybyRmb() {
		return _isPaybyRmb;
	}

	@Override
	public void setIsPaybyRmb(boolean isPaybyRmb) {
		_isPaybyRmb = isPaybyRmb;
	}

	@Override
	public long getEvpId() {
		return _evpId;
	}

	@Override
	public void setEvpId(long evpId) {
		_evpId = evpId;
	}

	@Override
	public String getEvpName() {
		if (_evpName == null) {
			return StringPool.BLANK;
		}
		else {
			return _evpName;
		}
	}

	@Override
	public void setEvpName(String evpName) {
		_evpName = evpName;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (!_setOriginalStatus) {
			_setOriginalStatus = true;

			_originalStatus = _status;
		}

		_status = status;
	}

	public int getOriginalStatus() {
		return _originalStatus;
	}

	@Override
	public int getSapStatus() {
		return _sapStatus;
	}

	@Override
	public void setSapStatus(int sapStatus) {
		_sapStatus = sapStatus;
	}

	@Override
	public String getSapComments() {
		if (_sapComments == null) {
			return StringPool.BLANK;
		}
		else {
			return _sapComments;
		}
	}

	@Override
	public void setSapComments(String sapComments) {
		_sapComments = sapComments;
	}

	@Override
	public String getSapDocumentId() {
		if (_sapDocumentId == null) {
			return StringPool.BLANK;
		}
		else {
			return _sapDocumentId;
		}
	}

	@Override
	public void setSapDocumentId(String sapDocumentId) {
		_sapDocumentId = sapDocumentId;
	}

	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getStatusByUserId(), "uuid",
			_statusByUserUuid);
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
		_statusByUserUuid = statusByUserUuid;
	}

	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return StringPool.BLANK;
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@Override
	public boolean getIsApplicantAgent() {
		return _isApplicantAgent;
	}

	@Override
	public boolean isIsApplicantAgent() {
		return _isApplicantAgent;
	}

	@Override
	public void setIsApplicantAgent(boolean isApplicantAgent) {
		_isApplicantAgent = isApplicantAgent;
	}

	@Override
	public boolean getIsApproverAgent() {
		return _isApproverAgent;
	}

	@Override
	public boolean isIsApproverAgent() {
		return _isApproverAgent;
	}

	@Override
	public void setIsApproverAgent(boolean isApproverAgent) {
		_isApproverAgent = isApproverAgent;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public Date getSubmittedDate() {
		return _submittedDate;
	}

	@Override
	public void setSubmittedDate(Date submittedDate) {
		_submittedDate = submittedDate;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	/**
	 * @deprecated As of 6.1.0, replaced by {@link #isApproved}
	 */
	@Override
	public boolean getApproved() {
		return isApproved();
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			BusinessTripReimbursement.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public BusinessTripReimbursement toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (BusinessTripReimbursement)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BusinessTripReimbursementImpl businessTripReimbursementImpl = new BusinessTripReimbursementImpl();

		businessTripReimbursementImpl.setBusinessTripReimbursementId(getBusinessTripReimbursementId());
		businessTripReimbursementImpl.setTicketNo(getTicketNo());
		businessTripReimbursementImpl.setBussinessTirpTicketNo(getBussinessTirpTicketNo());
		businessTripReimbursementImpl.setProcessType(getProcessType());
		businessTripReimbursementImpl.setSubType(getSubType());
		businessTripReimbursementImpl.setPrintName(getPrintName());
		businessTripReimbursementImpl.setStaffCode(getStaffCode());
		businessTripReimbursementImpl.setCompanyName(getCompanyName());
		businessTripReimbursementImpl.setDivision(getDivision());
		businessTripReimbursementImpl.setDepartment(getDepartment());
		businessTripReimbursementImpl.setCostCenter(getCostCenter());
		businessTripReimbursementImpl.setPersonalID(getPersonalID());
		businessTripReimbursementImpl.setPassportNo(getPassportNo());
		businessTripReimbursementImpl.setOfficePhone(getOfficePhone());
		businessTripReimbursementImpl.setMobilePhone(getMobilePhone());
		businessTripReimbursementImpl.setEmail(getEmail());
		businessTripReimbursementImpl.setOfficeSite(getOfficeSite());
		businessTripReimbursementImpl.setApproverId(getApproverId());
		businessTripReimbursementImpl.setApproverName(getApproverName());
		businessTripReimbursementImpl.setIsCrossDepartment(getIsCrossDepartment());
		businessTripReimbursementImpl.setTargetDepartmentId(getTargetDepartmentId());
		businessTripReimbursementImpl.setTargetDepartmentName(getTargetDepartmentName());
		businessTripReimbursementImpl.setTargetCostCenter(getTargetCostCenter());
		businessTripReimbursementImpl.setTargetDepartmentApproverId(getTargetDepartmentApproverId());
		businessTripReimbursementImpl.setTargetDepartmentApproverName(getTargetDepartmentApproverName());
		businessTripReimbursementImpl.setTripType(getTripType());
		businessTripReimbursementImpl.setDepartureDate(getDepartureDate());
		businessTripReimbursementImpl.setReturnDate(getReturnDate());
		businessTripReimbursementImpl.setPurposeOfTheTrip(getPurposeOfTheTrip());
		businessTripReimbursementImpl.setVisitCountriesCities(getVisitCountriesCities());
		businessTripReimbursementImpl.setAdvancePayment(getAdvancePayment());
		businessTripReimbursementImpl.setCurrency(getCurrency());
		businessTripReimbursementImpl.setPaymentMethods(getPaymentMethods());
		businessTripReimbursementImpl.setTotalCostRmb(getTotalCostRmb());
		businessTripReimbursementImpl.setTotalCostEur(getTotalCostEur());
		businessTripReimbursementImpl.setOrgTotalCostRmb(getOrgTotalCostRmb());
		businessTripReimbursementImpl.setOrgTotalCostEur(getOrgTotalCostEur());
		businessTripReimbursementImpl.setHotelTotalCostRmb(getHotelTotalCostRmb());
		businessTripReimbursementImpl.setHotelTotalCostEur(getHotelTotalCostEur());
		businessTripReimbursementImpl.setCarRentalTotalCostRmb(getCarRentalTotalCostRmb());
		businessTripReimbursementImpl.setCarRentalTotalCostEur(getCarRentalTotalCostEur());
		businessTripReimbursementImpl.setFlightCurrency(getFlightCurrency());
		businessTripReimbursementImpl.setFlightTotal(getFlightTotal());
		businessTripReimbursementImpl.setFlightAirFare(getFlightAirFare());
		businessTripReimbursementImpl.setFlightTaxes(getFlightTaxes());
		businessTripReimbursementImpl.setFlightTransactionFee(getFlightTransactionFee());
		businessTripReimbursementImpl.setTotalTravelExpenseRmb(getTotalTravelExpenseRmb());
		businessTripReimbursementImpl.setTotalTravelExpenseEur(getTotalTravelExpenseEur());
		businessTripReimbursementImpl.setCostListInlandTotalRmb(getCostListInlandTotalRmb());
		businessTripReimbursementImpl.setCostListForeignTotalEur(getCostListForeignTotalEur());
		businessTripReimbursementImpl.setCostListForeignTotalRmb(getCostListForeignTotalRmb());
		businessTripReimbursementImpl.setRemark(getRemark());
		businessTripReimbursementImpl.setIsPaybyRmb(getIsPaybyRmb());
		businessTripReimbursementImpl.setEvpId(getEvpId());
		businessTripReimbursementImpl.setEvpName(getEvpName());
		businessTripReimbursementImpl.setStatus(getStatus());
		businessTripReimbursementImpl.setSapStatus(getSapStatus());
		businessTripReimbursementImpl.setSapComments(getSapComments());
		businessTripReimbursementImpl.setSapDocumentId(getSapDocumentId());
		businessTripReimbursementImpl.setStatusByUserId(getStatusByUserId());
		businessTripReimbursementImpl.setStatusByUserName(getStatusByUserName());
		businessTripReimbursementImpl.setStatusDate(getStatusDate());
		businessTripReimbursementImpl.setIsApplicantAgent(getIsApplicantAgent());
		businessTripReimbursementImpl.setIsApproverAgent(getIsApproverAgent());
		businessTripReimbursementImpl.setGroupId(getGroupId());
		businessTripReimbursementImpl.setUserId(getUserId());
		businessTripReimbursementImpl.setUserName(getUserName());
		businessTripReimbursementImpl.setCreateDate(getCreateDate());
		businessTripReimbursementImpl.setModifiedDate(getModifiedDate());
		businessTripReimbursementImpl.setSubmittedDate(getSubmittedDate());
		businessTripReimbursementImpl.setCompanyId(getCompanyId());

		businessTripReimbursementImpl.resetOriginalValues();

		return businessTripReimbursementImpl;
	}

	@Override
	public int compareTo(BusinessTripReimbursement businessTripReimbursement) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(),
				businessTripReimbursement.getCreateDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof BusinessTripReimbursement)) {
			return false;
		}

		BusinessTripReimbursement businessTripReimbursement = (BusinessTripReimbursement)obj;

		long primaryKey = businessTripReimbursement.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		BusinessTripReimbursementModelImpl businessTripReimbursementModelImpl = this;

		businessTripReimbursementModelImpl._originalTicketNo = businessTripReimbursementModelImpl._ticketNo;

		businessTripReimbursementModelImpl._originalBussinessTirpTicketNo = businessTripReimbursementModelImpl._bussinessTirpTicketNo;

		businessTripReimbursementModelImpl._originalStatus = businessTripReimbursementModelImpl._status;

		businessTripReimbursementModelImpl._setOriginalStatus = false;

		businessTripReimbursementModelImpl._originalUserId = businessTripReimbursementModelImpl._userId;

		businessTripReimbursementModelImpl._setOriginalUserId = false;

		businessTripReimbursementModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<BusinessTripReimbursement> toCacheModel() {
		BusinessTripReimbursementCacheModel businessTripReimbursementCacheModel = new BusinessTripReimbursementCacheModel();

		businessTripReimbursementCacheModel.businessTripReimbursementId = getBusinessTripReimbursementId();

		businessTripReimbursementCacheModel.ticketNo = getTicketNo();

		String ticketNo = businessTripReimbursementCacheModel.ticketNo;

		if ((ticketNo != null) && (ticketNo.length() == 0)) {
			businessTripReimbursementCacheModel.ticketNo = null;
		}

		businessTripReimbursementCacheModel.bussinessTirpTicketNo = getBussinessTirpTicketNo();

		String bussinessTirpTicketNo = businessTripReimbursementCacheModel.bussinessTirpTicketNo;

		if ((bussinessTirpTicketNo != null) &&
				(bussinessTirpTicketNo.length() == 0)) {
			businessTripReimbursementCacheModel.bussinessTirpTicketNo = null;
		}

		businessTripReimbursementCacheModel.processType = getProcessType();

		String processType = businessTripReimbursementCacheModel.processType;

		if ((processType != null) && (processType.length() == 0)) {
			businessTripReimbursementCacheModel.processType = null;
		}

		businessTripReimbursementCacheModel.subType = getSubType();

		String subType = businessTripReimbursementCacheModel.subType;

		if ((subType != null) && (subType.length() == 0)) {
			businessTripReimbursementCacheModel.subType = null;
		}

		businessTripReimbursementCacheModel.printName = getPrintName();

		String printName = businessTripReimbursementCacheModel.printName;

		if ((printName != null) && (printName.length() == 0)) {
			businessTripReimbursementCacheModel.printName = null;
		}

		businessTripReimbursementCacheModel.staffCode = getStaffCode();

		businessTripReimbursementCacheModel.companyName = getCompanyName();

		String companyName = businessTripReimbursementCacheModel.companyName;

		if ((companyName != null) && (companyName.length() == 0)) {
			businessTripReimbursementCacheModel.companyName = null;
		}

		businessTripReimbursementCacheModel.division = getDivision();

		String division = businessTripReimbursementCacheModel.division;

		if ((division != null) && (division.length() == 0)) {
			businessTripReimbursementCacheModel.division = null;
		}

		businessTripReimbursementCacheModel.department = getDepartment();

		String department = businessTripReimbursementCacheModel.department;

		if ((department != null) && (department.length() == 0)) {
			businessTripReimbursementCacheModel.department = null;
		}

		businessTripReimbursementCacheModel.costCenter = getCostCenter();

		String costCenter = businessTripReimbursementCacheModel.costCenter;

		if ((costCenter != null) && (costCenter.length() == 0)) {
			businessTripReimbursementCacheModel.costCenter = null;
		}

		businessTripReimbursementCacheModel.personalID = getPersonalID();

		String personalID = businessTripReimbursementCacheModel.personalID;

		if ((personalID != null) && (personalID.length() == 0)) {
			businessTripReimbursementCacheModel.personalID = null;
		}

		businessTripReimbursementCacheModel.passportNo = getPassportNo();

		String passportNo = businessTripReimbursementCacheModel.passportNo;

		if ((passportNo != null) && (passportNo.length() == 0)) {
			businessTripReimbursementCacheModel.passportNo = null;
		}

		businessTripReimbursementCacheModel.officePhone = getOfficePhone();

		String officePhone = businessTripReimbursementCacheModel.officePhone;

		if ((officePhone != null) && (officePhone.length() == 0)) {
			businessTripReimbursementCacheModel.officePhone = null;
		}

		businessTripReimbursementCacheModel.mobilePhone = getMobilePhone();

		String mobilePhone = businessTripReimbursementCacheModel.mobilePhone;

		if ((mobilePhone != null) && (mobilePhone.length() == 0)) {
			businessTripReimbursementCacheModel.mobilePhone = null;
		}

		businessTripReimbursementCacheModel.email = getEmail();

		String email = businessTripReimbursementCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			businessTripReimbursementCacheModel.email = null;
		}

		businessTripReimbursementCacheModel.officeSite = getOfficeSite();

		String officeSite = businessTripReimbursementCacheModel.officeSite;

		if ((officeSite != null) && (officeSite.length() == 0)) {
			businessTripReimbursementCacheModel.officeSite = null;
		}

		businessTripReimbursementCacheModel.approverId = getApproverId();

		businessTripReimbursementCacheModel.approverName = getApproverName();

		String approverName = businessTripReimbursementCacheModel.approverName;

		if ((approverName != null) && (approverName.length() == 0)) {
			businessTripReimbursementCacheModel.approverName = null;
		}

		businessTripReimbursementCacheModel.isCrossDepartment = getIsCrossDepartment();

		businessTripReimbursementCacheModel.targetDepartmentId = getTargetDepartmentId();

		businessTripReimbursementCacheModel.targetDepartmentName = getTargetDepartmentName();

		String targetDepartmentName = businessTripReimbursementCacheModel.targetDepartmentName;

		if ((targetDepartmentName != null) &&
				(targetDepartmentName.length() == 0)) {
			businessTripReimbursementCacheModel.targetDepartmentName = null;
		}

		businessTripReimbursementCacheModel.targetCostCenter = getTargetCostCenter();

		String targetCostCenter = businessTripReimbursementCacheModel.targetCostCenter;

		if ((targetCostCenter != null) && (targetCostCenter.length() == 0)) {
			businessTripReimbursementCacheModel.targetCostCenter = null;
		}

		businessTripReimbursementCacheModel.targetDepartmentApproverId = getTargetDepartmentApproverId();

		businessTripReimbursementCacheModel.targetDepartmentApproverName = getTargetDepartmentApproverName();

		String targetDepartmentApproverName = businessTripReimbursementCacheModel.targetDepartmentApproverName;

		if ((targetDepartmentApproverName != null) &&
				(targetDepartmentApproverName.length() == 0)) {
			businessTripReimbursementCacheModel.targetDepartmentApproverName = null;
		}

		businessTripReimbursementCacheModel.tripType = getTripType();

		Date departureDate = getDepartureDate();

		if (departureDate != null) {
			businessTripReimbursementCacheModel.departureDate = departureDate.getTime();
		}
		else {
			businessTripReimbursementCacheModel.departureDate = Long.MIN_VALUE;
		}

		Date returnDate = getReturnDate();

		if (returnDate != null) {
			businessTripReimbursementCacheModel.returnDate = returnDate.getTime();
		}
		else {
			businessTripReimbursementCacheModel.returnDate = Long.MIN_VALUE;
		}

		businessTripReimbursementCacheModel.purposeOfTheTrip = getPurposeOfTheTrip();

		String purposeOfTheTrip = businessTripReimbursementCacheModel.purposeOfTheTrip;

		if ((purposeOfTheTrip != null) && (purposeOfTheTrip.length() == 0)) {
			businessTripReimbursementCacheModel.purposeOfTheTrip = null;
		}

		businessTripReimbursementCacheModel.visitCountriesCities = getVisitCountriesCities();

		String visitCountriesCities = businessTripReimbursementCacheModel.visitCountriesCities;

		if ((visitCountriesCities != null) &&
				(visitCountriesCities.length() == 0)) {
			businessTripReimbursementCacheModel.visitCountriesCities = null;
		}

		businessTripReimbursementCacheModel.advancePayment = getAdvancePayment();

		businessTripReimbursementCacheModel.currency = getCurrency();

		String currency = businessTripReimbursementCacheModel.currency;

		if ((currency != null) && (currency.length() == 0)) {
			businessTripReimbursementCacheModel.currency = null;
		}

		businessTripReimbursementCacheModel.paymentMethods = getPaymentMethods();

		String paymentMethods = businessTripReimbursementCacheModel.paymentMethods;

		if ((paymentMethods != null) && (paymentMethods.length() == 0)) {
			businessTripReimbursementCacheModel.paymentMethods = null;
		}

		businessTripReimbursementCacheModel.totalCostRmb = getTotalCostRmb();

		businessTripReimbursementCacheModel.totalCostEur = getTotalCostEur();

		businessTripReimbursementCacheModel.orgTotalCostRmb = getOrgTotalCostRmb();

		businessTripReimbursementCacheModel.orgTotalCostEur = getOrgTotalCostEur();

		businessTripReimbursementCacheModel.hotelTotalCostRmb = getHotelTotalCostRmb();

		businessTripReimbursementCacheModel.hotelTotalCostEur = getHotelTotalCostEur();

		businessTripReimbursementCacheModel.carRentalTotalCostRmb = getCarRentalTotalCostRmb();

		businessTripReimbursementCacheModel.carRentalTotalCostEur = getCarRentalTotalCostEur();

		businessTripReimbursementCacheModel.flightCurrency = getFlightCurrency();

		String flightCurrency = businessTripReimbursementCacheModel.flightCurrency;

		if ((flightCurrency != null) && (flightCurrency.length() == 0)) {
			businessTripReimbursementCacheModel.flightCurrency = null;
		}

		businessTripReimbursementCacheModel.flightTotal = getFlightTotal();

		businessTripReimbursementCacheModel.flightAirFare = getFlightAirFare();

		businessTripReimbursementCacheModel.flightTaxes = getFlightTaxes();

		businessTripReimbursementCacheModel.flightTransactionFee = getFlightTransactionFee();

		businessTripReimbursementCacheModel.totalTravelExpenseRmb = getTotalTravelExpenseRmb();

		businessTripReimbursementCacheModel.totalTravelExpenseEur = getTotalTravelExpenseEur();

		businessTripReimbursementCacheModel.costListInlandTotalRmb = getCostListInlandTotalRmb();

		businessTripReimbursementCacheModel.costListForeignTotalEur = getCostListForeignTotalEur();

		businessTripReimbursementCacheModel.costListForeignTotalRmb = getCostListForeignTotalRmb();

		businessTripReimbursementCacheModel.remark = getRemark();

		String remark = businessTripReimbursementCacheModel.remark;

		if ((remark != null) && (remark.length() == 0)) {
			businessTripReimbursementCacheModel.remark = null;
		}

		businessTripReimbursementCacheModel.isPaybyRmb = getIsPaybyRmb();

		businessTripReimbursementCacheModel.evpId = getEvpId();

		businessTripReimbursementCacheModel.evpName = getEvpName();

		String evpName = businessTripReimbursementCacheModel.evpName;

		if ((evpName != null) && (evpName.length() == 0)) {
			businessTripReimbursementCacheModel.evpName = null;
		}

		businessTripReimbursementCacheModel.status = getStatus();

		businessTripReimbursementCacheModel.sapStatus = getSapStatus();

		businessTripReimbursementCacheModel.sapComments = getSapComments();

		String sapComments = businessTripReimbursementCacheModel.sapComments;

		if ((sapComments != null) && (sapComments.length() == 0)) {
			businessTripReimbursementCacheModel.sapComments = null;
		}

		businessTripReimbursementCacheModel.sapDocumentId = getSapDocumentId();

		String sapDocumentId = businessTripReimbursementCacheModel.sapDocumentId;

		if ((sapDocumentId != null) && (sapDocumentId.length() == 0)) {
			businessTripReimbursementCacheModel.sapDocumentId = null;
		}

		businessTripReimbursementCacheModel.statusByUserId = getStatusByUserId();

		businessTripReimbursementCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = businessTripReimbursementCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			businessTripReimbursementCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			businessTripReimbursementCacheModel.statusDate = statusDate.getTime();
		}
		else {
			businessTripReimbursementCacheModel.statusDate = Long.MIN_VALUE;
		}

		businessTripReimbursementCacheModel.isApplicantAgent = getIsApplicantAgent();

		businessTripReimbursementCacheModel.isApproverAgent = getIsApproverAgent();

		businessTripReimbursementCacheModel.groupId = getGroupId();

		businessTripReimbursementCacheModel.userId = getUserId();

		businessTripReimbursementCacheModel.userName = getUserName();

		String userName = businessTripReimbursementCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			businessTripReimbursementCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			businessTripReimbursementCacheModel.createDate = createDate.getTime();
		}
		else {
			businessTripReimbursementCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			businessTripReimbursementCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			businessTripReimbursementCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		Date submittedDate = getSubmittedDate();

		if (submittedDate != null) {
			businessTripReimbursementCacheModel.submittedDate = submittedDate.getTime();
		}
		else {
			businessTripReimbursementCacheModel.submittedDate = Long.MIN_VALUE;
		}

		businessTripReimbursementCacheModel.companyId = getCompanyId();

		return businessTripReimbursementCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(143);

		sb.append("{businessTripReimbursementId=");
		sb.append(getBusinessTripReimbursementId());
		sb.append(", ticketNo=");
		sb.append(getTicketNo());
		sb.append(", bussinessTirpTicketNo=");
		sb.append(getBussinessTirpTicketNo());
		sb.append(", processType=");
		sb.append(getProcessType());
		sb.append(", subType=");
		sb.append(getSubType());
		sb.append(", printName=");
		sb.append(getPrintName());
		sb.append(", staffCode=");
		sb.append(getStaffCode());
		sb.append(", companyName=");
		sb.append(getCompanyName());
		sb.append(", division=");
		sb.append(getDivision());
		sb.append(", department=");
		sb.append(getDepartment());
		sb.append(", costCenter=");
		sb.append(getCostCenter());
		sb.append(", personalID=");
		sb.append(getPersonalID());
		sb.append(", passportNo=");
		sb.append(getPassportNo());
		sb.append(", officePhone=");
		sb.append(getOfficePhone());
		sb.append(", mobilePhone=");
		sb.append(getMobilePhone());
		sb.append(", email=");
		sb.append(getEmail());
		sb.append(", officeSite=");
		sb.append(getOfficeSite());
		sb.append(", approverId=");
		sb.append(getApproverId());
		sb.append(", approverName=");
		sb.append(getApproverName());
		sb.append(", isCrossDepartment=");
		sb.append(getIsCrossDepartment());
		sb.append(", targetDepartmentId=");
		sb.append(getTargetDepartmentId());
		sb.append(", targetDepartmentName=");
		sb.append(getTargetDepartmentName());
		sb.append(", targetCostCenter=");
		sb.append(getTargetCostCenter());
		sb.append(", targetDepartmentApproverId=");
		sb.append(getTargetDepartmentApproverId());
		sb.append(", targetDepartmentApproverName=");
		sb.append(getTargetDepartmentApproverName());
		sb.append(", tripType=");
		sb.append(getTripType());
		sb.append(", departureDate=");
		sb.append(getDepartureDate());
		sb.append(", returnDate=");
		sb.append(getReturnDate());
		sb.append(", purposeOfTheTrip=");
		sb.append(getPurposeOfTheTrip());
		sb.append(", visitCountriesCities=");
		sb.append(getVisitCountriesCities());
		sb.append(", advancePayment=");
		sb.append(getAdvancePayment());
		sb.append(", currency=");
		sb.append(getCurrency());
		sb.append(", paymentMethods=");
		sb.append(getPaymentMethods());
		sb.append(", totalCostRmb=");
		sb.append(getTotalCostRmb());
		sb.append(", totalCostEur=");
		sb.append(getTotalCostEur());
		sb.append(", orgTotalCostRmb=");
		sb.append(getOrgTotalCostRmb());
		sb.append(", orgTotalCostEur=");
		sb.append(getOrgTotalCostEur());
		sb.append(", hotelTotalCostRmb=");
		sb.append(getHotelTotalCostRmb());
		sb.append(", hotelTotalCostEur=");
		sb.append(getHotelTotalCostEur());
		sb.append(", carRentalTotalCostRmb=");
		sb.append(getCarRentalTotalCostRmb());
		sb.append(", carRentalTotalCostEur=");
		sb.append(getCarRentalTotalCostEur());
		sb.append(", flightCurrency=");
		sb.append(getFlightCurrency());
		sb.append(", flightTotal=");
		sb.append(getFlightTotal());
		sb.append(", flightAirFare=");
		sb.append(getFlightAirFare());
		sb.append(", flightTaxes=");
		sb.append(getFlightTaxes());
		sb.append(", flightTransactionFee=");
		sb.append(getFlightTransactionFee());
		sb.append(", totalTravelExpenseRmb=");
		sb.append(getTotalTravelExpenseRmb());
		sb.append(", totalTravelExpenseEur=");
		sb.append(getTotalTravelExpenseEur());
		sb.append(", costListInlandTotalRmb=");
		sb.append(getCostListInlandTotalRmb());
		sb.append(", costListForeignTotalEur=");
		sb.append(getCostListForeignTotalEur());
		sb.append(", costListForeignTotalRmb=");
		sb.append(getCostListForeignTotalRmb());
		sb.append(", remark=");
		sb.append(getRemark());
		sb.append(", isPaybyRmb=");
		sb.append(getIsPaybyRmb());
		sb.append(", evpId=");
		sb.append(getEvpId());
		sb.append(", evpName=");
		sb.append(getEvpName());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", sapStatus=");
		sb.append(getSapStatus());
		sb.append(", sapComments=");
		sb.append(getSapComments());
		sb.append(", sapDocumentId=");
		sb.append(getSapDocumentId());
		sb.append(", statusByUserId=");
		sb.append(getStatusByUserId());
		sb.append(", statusByUserName=");
		sb.append(getStatusByUserName());
		sb.append(", statusDate=");
		sb.append(getStatusDate());
		sb.append(", isApplicantAgent=");
		sb.append(getIsApplicantAgent());
		sb.append(", isApproverAgent=");
		sb.append(getIsApproverAgent());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", submittedDate=");
		sb.append(getSubmittedDate());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(217);

		sb.append("<model><model-name>");
		sb.append("com.business.trip.model.BusinessTripReimbursement");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>businessTripReimbursementId</column-name><column-value><![CDATA[");
		sb.append(getBusinessTripReimbursementId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ticketNo</column-name><column-value><![CDATA[");
		sb.append(getTicketNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>bussinessTirpTicketNo</column-name><column-value><![CDATA[");
		sb.append(getBussinessTirpTicketNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>processType</column-name><column-value><![CDATA[");
		sb.append(getProcessType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>subType</column-name><column-value><![CDATA[");
		sb.append(getSubType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>printName</column-name><column-value><![CDATA[");
		sb.append(getPrintName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>staffCode</column-name><column-value><![CDATA[");
		sb.append(getStaffCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyName</column-name><column-value><![CDATA[");
		sb.append(getCompanyName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>division</column-name><column-value><![CDATA[");
		sb.append(getDivision());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>department</column-name><column-value><![CDATA[");
		sb.append(getDepartment());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>costCenter</column-name><column-value><![CDATA[");
		sb.append(getCostCenter());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>personalID</column-name><column-value><![CDATA[");
		sb.append(getPersonalID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>passportNo</column-name><column-value><![CDATA[");
		sb.append(getPassportNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>officePhone</column-name><column-value><![CDATA[");
		sb.append(getOfficePhone());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mobilePhone</column-name><column-value><![CDATA[");
		sb.append(getMobilePhone());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>email</column-name><column-value><![CDATA[");
		sb.append(getEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>officeSite</column-name><column-value><![CDATA[");
		sb.append(getOfficeSite());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>approverId</column-name><column-value><![CDATA[");
		sb.append(getApproverId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>approverName</column-name><column-value><![CDATA[");
		sb.append(getApproverName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isCrossDepartment</column-name><column-value><![CDATA[");
		sb.append(getIsCrossDepartment());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>targetDepartmentId</column-name><column-value><![CDATA[");
		sb.append(getTargetDepartmentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>targetDepartmentName</column-name><column-value><![CDATA[");
		sb.append(getTargetDepartmentName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>targetCostCenter</column-name><column-value><![CDATA[");
		sb.append(getTargetCostCenter());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>targetDepartmentApproverId</column-name><column-value><![CDATA[");
		sb.append(getTargetDepartmentApproverId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>targetDepartmentApproverName</column-name><column-value><![CDATA[");
		sb.append(getTargetDepartmentApproverName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tripType</column-name><column-value><![CDATA[");
		sb.append(getTripType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>departureDate</column-name><column-value><![CDATA[");
		sb.append(getDepartureDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>returnDate</column-name><column-value><![CDATA[");
		sb.append(getReturnDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>purposeOfTheTrip</column-name><column-value><![CDATA[");
		sb.append(getPurposeOfTheTrip());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>visitCountriesCities</column-name><column-value><![CDATA[");
		sb.append(getVisitCountriesCities());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>advancePayment</column-name><column-value><![CDATA[");
		sb.append(getAdvancePayment());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>currency</column-name><column-value><![CDATA[");
		sb.append(getCurrency());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>paymentMethods</column-name><column-value><![CDATA[");
		sb.append(getPaymentMethods());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>totalCostRmb</column-name><column-value><![CDATA[");
		sb.append(getTotalCostRmb());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>totalCostEur</column-name><column-value><![CDATA[");
		sb.append(getTotalCostEur());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>orgTotalCostRmb</column-name><column-value><![CDATA[");
		sb.append(getOrgTotalCostRmb());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>orgTotalCostEur</column-name><column-value><![CDATA[");
		sb.append(getOrgTotalCostEur());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hotelTotalCostRmb</column-name><column-value><![CDATA[");
		sb.append(getHotelTotalCostRmb());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hotelTotalCostEur</column-name><column-value><![CDATA[");
		sb.append(getHotelTotalCostEur());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>carRentalTotalCostRmb</column-name><column-value><![CDATA[");
		sb.append(getCarRentalTotalCostRmb());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>carRentalTotalCostEur</column-name><column-value><![CDATA[");
		sb.append(getCarRentalTotalCostEur());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>flightCurrency</column-name><column-value><![CDATA[");
		sb.append(getFlightCurrency());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>flightTotal</column-name><column-value><![CDATA[");
		sb.append(getFlightTotal());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>flightAirFare</column-name><column-value><![CDATA[");
		sb.append(getFlightAirFare());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>flightTaxes</column-name><column-value><![CDATA[");
		sb.append(getFlightTaxes());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>flightTransactionFee</column-name><column-value><![CDATA[");
		sb.append(getFlightTransactionFee());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>totalTravelExpenseRmb</column-name><column-value><![CDATA[");
		sb.append(getTotalTravelExpenseRmb());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>totalTravelExpenseEur</column-name><column-value><![CDATA[");
		sb.append(getTotalTravelExpenseEur());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>costListInlandTotalRmb</column-name><column-value><![CDATA[");
		sb.append(getCostListInlandTotalRmb());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>costListForeignTotalEur</column-name><column-value><![CDATA[");
		sb.append(getCostListForeignTotalEur());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>costListForeignTotalRmb</column-name><column-value><![CDATA[");
		sb.append(getCostListForeignTotalRmb());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>remark</column-name><column-value><![CDATA[");
		sb.append(getRemark());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isPaybyRmb</column-name><column-value><![CDATA[");
		sb.append(getIsPaybyRmb());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>evpId</column-name><column-value><![CDATA[");
		sb.append(getEvpId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>evpName</column-name><column-value><![CDATA[");
		sb.append(getEvpName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sapStatus</column-name><column-value><![CDATA[");
		sb.append(getSapStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sapComments</column-name><column-value><![CDATA[");
		sb.append(getSapComments());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sapDocumentId</column-name><column-value><![CDATA[");
		sb.append(getSapDocumentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserId</column-name><column-value><![CDATA[");
		sb.append(getStatusByUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserName</column-name><column-value><![CDATA[");
		sb.append(getStatusByUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusDate</column-name><column-value><![CDATA[");
		sb.append(getStatusDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isApplicantAgent</column-name><column-value><![CDATA[");
		sb.append(getIsApplicantAgent());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isApproverAgent</column-name><column-value><![CDATA[");
		sb.append(getIsApproverAgent());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>submittedDate</column-name><column-value><![CDATA[");
		sb.append(getSubmittedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = BusinessTripReimbursement.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			BusinessTripReimbursement.class
		};
	private long _businessTripReimbursementId;
	private String _ticketNo;
	private String _originalTicketNo;
	private String _bussinessTirpTicketNo;
	private String _originalBussinessTirpTicketNo;
	private String _processType;
	private String _subType;
	private String _printName;
	private long _staffCode;
	private String _companyName;
	private String _division;
	private String _department;
	private String _costCenter;
	private String _personalID;
	private String _passportNo;
	private String _officePhone;
	private String _mobilePhone;
	private String _email;
	private String _officeSite;
	private long _approverId;
	private String _approverName;
	private boolean _isCrossDepartment;
	private long _targetDepartmentId;
	private String _targetDepartmentName;
	private String _targetCostCenter;
	private long _targetDepartmentApproverId;
	private String _targetDepartmentApproverName;
	private int _tripType;
	private Date _departureDate;
	private Date _returnDate;
	private String _purposeOfTheTrip;
	private String _visitCountriesCities;
	private double _advancePayment;
	private String _currency;
	private String _paymentMethods;
	private double _totalCostRmb;
	private double _totalCostEur;
	private double _orgTotalCostRmb;
	private double _orgTotalCostEur;
	private double _hotelTotalCostRmb;
	private double _hotelTotalCostEur;
	private double _carRentalTotalCostRmb;
	private double _carRentalTotalCostEur;
	private String _flightCurrency;
	private double _flightTotal;
	private double _flightAirFare;
	private double _flightTaxes;
	private double _flightTransactionFee;
	private double _totalTravelExpenseRmb;
	private double _totalTravelExpenseEur;
	private double _costListInlandTotalRmb;
	private double _costListForeignTotalEur;
	private double _costListForeignTotalRmb;
	private String _remark;
	private boolean _isPaybyRmb;
	private long _evpId;
	private String _evpName;
	private int _status;
	private int _originalStatus;
	private boolean _setOriginalStatus;
	private int _sapStatus;
	private String _sapComments;
	private String _sapDocumentId;
	private long _statusByUserId;
	private String _statusByUserUuid;
	private String _statusByUserName;
	private Date _statusDate;
	private boolean _isApplicantAgent;
	private boolean _isApproverAgent;
	private long _groupId;
	private long _userId;
	private String _userUuid;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private Date _submittedDate;
	private long _companyId;
	private long _columnBitmask;
	private BusinessTripReimbursement _escapedModel;
}