/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.business.trip.model.impl;

import com.business.trip.model.BusinessTripReimbursement;
import com.business.trip.service.BusinessTripReimbursementLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the BusinessTripReimbursement service. Represents a row in the &quot;VgcApon_BtReimbursement&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BusinessTripReimbursementImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BusinessTripReimbursementImpl
 * @see com.business.trip.model.BusinessTripReimbursement
 * @generated
 */
public abstract class BusinessTripReimbursementBaseImpl
	extends BusinessTripReimbursementModelImpl
	implements BusinessTripReimbursement {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a business trip reimbursement model instance should use the {@link BusinessTripReimbursement} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			BusinessTripReimbursementLocalServiceUtil.addBusinessTripReimbursement(this);
		}
		else {
			BusinessTripReimbursementLocalServiceUtil.updateBusinessTripReimbursement(this);
		}
	}
}