/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.e.closing.model.impl;

import com.e.closing.model.EClosing;
import com.e.closing.model.EClosingModel;
import com.e.closing.model.EClosingSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.workflow.WorkflowConstants;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the EClosing service. Represents a row in the &quot;vgcapon_EClosing&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.e.closing.model.EClosingModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EClosingImpl}.
 * </p>
 *
 * @author t.a.jiang
 * @see EClosingImpl
 * @see com.e.closing.model.EClosing
 * @see com.e.closing.model.EClosingModel
 * @generated
 */
@JSON(strict = true)
public class EClosingModelImpl extends BaseModelImpl<EClosing>
	implements EClosingModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a e closing model instance should use the {@link com.e.closing.model.EClosing} interface instead.
	 */
	public static final String TABLE_NAME = "vgcapon_EClosing";
	public static final Object[][] TABLE_COLUMNS = {
			{ "eclosingId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "ticketNo", Types.VARCHAR },
			{ "staffCode", Types.INTEGER },
			{ "staffName", Types.VARCHAR },
			{ "company", Types.VARCHAR },
			{ "division", Types.VARCHAR },
			{ "department", Types.VARCHAR },
			{ "costCenter", Types.VARCHAR },
			{ "functionName", Types.VARCHAR },
			{ "positionCode", Types.VARCHAR },
			{ "employeeGroupId", Types.VARCHAR },
			{ "employeeGroupName", Types.VARCHAR },
			{ "privateEmailAddress", Types.VARCHAR },
			{ "startingDate", Types.TIMESTAMP },
			{ "lastWorkingDay", Types.TIMESTAMP },
			{ "finishContractDate", Types.TIMESTAMP },
			{ "seatOfficeNumber", Types.VARCHAR },
			{ "permanentAddress", Types.VARCHAR },
			{ "dmOption1", Types.BOOLEAN },
			{ "dmOption2", Types.BOOLEAN },
			{ "dmStatus", Types.VARCHAR },
			{ "dmComments", Types.VARCHAR },
			{ "adOption1", Types.BOOLEAN },
			{ "adOption2", Types.BOOLEAN },
			{ "adOption3", Types.BOOLEAN },
			{ "adOption4", Types.BOOLEAN },
			{ "adFinanceFee", Types.DOUBLE },
			{ "adStatus", Types.VARCHAR },
			{ "adComments", Types.VARCHAR },
			{ "fsOption1", Types.BOOLEAN },
			{ "fsStatus", Types.VARCHAR },
			{ "fsComments", Types.VARCHAR },
			{ "flcOption1", Types.BOOLEAN },
			{ "flcOption2", Types.BOOLEAN },
			{ "flcStatus", Types.VARCHAR },
			{ "flcComments", Types.VARCHAR },
			{ "securityOption1", Types.BOOLEAN },
			{ "securityFinanceFee", Types.DOUBLE },
			{ "securityStatus", Types.VARCHAR },
			{ "securityComments", Types.VARCHAR },
			{ "idOption1", Types.BOOLEAN },
			{ "idOption2", Types.BOOLEAN },
			{ "idOption3", Types.BOOLEAN },
			{ "idOption4", Types.BOOLEAN },
			{ "idOption5", Types.BOOLEAN },
			{ "idOption6", Types.BOOLEAN },
			{ "idOption7", Types.BOOLEAN },
			{ "idOption8", Types.BOOLEAN },
			{ "idOption9", Types.BOOLEAN },
			{ "idHrFee", Types.DOUBLE },
			{ "idFinanceFee", Types.DOUBLE },
			{ "idStatus", Types.VARCHAR },
			{ "idComments", Types.VARCHAR },
			{ "htdOption1", Types.BOOLEAN },
			{ "htdHrFee", Types.DOUBLE },
			{ "htdFinanceFee", Types.DOUBLE },
			{ "htdStatus", Types.VARCHAR },
			{ "htdComments", Types.VARCHAR },
			{ "hdOption1", Types.BOOLEAN },
			{ "hdOption2", Types.BOOLEAN },
			{ "hdOption2Text", Types.VARCHAR },
			{ "hdOption3", Types.BOOLEAN },
			{ "hdOption3Money", Types.DOUBLE },
			{ "hdOption4", Types.BOOLEAN },
			{ "hdOption4Money", Types.DOUBLE },
			{ "hdStatus", Types.VARCHAR },
			{ "hdComments", Types.VARCHAR },
			{ "hdleaveText", Types.VARCHAR },
			{ "fdOption1", Types.BOOLEAN },
			{ "fdOption2", Types.BOOLEAN },
			{ "fdOption3", Types.BOOLEAN },
			{ "fdOption4", Types.BOOLEAN },
			{ "fdOption4Text", Types.VARCHAR },
			{ "fdStatus", Types.VARCHAR },
			{ "fdComments", Types.VARCHAR },
			{ "applicantAgent", Types.BOOLEAN },
			{ "approverAgent", Types.BOOLEAN },
			{ "processType", Types.VARCHAR },
			{ "subProcessType", Types.VARCHAR },
			{ "status", Types.INTEGER },
			{ "statusByUserId", Types.BIGINT },
			{ "statusByUserName", Types.VARCHAR },
			{ "statusDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table vgcapon_EClosing (eclosingId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,ticketNo VARCHAR(75) null,staffCode INTEGER,staffName VARCHAR(75) null,company VARCHAR(75) null,division VARCHAR(75) null,department VARCHAR(75) null,costCenter VARCHAR(75) null,functionName VARCHAR(75) null,positionCode VARCHAR(75) null,employeeGroupId VARCHAR(75) null,employeeGroupName VARCHAR(75) null,privateEmailAddress VARCHAR(75) null,startingDate DATE null,lastWorkingDay DATE null,finishContractDate DATE null,seatOfficeNumber VARCHAR(75) null,permanentAddress VARCHAR(75) null,dmOption1 BOOLEAN,dmOption2 BOOLEAN,dmStatus VARCHAR(75) null,dmComments VARCHAR(500) null,adOption1 BOOLEAN,adOption2 BOOLEAN,adOption3 BOOLEAN,adOption4 BOOLEAN,adFinanceFee DOUBLE,adStatus VARCHAR(75) null,adComments VARCHAR(500) null,fsOption1 BOOLEAN,fsStatus VARCHAR(75) null,fsComments VARCHAR(500) null,flcOption1 BOOLEAN,flcOption2 BOOLEAN,flcStatus VARCHAR(75) null,flcComments VARCHAR(500) null,securityOption1 BOOLEAN,securityFinanceFee DOUBLE,securityStatus VARCHAR(75) null,securityComments VARCHAR(500) null,idOption1 BOOLEAN,idOption2 BOOLEAN,idOption3 BOOLEAN,idOption4 BOOLEAN,idOption5 BOOLEAN,idOption6 BOOLEAN,idOption7 BOOLEAN,idOption8 BOOLEAN,idOption9 BOOLEAN,idHrFee DOUBLE,idFinanceFee DOUBLE,idStatus VARCHAR(75) null,idComments VARCHAR(500) null,htdOption1 BOOLEAN,htdHrFee DOUBLE,htdFinanceFee DOUBLE,htdStatus VARCHAR(75) null,htdComments VARCHAR(500) null,hdOption1 BOOLEAN,hdOption2 BOOLEAN,hdOption2Text VARCHAR(75) null,hdOption3 BOOLEAN,hdOption3Money DOUBLE,hdOption4 BOOLEAN,hdOption4Money DOUBLE,hdStatus VARCHAR(75) null,hdComments VARCHAR(500) null,hdleaveText VARCHAR(75) null,fdOption1 BOOLEAN,fdOption2 BOOLEAN,fdOption3 BOOLEAN,fdOption4 BOOLEAN,fdOption4Text VARCHAR(75) null,fdStatus VARCHAR(75) null,fdComments VARCHAR(500) null,applicantAgent BOOLEAN,approverAgent BOOLEAN,processType VARCHAR(75) null,subProcessType VARCHAR(75) null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table vgcapon_EClosing";
	public static final String ORDER_BY_JPQL = " ORDER BY eClosing.eclosingId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY vgcapon_EClosing.eclosingId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.e.closing.model.EClosing"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.e.closing.model.EClosing"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.e.closing.model.EClosing"),
			true);
	public static long STATUS_COLUMN_BITMASK = 1L;
	public static long USERID_COLUMN_BITMASK = 2L;
	public static long ECLOSINGID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static EClosing toModel(EClosingSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		EClosing model = new EClosingImpl();

		model.setEclosingId(soapModel.getEclosingId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setTicketNo(soapModel.getTicketNo());
		model.setStaffCode(soapModel.getStaffCode());
		model.setStaffName(soapModel.getStaffName());
		model.setCompany(soapModel.getCompany());
		model.setDivision(soapModel.getDivision());
		model.setDepartment(soapModel.getDepartment());
		model.setCostCenter(soapModel.getCostCenter());
		model.setFunctionName(soapModel.getFunctionName());
		model.setPositionCode(soapModel.getPositionCode());
		model.setEmployeeGroupId(soapModel.getEmployeeGroupId());
		model.setEmployeeGroupName(soapModel.getEmployeeGroupName());
		model.setPrivateEmailAddress(soapModel.getPrivateEmailAddress());
		model.setStartingDate(soapModel.getStartingDate());
		model.setLastWorkingDay(soapModel.getLastWorkingDay());
		model.setFinishContractDate(soapModel.getFinishContractDate());
		model.setSeatOfficeNumber(soapModel.getSeatOfficeNumber());
		model.setPermanentAddress(soapModel.getPermanentAddress());
		model.setDmOption1(soapModel.getDmOption1());
		model.setDmOption2(soapModel.getDmOption2());
		model.setDmStatus(soapModel.getDmStatus());
		model.setDmComments(soapModel.getDmComments());
		model.setAdOption1(soapModel.getAdOption1());
		model.setAdOption2(soapModel.getAdOption2());
		model.setAdOption3(soapModel.getAdOption3());
		model.setAdOption4(soapModel.getAdOption4());
		model.setAdFinanceFee(soapModel.getAdFinanceFee());
		model.setAdStatus(soapModel.getAdStatus());
		model.setAdComments(soapModel.getAdComments());
		model.setFsOption1(soapModel.getFsOption1());
		model.setFsStatus(soapModel.getFsStatus());
		model.setFsComments(soapModel.getFsComments());
		model.setFlcOption1(soapModel.getFlcOption1());
		model.setFlcOption2(soapModel.getFlcOption2());
		model.setFlcStatus(soapModel.getFlcStatus());
		model.setFlcComments(soapModel.getFlcComments());
		model.setSecurityOption1(soapModel.getSecurityOption1());
		model.setSecurityFinanceFee(soapModel.getSecurityFinanceFee());
		model.setSecurityStatus(soapModel.getSecurityStatus());
		model.setSecurityComments(soapModel.getSecurityComments());
		model.setIdOption1(soapModel.getIdOption1());
		model.setIdOption2(soapModel.getIdOption2());
		model.setIdOption3(soapModel.getIdOption3());
		model.setIdOption4(soapModel.getIdOption4());
		model.setIdOption5(soapModel.getIdOption5());
		model.setIdOption6(soapModel.getIdOption6());
		model.setIdOption7(soapModel.getIdOption7());
		model.setIdOption8(soapModel.getIdOption8());
		model.setIdOption9(soapModel.getIdOption9());
		model.setIdHrFee(soapModel.getIdHrFee());
		model.setIdFinanceFee(soapModel.getIdFinanceFee());
		model.setIdStatus(soapModel.getIdStatus());
		model.setIdComments(soapModel.getIdComments());
		model.setHtdOption1(soapModel.getHtdOption1());
		model.setHtdHrFee(soapModel.getHtdHrFee());
		model.setHtdFinanceFee(soapModel.getHtdFinanceFee());
		model.setHtdStatus(soapModel.getHtdStatus());
		model.setHtdComments(soapModel.getHtdComments());
		model.setHdOption1(soapModel.getHdOption1());
		model.setHdOption2(soapModel.getHdOption2());
		model.setHdOption2Text(soapModel.getHdOption2Text());
		model.setHdOption3(soapModel.getHdOption3());
		model.setHdOption3Money(soapModel.getHdOption3Money());
		model.setHdOption4(soapModel.getHdOption4());
		model.setHdOption4Money(soapModel.getHdOption4Money());
		model.setHdStatus(soapModel.getHdStatus());
		model.setHdComments(soapModel.getHdComments());
		model.setHdleaveText(soapModel.getHdleaveText());
		model.setFdOption1(soapModel.getFdOption1());
		model.setFdOption2(soapModel.getFdOption2());
		model.setFdOption3(soapModel.getFdOption3());
		model.setFdOption4(soapModel.getFdOption4());
		model.setFdOption4Text(soapModel.getFdOption4Text());
		model.setFdStatus(soapModel.getFdStatus());
		model.setFdComments(soapModel.getFdComments());
		model.setApplicantAgent(soapModel.getApplicantAgent());
		model.setApproverAgent(soapModel.getApproverAgent());
		model.setProcessType(soapModel.getProcessType());
		model.setSubProcessType(soapModel.getSubProcessType());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<EClosing> toModels(EClosingSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<EClosing> models = new ArrayList<EClosing>(soapModels.length);

		for (EClosingSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.e.closing.model.EClosing"));

	public EClosingModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _eclosingId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEclosingId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _eclosingId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EClosing.class;
	}

	@Override
	public String getModelClassName() {
		return EClosing.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("eclosingId", getEclosingId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("ticketNo", getTicketNo());
		attributes.put("staffCode", getStaffCode());
		attributes.put("staffName", getStaffName());
		attributes.put("company", getCompany());
		attributes.put("division", getDivision());
		attributes.put("department", getDepartment());
		attributes.put("costCenter", getCostCenter());
		attributes.put("functionName", getFunctionName());
		attributes.put("positionCode", getPositionCode());
		attributes.put("employeeGroupId", getEmployeeGroupId());
		attributes.put("employeeGroupName", getEmployeeGroupName());
		attributes.put("privateEmailAddress", getPrivateEmailAddress());
		attributes.put("startingDate", getStartingDate());
		attributes.put("lastWorkingDay", getLastWorkingDay());
		attributes.put("finishContractDate", getFinishContractDate());
		attributes.put("seatOfficeNumber", getSeatOfficeNumber());
		attributes.put("permanentAddress", getPermanentAddress());
		attributes.put("dmOption1", getDmOption1());
		attributes.put("dmOption2", getDmOption2());
		attributes.put("dmStatus", getDmStatus());
		attributes.put("dmComments", getDmComments());
		attributes.put("adOption1", getAdOption1());
		attributes.put("adOption2", getAdOption2());
		attributes.put("adOption3", getAdOption3());
		attributes.put("adOption4", getAdOption4());
		attributes.put("adFinanceFee", getAdFinanceFee());
		attributes.put("adStatus", getAdStatus());
		attributes.put("adComments", getAdComments());
		attributes.put("fsOption1", getFsOption1());
		attributes.put("fsStatus", getFsStatus());
		attributes.put("fsComments", getFsComments());
		attributes.put("flcOption1", getFlcOption1());
		attributes.put("flcOption2", getFlcOption2());
		attributes.put("flcStatus", getFlcStatus());
		attributes.put("flcComments", getFlcComments());
		attributes.put("securityOption1", getSecurityOption1());
		attributes.put("securityFinanceFee", getSecurityFinanceFee());
		attributes.put("securityStatus", getSecurityStatus());
		attributes.put("securityComments", getSecurityComments());
		attributes.put("idOption1", getIdOption1());
		attributes.put("idOption2", getIdOption2());
		attributes.put("idOption3", getIdOption3());
		attributes.put("idOption4", getIdOption4());
		attributes.put("idOption5", getIdOption5());
		attributes.put("idOption6", getIdOption6());
		attributes.put("idOption7", getIdOption7());
		attributes.put("idOption8", getIdOption8());
		attributes.put("idOption9", getIdOption9());
		attributes.put("idHrFee", getIdHrFee());
		attributes.put("idFinanceFee", getIdFinanceFee());
		attributes.put("idStatus", getIdStatus());
		attributes.put("idComments", getIdComments());
		attributes.put("htdOption1", getHtdOption1());
		attributes.put("htdHrFee", getHtdHrFee());
		attributes.put("htdFinanceFee", getHtdFinanceFee());
		attributes.put("htdStatus", getHtdStatus());
		attributes.put("htdComments", getHtdComments());
		attributes.put("hdOption1", getHdOption1());
		attributes.put("hdOption2", getHdOption2());
		attributes.put("hdOption2Text", getHdOption2Text());
		attributes.put("hdOption3", getHdOption3());
		attributes.put("hdOption3Money", getHdOption3Money());
		attributes.put("hdOption4", getHdOption4());
		attributes.put("hdOption4Money", getHdOption4Money());
		attributes.put("hdStatus", getHdStatus());
		attributes.put("hdComments", getHdComments());
		attributes.put("hdleaveText", getHdleaveText());
		attributes.put("fdOption1", getFdOption1());
		attributes.put("fdOption2", getFdOption2());
		attributes.put("fdOption3", getFdOption3());
		attributes.put("fdOption4", getFdOption4());
		attributes.put("fdOption4Text", getFdOption4Text());
		attributes.put("fdStatus", getFdStatus());
		attributes.put("fdComments", getFdComments());
		attributes.put("applicantAgent", getApplicantAgent());
		attributes.put("approverAgent", getApproverAgent());
		attributes.put("processType", getProcessType());
		attributes.put("subProcessType", getSubProcessType());
		attributes.put("status", getStatus());
		attributes.put("statusByUserId", getStatusByUserId());
		attributes.put("statusByUserName", getStatusByUserName());
		attributes.put("statusDate", getStatusDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long eclosingId = (Long)attributes.get("eclosingId");

		if (eclosingId != null) {
			setEclosingId(eclosingId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String ticketNo = (String)attributes.get("ticketNo");

		if (ticketNo != null) {
			setTicketNo(ticketNo);
		}

		Integer staffCode = (Integer)attributes.get("staffCode");

		if (staffCode != null) {
			setStaffCode(staffCode);
		}

		String staffName = (String)attributes.get("staffName");

		if (staffName != null) {
			setStaffName(staffName);
		}

		String company = (String)attributes.get("company");

		if (company != null) {
			setCompany(company);
		}

		String division = (String)attributes.get("division");

		if (division != null) {
			setDivision(division);
		}

		String department = (String)attributes.get("department");

		if (department != null) {
			setDepartment(department);
		}

		String costCenter = (String)attributes.get("costCenter");

		if (costCenter != null) {
			setCostCenter(costCenter);
		}

		String functionName = (String)attributes.get("functionName");

		if (functionName != null) {
			setFunctionName(functionName);
		}

		String positionCode = (String)attributes.get("positionCode");

		if (positionCode != null) {
			setPositionCode(positionCode);
		}

		String employeeGroupId = (String)attributes.get("employeeGroupId");

		if (employeeGroupId != null) {
			setEmployeeGroupId(employeeGroupId);
		}

		String employeeGroupName = (String)attributes.get("employeeGroupName");

		if (employeeGroupName != null) {
			setEmployeeGroupName(employeeGroupName);
		}

		String privateEmailAddress = (String)attributes.get(
				"privateEmailAddress");

		if (privateEmailAddress != null) {
			setPrivateEmailAddress(privateEmailAddress);
		}

		Date startingDate = (Date)attributes.get("startingDate");

		if (startingDate != null) {
			setStartingDate(startingDate);
		}

		Date lastWorkingDay = (Date)attributes.get("lastWorkingDay");

		if (lastWorkingDay != null) {
			setLastWorkingDay(lastWorkingDay);
		}

		Date finishContractDate = (Date)attributes.get("finishContractDate");

		if (finishContractDate != null) {
			setFinishContractDate(finishContractDate);
		}

		String seatOfficeNumber = (String)attributes.get("seatOfficeNumber");

		if (seatOfficeNumber != null) {
			setSeatOfficeNumber(seatOfficeNumber);
		}

		String permanentAddress = (String)attributes.get("permanentAddress");

		if (permanentAddress != null) {
			setPermanentAddress(permanentAddress);
		}

		Boolean dmOption1 = (Boolean)attributes.get("dmOption1");

		if (dmOption1 != null) {
			setDmOption1(dmOption1);
		}

		Boolean dmOption2 = (Boolean)attributes.get("dmOption2");

		if (dmOption2 != null) {
			setDmOption2(dmOption2);
		}

		String dmStatus = (String)attributes.get("dmStatus");

		if (dmStatus != null) {
			setDmStatus(dmStatus);
		}

		String dmComments = (String)attributes.get("dmComments");

		if (dmComments != null) {
			setDmComments(dmComments);
		}

		Boolean adOption1 = (Boolean)attributes.get("adOption1");

		if (adOption1 != null) {
			setAdOption1(adOption1);
		}

		Boolean adOption2 = (Boolean)attributes.get("adOption2");

		if (adOption2 != null) {
			setAdOption2(adOption2);
		}

		Boolean adOption3 = (Boolean)attributes.get("adOption3");

		if (adOption3 != null) {
			setAdOption3(adOption3);
		}

		Boolean adOption4 = (Boolean)attributes.get("adOption4");

		if (adOption4 != null) {
			setAdOption4(adOption4);
		}

		Double adFinanceFee = (Double)attributes.get("adFinanceFee");

		if (adFinanceFee != null) {
			setAdFinanceFee(adFinanceFee);
		}

		String adStatus = (String)attributes.get("adStatus");

		if (adStatus != null) {
			setAdStatus(adStatus);
		}

		String adComments = (String)attributes.get("adComments");

		if (adComments != null) {
			setAdComments(adComments);
		}

		Boolean fsOption1 = (Boolean)attributes.get("fsOption1");

		if (fsOption1 != null) {
			setFsOption1(fsOption1);
		}

		String fsStatus = (String)attributes.get("fsStatus");

		if (fsStatus != null) {
			setFsStatus(fsStatus);
		}

		String fsComments = (String)attributes.get("fsComments");

		if (fsComments != null) {
			setFsComments(fsComments);
		}

		Boolean flcOption1 = (Boolean)attributes.get("flcOption1");

		if (flcOption1 != null) {
			setFlcOption1(flcOption1);
		}

		Boolean flcOption2 = (Boolean)attributes.get("flcOption2");

		if (flcOption2 != null) {
			setFlcOption2(flcOption2);
		}

		String flcStatus = (String)attributes.get("flcStatus");

		if (flcStatus != null) {
			setFlcStatus(flcStatus);
		}

		String flcComments = (String)attributes.get("flcComments");

		if (flcComments != null) {
			setFlcComments(flcComments);
		}

		Boolean securityOption1 = (Boolean)attributes.get("securityOption1");

		if (securityOption1 != null) {
			setSecurityOption1(securityOption1);
		}

		Double securityFinanceFee = (Double)attributes.get("securityFinanceFee");

		if (securityFinanceFee != null) {
			setSecurityFinanceFee(securityFinanceFee);
		}

		String securityStatus = (String)attributes.get("securityStatus");

		if (securityStatus != null) {
			setSecurityStatus(securityStatus);
		}

		String securityComments = (String)attributes.get("securityComments");

		if (securityComments != null) {
			setSecurityComments(securityComments);
		}

		Boolean idOption1 = (Boolean)attributes.get("idOption1");

		if (idOption1 != null) {
			setIdOption1(idOption1);
		}

		Boolean idOption2 = (Boolean)attributes.get("idOption2");

		if (idOption2 != null) {
			setIdOption2(idOption2);
		}

		Boolean idOption3 = (Boolean)attributes.get("idOption3");

		if (idOption3 != null) {
			setIdOption3(idOption3);
		}

		Boolean idOption4 = (Boolean)attributes.get("idOption4");

		if (idOption4 != null) {
			setIdOption4(idOption4);
		}

		Boolean idOption5 = (Boolean)attributes.get("idOption5");

		if (idOption5 != null) {
			setIdOption5(idOption5);
		}

		Boolean idOption6 = (Boolean)attributes.get("idOption6");

		if (idOption6 != null) {
			setIdOption6(idOption6);
		}

		Boolean idOption7 = (Boolean)attributes.get("idOption7");

		if (idOption7 != null) {
			setIdOption7(idOption7);
		}

		Boolean idOption8 = (Boolean)attributes.get("idOption8");

		if (idOption8 != null) {
			setIdOption8(idOption8);
		}

		Boolean idOption9 = (Boolean)attributes.get("idOption9");

		if (idOption9 != null) {
			setIdOption9(idOption9);
		}

		Double idHrFee = (Double)attributes.get("idHrFee");

		if (idHrFee != null) {
			setIdHrFee(idHrFee);
		}

		Double idFinanceFee = (Double)attributes.get("idFinanceFee");

		if (idFinanceFee != null) {
			setIdFinanceFee(idFinanceFee);
		}

		String idStatus = (String)attributes.get("idStatus");

		if (idStatus != null) {
			setIdStatus(idStatus);
		}

		String idComments = (String)attributes.get("idComments");

		if (idComments != null) {
			setIdComments(idComments);
		}

		Boolean htdOption1 = (Boolean)attributes.get("htdOption1");

		if (htdOption1 != null) {
			setHtdOption1(htdOption1);
		}

		Double htdHrFee = (Double)attributes.get("htdHrFee");

		if (htdHrFee != null) {
			setHtdHrFee(htdHrFee);
		}

		Double htdFinanceFee = (Double)attributes.get("htdFinanceFee");

		if (htdFinanceFee != null) {
			setHtdFinanceFee(htdFinanceFee);
		}

		String htdStatus = (String)attributes.get("htdStatus");

		if (htdStatus != null) {
			setHtdStatus(htdStatus);
		}

		String htdComments = (String)attributes.get("htdComments");

		if (htdComments != null) {
			setHtdComments(htdComments);
		}

		Boolean hdOption1 = (Boolean)attributes.get("hdOption1");

		if (hdOption1 != null) {
			setHdOption1(hdOption1);
		}

		Boolean hdOption2 = (Boolean)attributes.get("hdOption2");

		if (hdOption2 != null) {
			setHdOption2(hdOption2);
		}

		String hdOption2Text = (String)attributes.get("hdOption2Text");

		if (hdOption2Text != null) {
			setHdOption2Text(hdOption2Text);
		}

		Boolean hdOption3 = (Boolean)attributes.get("hdOption3");

		if (hdOption3 != null) {
			setHdOption3(hdOption3);
		}

		Double hdOption3Money = (Double)attributes.get("hdOption3Money");

		if (hdOption3Money != null) {
			setHdOption3Money(hdOption3Money);
		}

		Boolean hdOption4 = (Boolean)attributes.get("hdOption4");

		if (hdOption4 != null) {
			setHdOption4(hdOption4);
		}

		Double hdOption4Money = (Double)attributes.get("hdOption4Money");

		if (hdOption4Money != null) {
			setHdOption4Money(hdOption4Money);
		}

		String hdStatus = (String)attributes.get("hdStatus");

		if (hdStatus != null) {
			setHdStatus(hdStatus);
		}

		String hdComments = (String)attributes.get("hdComments");

		if (hdComments != null) {
			setHdComments(hdComments);
		}

		String hdleaveText = (String)attributes.get("hdleaveText");

		if (hdleaveText != null) {
			setHdleaveText(hdleaveText);
		}

		Boolean fdOption1 = (Boolean)attributes.get("fdOption1");

		if (fdOption1 != null) {
			setFdOption1(fdOption1);
		}

		Boolean fdOption2 = (Boolean)attributes.get("fdOption2");

		if (fdOption2 != null) {
			setFdOption2(fdOption2);
		}

		Boolean fdOption3 = (Boolean)attributes.get("fdOption3");

		if (fdOption3 != null) {
			setFdOption3(fdOption3);
		}

		Boolean fdOption4 = (Boolean)attributes.get("fdOption4");

		if (fdOption4 != null) {
			setFdOption4(fdOption4);
		}

		String fdOption4Text = (String)attributes.get("fdOption4Text");

		if (fdOption4Text != null) {
			setFdOption4Text(fdOption4Text);
		}

		String fdStatus = (String)attributes.get("fdStatus");

		if (fdStatus != null) {
			setFdStatus(fdStatus);
		}

		String fdComments = (String)attributes.get("fdComments");

		if (fdComments != null) {
			setFdComments(fdComments);
		}

		Boolean applicantAgent = (Boolean)attributes.get("applicantAgent");

		if (applicantAgent != null) {
			setApplicantAgent(applicantAgent);
		}

		Boolean approverAgent = (Boolean)attributes.get("approverAgent");

		if (approverAgent != null) {
			setApproverAgent(approverAgent);
		}

		String processType = (String)attributes.get("processType");

		if (processType != null) {
			setProcessType(processType);
		}

		String subProcessType = (String)attributes.get("subProcessType");

		if (subProcessType != null) {
			setSubProcessType(subProcessType);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		Long statusByUserId = (Long)attributes.get("statusByUserId");

		if (statusByUserId != null) {
			setStatusByUserId(statusByUserId);
		}

		String statusByUserName = (String)attributes.get("statusByUserName");

		if (statusByUserName != null) {
			setStatusByUserName(statusByUserName);
		}

		Date statusDate = (Date)attributes.get("statusDate");

		if (statusDate != null) {
			setStatusDate(statusDate);
		}
	}

	@JSON
	@Override
	public long getEclosingId() {
		return _eclosingId;
	}

	@Override
	public void setEclosingId(long eclosingId) {
		_columnBitmask = -1L;

		_eclosingId = eclosingId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getTicketNo() {
		if (_ticketNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _ticketNo;
		}
	}

	@Override
	public void setTicketNo(String ticketNo) {
		_ticketNo = ticketNo;
	}

	@JSON
	@Override
	public int getStaffCode() {
		return _staffCode;
	}

	@Override
	public void setStaffCode(int staffCode) {
		_staffCode = staffCode;
	}

	@JSON
	@Override
	public String getStaffName() {
		if (_staffName == null) {
			return StringPool.BLANK;
		}
		else {
			return _staffName;
		}
	}

	@Override
	public void setStaffName(String staffName) {
		_staffName = staffName;
	}

	@JSON
	@Override
	public String getCompany() {
		if (_company == null) {
			return StringPool.BLANK;
		}
		else {
			return _company;
		}
	}

	@Override
	public void setCompany(String company) {
		_company = company;
	}

	@JSON
	@Override
	public String getDivision() {
		if (_division == null) {
			return StringPool.BLANK;
		}
		else {
			return _division;
		}
	}

	@Override
	public void setDivision(String division) {
		_division = division;
	}

	@JSON
	@Override
	public String getDepartment() {
		if (_department == null) {
			return StringPool.BLANK;
		}
		else {
			return _department;
		}
	}

	@Override
	public void setDepartment(String department) {
		_department = department;
	}

	@JSON
	@Override
	public String getCostCenter() {
		if (_costCenter == null) {
			return StringPool.BLANK;
		}
		else {
			return _costCenter;
		}
	}

	@Override
	public void setCostCenter(String costCenter) {
		_costCenter = costCenter;
	}

	@JSON
	@Override
	public String getFunctionName() {
		if (_functionName == null) {
			return StringPool.BLANK;
		}
		else {
			return _functionName;
		}
	}

	@Override
	public void setFunctionName(String functionName) {
		_functionName = functionName;
	}

	@JSON
	@Override
	public String getPositionCode() {
		if (_positionCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _positionCode;
		}
	}

	@Override
	public void setPositionCode(String positionCode) {
		_positionCode = positionCode;
	}

	@JSON
	@Override
	public String getEmployeeGroupId() {
		if (_employeeGroupId == null) {
			return StringPool.BLANK;
		}
		else {
			return _employeeGroupId;
		}
	}

	@Override
	public void setEmployeeGroupId(String employeeGroupId) {
		_employeeGroupId = employeeGroupId;
	}

	@JSON
	@Override
	public String getEmployeeGroupName() {
		if (_employeeGroupName == null) {
			return StringPool.BLANK;
		}
		else {
			return _employeeGroupName;
		}
	}

	@Override
	public void setEmployeeGroupName(String employeeGroupName) {
		_employeeGroupName = employeeGroupName;
	}

	@JSON
	@Override
	public String getPrivateEmailAddress() {
		if (_privateEmailAddress == null) {
			return StringPool.BLANK;
		}
		else {
			return _privateEmailAddress;
		}
	}

	@Override
	public void setPrivateEmailAddress(String privateEmailAddress) {
		_privateEmailAddress = privateEmailAddress;
	}

	@JSON
	@Override
	public Date getStartingDate() {
		return _startingDate;
	}

	@Override
	public void setStartingDate(Date startingDate) {
		_startingDate = startingDate;
	}

	@JSON
	@Override
	public Date getLastWorkingDay() {
		return _lastWorkingDay;
	}

	@Override
	public void setLastWorkingDay(Date lastWorkingDay) {
		_lastWorkingDay = lastWorkingDay;
	}

	@JSON
	@Override
	public Date getFinishContractDate() {
		return _finishContractDate;
	}

	@Override
	public void setFinishContractDate(Date finishContractDate) {
		_finishContractDate = finishContractDate;
	}

	@JSON
	@Override
	public String getSeatOfficeNumber() {
		if (_seatOfficeNumber == null) {
			return StringPool.BLANK;
		}
		else {
			return _seatOfficeNumber;
		}
	}

	@Override
	public void setSeatOfficeNumber(String seatOfficeNumber) {
		_seatOfficeNumber = seatOfficeNumber;
	}

	@JSON
	@Override
	public String getPermanentAddress() {
		if (_permanentAddress == null) {
			return StringPool.BLANK;
		}
		else {
			return _permanentAddress;
		}
	}

	@Override
	public void setPermanentAddress(String permanentAddress) {
		_permanentAddress = permanentAddress;
	}

	@JSON
	@Override
	public boolean getDmOption1() {
		return _dmOption1;
	}

	@Override
	public boolean isDmOption1() {
		return _dmOption1;
	}

	@Override
	public void setDmOption1(boolean dmOption1) {
		_dmOption1 = dmOption1;
	}

	@JSON
	@Override
	public boolean getDmOption2() {
		return _dmOption2;
	}

	@Override
	public boolean isDmOption2() {
		return _dmOption2;
	}

	@Override
	public void setDmOption2(boolean dmOption2) {
		_dmOption2 = dmOption2;
	}

	@JSON
	@Override
	public String getDmStatus() {
		if (_dmStatus == null) {
			return StringPool.BLANK;
		}
		else {
			return _dmStatus;
		}
	}

	@Override
	public void setDmStatus(String dmStatus) {
		_dmStatus = dmStatus;
	}

	@JSON
	@Override
	public String getDmComments() {
		if (_dmComments == null) {
			return StringPool.BLANK;
		}
		else {
			return _dmComments;
		}
	}

	@Override
	public void setDmComments(String dmComments) {
		_dmComments = dmComments;
	}

	@JSON
	@Override
	public boolean getAdOption1() {
		return _adOption1;
	}

	@Override
	public boolean isAdOption1() {
		return _adOption1;
	}

	@Override
	public void setAdOption1(boolean adOption1) {
		_adOption1 = adOption1;
	}

	@JSON
	@Override
	public boolean getAdOption2() {
		return _adOption2;
	}

	@Override
	public boolean isAdOption2() {
		return _adOption2;
	}

	@Override
	public void setAdOption2(boolean adOption2) {
		_adOption2 = adOption2;
	}

	@JSON
	@Override
	public boolean getAdOption3() {
		return _adOption3;
	}

	@Override
	public boolean isAdOption3() {
		return _adOption3;
	}

	@Override
	public void setAdOption3(boolean adOption3) {
		_adOption3 = adOption3;
	}

	@JSON
	@Override
	public boolean getAdOption4() {
		return _adOption4;
	}

	@Override
	public boolean isAdOption4() {
		return _adOption4;
	}

	@Override
	public void setAdOption4(boolean adOption4) {
		_adOption4 = adOption4;
	}

	@JSON
	@Override
	public double getAdFinanceFee() {
		return _adFinanceFee;
	}

	@Override
	public void setAdFinanceFee(double adFinanceFee) {
		_adFinanceFee = adFinanceFee;
	}

	@JSON
	@Override
	public String getAdStatus() {
		if (_adStatus == null) {
			return StringPool.BLANK;
		}
		else {
			return _adStatus;
		}
	}

	@Override
	public void setAdStatus(String adStatus) {
		_adStatus = adStatus;
	}

	@JSON
	@Override
	public String getAdComments() {
		if (_adComments == null) {
			return StringPool.BLANK;
		}
		else {
			return _adComments;
		}
	}

	@Override
	public void setAdComments(String adComments) {
		_adComments = adComments;
	}

	@JSON
	@Override
	public boolean getFsOption1() {
		return _fsOption1;
	}

	@Override
	public boolean isFsOption1() {
		return _fsOption1;
	}

	@Override
	public void setFsOption1(boolean fsOption1) {
		_fsOption1 = fsOption1;
	}

	@JSON
	@Override
	public String getFsStatus() {
		if (_fsStatus == null) {
			return StringPool.BLANK;
		}
		else {
			return _fsStatus;
		}
	}

	@Override
	public void setFsStatus(String fsStatus) {
		_fsStatus = fsStatus;
	}

	@JSON
	@Override
	public String getFsComments() {
		if (_fsComments == null) {
			return StringPool.BLANK;
		}
		else {
			return _fsComments;
		}
	}

	@Override
	public void setFsComments(String fsComments) {
		_fsComments = fsComments;
	}

	@JSON
	@Override
	public boolean getFlcOption1() {
		return _flcOption1;
	}

	@Override
	public boolean isFlcOption1() {
		return _flcOption1;
	}

	@Override
	public void setFlcOption1(boolean flcOption1) {
		_flcOption1 = flcOption1;
	}

	@JSON
	@Override
	public boolean getFlcOption2() {
		return _flcOption2;
	}

	@Override
	public boolean isFlcOption2() {
		return _flcOption2;
	}

	@Override
	public void setFlcOption2(boolean flcOption2) {
		_flcOption2 = flcOption2;
	}

	@JSON
	@Override
	public String getFlcStatus() {
		if (_flcStatus == null) {
			return StringPool.BLANK;
		}
		else {
			return _flcStatus;
		}
	}

	@Override
	public void setFlcStatus(String flcStatus) {
		_flcStatus = flcStatus;
	}

	@JSON
	@Override
	public String getFlcComments() {
		if (_flcComments == null) {
			return StringPool.BLANK;
		}
		else {
			return _flcComments;
		}
	}

	@Override
	public void setFlcComments(String flcComments) {
		_flcComments = flcComments;
	}

	@JSON
	@Override
	public boolean getSecurityOption1() {
		return _securityOption1;
	}

	@Override
	public boolean isSecurityOption1() {
		return _securityOption1;
	}

	@Override
	public void setSecurityOption1(boolean securityOption1) {
		_securityOption1 = securityOption1;
	}

	@JSON
	@Override
	public double getSecurityFinanceFee() {
		return _securityFinanceFee;
	}

	@Override
	public void setSecurityFinanceFee(double securityFinanceFee) {
		_securityFinanceFee = securityFinanceFee;
	}

	@JSON
	@Override
	public String getSecurityStatus() {
		if (_securityStatus == null) {
			return StringPool.BLANK;
		}
		else {
			return _securityStatus;
		}
	}

	@Override
	public void setSecurityStatus(String securityStatus) {
		_securityStatus = securityStatus;
	}

	@JSON
	@Override
	public String getSecurityComments() {
		if (_securityComments == null) {
			return StringPool.BLANK;
		}
		else {
			return _securityComments;
		}
	}

	@Override
	public void setSecurityComments(String securityComments) {
		_securityComments = securityComments;
	}

	@JSON
	@Override
	public boolean getIdOption1() {
		return _idOption1;
	}

	@Override
	public boolean isIdOption1() {
		return _idOption1;
	}

	@Override
	public void setIdOption1(boolean idOption1) {
		_idOption1 = idOption1;
	}

	@JSON
	@Override
	public boolean getIdOption2() {
		return _idOption2;
	}

	@Override
	public boolean isIdOption2() {
		return _idOption2;
	}

	@Override
	public void setIdOption2(boolean idOption2) {
		_idOption2 = idOption2;
	}

	@JSON
	@Override
	public boolean getIdOption3() {
		return _idOption3;
	}

	@Override
	public boolean isIdOption3() {
		return _idOption3;
	}

	@Override
	public void setIdOption3(boolean idOption3) {
		_idOption3 = idOption3;
	}

	@JSON
	@Override
	public boolean getIdOption4() {
		return _idOption4;
	}

	@Override
	public boolean isIdOption4() {
		return _idOption4;
	}

	@Override
	public void setIdOption4(boolean idOption4) {
		_idOption4 = idOption4;
	}

	@JSON
	@Override
	public boolean getIdOption5() {
		return _idOption5;
	}

	@Override
	public boolean isIdOption5() {
		return _idOption5;
	}

	@Override
	public void setIdOption5(boolean idOption5) {
		_idOption5 = idOption5;
	}

	@JSON
	@Override
	public boolean getIdOption6() {
		return _idOption6;
	}

	@Override
	public boolean isIdOption6() {
		return _idOption6;
	}

	@Override
	public void setIdOption6(boolean idOption6) {
		_idOption6 = idOption6;
	}

	@JSON
	@Override
	public boolean getIdOption7() {
		return _idOption7;
	}

	@Override
	public boolean isIdOption7() {
		return _idOption7;
	}

	@Override
	public void setIdOption7(boolean idOption7) {
		_idOption7 = idOption7;
	}

	@JSON
	@Override
	public boolean getIdOption8() {
		return _idOption8;
	}

	@Override
	public boolean isIdOption8() {
		return _idOption8;
	}

	@Override
	public void setIdOption8(boolean idOption8) {
		_idOption8 = idOption8;
	}

	@JSON
	@Override
	public boolean getIdOption9() {
		return _idOption9;
	}

	@Override
	public boolean isIdOption9() {
		return _idOption9;
	}

	@Override
	public void setIdOption9(boolean idOption9) {
		_idOption9 = idOption9;
	}

	@JSON
	@Override
	public double getIdHrFee() {
		return _idHrFee;
	}

	@Override
	public void setIdHrFee(double idHrFee) {
		_idHrFee = idHrFee;
	}

	@JSON
	@Override
	public double getIdFinanceFee() {
		return _idFinanceFee;
	}

	@Override
	public void setIdFinanceFee(double idFinanceFee) {
		_idFinanceFee = idFinanceFee;
	}

	@JSON
	@Override
	public String getIdStatus() {
		if (_idStatus == null) {
			return StringPool.BLANK;
		}
		else {
			return _idStatus;
		}
	}

	@Override
	public void setIdStatus(String idStatus) {
		_idStatus = idStatus;
	}

	@JSON
	@Override
	public String getIdComments() {
		if (_idComments == null) {
			return StringPool.BLANK;
		}
		else {
			return _idComments;
		}
	}

	@Override
	public void setIdComments(String idComments) {
		_idComments = idComments;
	}

	@JSON
	@Override
	public boolean getHtdOption1() {
		return _htdOption1;
	}

	@Override
	public boolean isHtdOption1() {
		return _htdOption1;
	}

	@Override
	public void setHtdOption1(boolean htdOption1) {
		_htdOption1 = htdOption1;
	}

	@JSON
	@Override
	public double getHtdHrFee() {
		return _htdHrFee;
	}

	@Override
	public void setHtdHrFee(double htdHrFee) {
		_htdHrFee = htdHrFee;
	}

	@JSON
	@Override
	public double getHtdFinanceFee() {
		return _htdFinanceFee;
	}

	@Override
	public void setHtdFinanceFee(double htdFinanceFee) {
		_htdFinanceFee = htdFinanceFee;
	}

	@JSON
	@Override
	public String getHtdStatus() {
		if (_htdStatus == null) {
			return StringPool.BLANK;
		}
		else {
			return _htdStatus;
		}
	}

	@Override
	public void setHtdStatus(String htdStatus) {
		_htdStatus = htdStatus;
	}

	@JSON
	@Override
	public String getHtdComments() {
		if (_htdComments == null) {
			return StringPool.BLANK;
		}
		else {
			return _htdComments;
		}
	}

	@Override
	public void setHtdComments(String htdComments) {
		_htdComments = htdComments;
	}

	@JSON
	@Override
	public boolean getHdOption1() {
		return _hdOption1;
	}

	@Override
	public boolean isHdOption1() {
		return _hdOption1;
	}

	@Override
	public void setHdOption1(boolean hdOption1) {
		_hdOption1 = hdOption1;
	}

	@JSON
	@Override
	public boolean getHdOption2() {
		return _hdOption2;
	}

	@Override
	public boolean isHdOption2() {
		return _hdOption2;
	}

	@Override
	public void setHdOption2(boolean hdOption2) {
		_hdOption2 = hdOption2;
	}

	@JSON
	@Override
	public String getHdOption2Text() {
		if (_hdOption2Text == null) {
			return StringPool.BLANK;
		}
		else {
			return _hdOption2Text;
		}
	}

	@Override
	public void setHdOption2Text(String hdOption2Text) {
		_hdOption2Text = hdOption2Text;
	}

	@JSON
	@Override
	public boolean getHdOption3() {
		return _hdOption3;
	}

	@Override
	public boolean isHdOption3() {
		return _hdOption3;
	}

	@Override
	public void setHdOption3(boolean hdOption3) {
		_hdOption3 = hdOption3;
	}

	@JSON
	@Override
	public double getHdOption3Money() {
		return _hdOption3Money;
	}

	@Override
	public void setHdOption3Money(double hdOption3Money) {
		_hdOption3Money = hdOption3Money;
	}

	@JSON
	@Override
	public boolean getHdOption4() {
		return _hdOption4;
	}

	@Override
	public boolean isHdOption4() {
		return _hdOption4;
	}

	@Override
	public void setHdOption4(boolean hdOption4) {
		_hdOption4 = hdOption4;
	}

	@JSON
	@Override
	public double getHdOption4Money() {
		return _hdOption4Money;
	}

	@Override
	public void setHdOption4Money(double hdOption4Money) {
		_hdOption4Money = hdOption4Money;
	}

	@JSON
	@Override
	public String getHdStatus() {
		if (_hdStatus == null) {
			return StringPool.BLANK;
		}
		else {
			return _hdStatus;
		}
	}

	@Override
	public void setHdStatus(String hdStatus) {
		_hdStatus = hdStatus;
	}

	@JSON
	@Override
	public String getHdComments() {
		if (_hdComments == null) {
			return StringPool.BLANK;
		}
		else {
			return _hdComments;
		}
	}

	@Override
	public void setHdComments(String hdComments) {
		_hdComments = hdComments;
	}

	@JSON
	@Override
	public String getHdleaveText() {
		if (_hdleaveText == null) {
			return StringPool.BLANK;
		}
		else {
			return _hdleaveText;
		}
	}

	@Override
	public void setHdleaveText(String hdleaveText) {
		_hdleaveText = hdleaveText;
	}

	@JSON
	@Override
	public boolean getFdOption1() {
		return _fdOption1;
	}

	@Override
	public boolean isFdOption1() {
		return _fdOption1;
	}

	@Override
	public void setFdOption1(boolean fdOption1) {
		_fdOption1 = fdOption1;
	}

	@JSON
	@Override
	public boolean getFdOption2() {
		return _fdOption2;
	}

	@Override
	public boolean isFdOption2() {
		return _fdOption2;
	}

	@Override
	public void setFdOption2(boolean fdOption2) {
		_fdOption2 = fdOption2;
	}

	@JSON
	@Override
	public boolean getFdOption3() {
		return _fdOption3;
	}

	@Override
	public boolean isFdOption3() {
		return _fdOption3;
	}

	@Override
	public void setFdOption3(boolean fdOption3) {
		_fdOption3 = fdOption3;
	}

	@JSON
	@Override
	public boolean getFdOption4() {
		return _fdOption4;
	}

	@Override
	public boolean isFdOption4() {
		return _fdOption4;
	}

	@Override
	public void setFdOption4(boolean fdOption4) {
		_fdOption4 = fdOption4;
	}

	@JSON
	@Override
	public String getFdOption4Text() {
		if (_fdOption4Text == null) {
			return StringPool.BLANK;
		}
		else {
			return _fdOption4Text;
		}
	}

	@Override
	public void setFdOption4Text(String fdOption4Text) {
		_fdOption4Text = fdOption4Text;
	}

	@JSON
	@Override
	public String getFdStatus() {
		if (_fdStatus == null) {
			return StringPool.BLANK;
		}
		else {
			return _fdStatus;
		}
	}

	@Override
	public void setFdStatus(String fdStatus) {
		_fdStatus = fdStatus;
	}

	@JSON
	@Override
	public String getFdComments() {
		if (_fdComments == null) {
			return StringPool.BLANK;
		}
		else {
			return _fdComments;
		}
	}

	@Override
	public void setFdComments(String fdComments) {
		_fdComments = fdComments;
	}

	@JSON
	@Override
	public boolean getApplicantAgent() {
		return _applicantAgent;
	}

	@Override
	public boolean isApplicantAgent() {
		return _applicantAgent;
	}

	@Override
	public void setApplicantAgent(boolean applicantAgent) {
		_applicantAgent = applicantAgent;
	}

	@JSON
	@Override
	public boolean getApproverAgent() {
		return _approverAgent;
	}

	@Override
	public boolean isApproverAgent() {
		return _approverAgent;
	}

	@Override
	public void setApproverAgent(boolean approverAgent) {
		_approverAgent = approverAgent;
	}

	@JSON
	@Override
	public String getProcessType() {
		if (_processType == null) {
			return StringPool.BLANK;
		}
		else {
			return _processType;
		}
	}

	@Override
	public void setProcessType(String processType) {
		_processType = processType;
	}

	@JSON
	@Override
	public String getSubProcessType() {
		if (_subProcessType == null) {
			return StringPool.BLANK;
		}
		else {
			return _subProcessType;
		}
	}

	@Override
	public void setSubProcessType(String subProcessType) {
		_subProcessType = subProcessType;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (!_setOriginalStatus) {
			_setOriginalStatus = true;

			_originalStatus = _status;
		}

		_status = status;
	}

	public int getOriginalStatus() {
		return _originalStatus;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getStatusByUserId(), "uuid",
			_statusByUserUuid);
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
		_statusByUserUuid = statusByUserUuid;
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return StringPool.BLANK;
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	/**
	 * @deprecated As of 6.1.0, replaced by {@link #isApproved}
	 */
	@Override
	public boolean getApproved() {
		return isApproved();
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			EClosing.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EClosing toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (EClosing)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EClosingImpl eClosingImpl = new EClosingImpl();

		eClosingImpl.setEclosingId(getEclosingId());
		eClosingImpl.setGroupId(getGroupId());
		eClosingImpl.setCompanyId(getCompanyId());
		eClosingImpl.setUserId(getUserId());
		eClosingImpl.setUserName(getUserName());
		eClosingImpl.setCreateDate(getCreateDate());
		eClosingImpl.setModifiedDate(getModifiedDate());
		eClosingImpl.setTicketNo(getTicketNo());
		eClosingImpl.setStaffCode(getStaffCode());
		eClosingImpl.setStaffName(getStaffName());
		eClosingImpl.setCompany(getCompany());
		eClosingImpl.setDivision(getDivision());
		eClosingImpl.setDepartment(getDepartment());
		eClosingImpl.setCostCenter(getCostCenter());
		eClosingImpl.setFunctionName(getFunctionName());
		eClosingImpl.setPositionCode(getPositionCode());
		eClosingImpl.setEmployeeGroupId(getEmployeeGroupId());
		eClosingImpl.setEmployeeGroupName(getEmployeeGroupName());
		eClosingImpl.setPrivateEmailAddress(getPrivateEmailAddress());
		eClosingImpl.setStartingDate(getStartingDate());
		eClosingImpl.setLastWorkingDay(getLastWorkingDay());
		eClosingImpl.setFinishContractDate(getFinishContractDate());
		eClosingImpl.setSeatOfficeNumber(getSeatOfficeNumber());
		eClosingImpl.setPermanentAddress(getPermanentAddress());
		eClosingImpl.setDmOption1(getDmOption1());
		eClosingImpl.setDmOption2(getDmOption2());
		eClosingImpl.setDmStatus(getDmStatus());
		eClosingImpl.setDmComments(getDmComments());
		eClosingImpl.setAdOption1(getAdOption1());
		eClosingImpl.setAdOption2(getAdOption2());
		eClosingImpl.setAdOption3(getAdOption3());
		eClosingImpl.setAdOption4(getAdOption4());
		eClosingImpl.setAdFinanceFee(getAdFinanceFee());
		eClosingImpl.setAdStatus(getAdStatus());
		eClosingImpl.setAdComments(getAdComments());
		eClosingImpl.setFsOption1(getFsOption1());
		eClosingImpl.setFsStatus(getFsStatus());
		eClosingImpl.setFsComments(getFsComments());
		eClosingImpl.setFlcOption1(getFlcOption1());
		eClosingImpl.setFlcOption2(getFlcOption2());
		eClosingImpl.setFlcStatus(getFlcStatus());
		eClosingImpl.setFlcComments(getFlcComments());
		eClosingImpl.setSecurityOption1(getSecurityOption1());
		eClosingImpl.setSecurityFinanceFee(getSecurityFinanceFee());
		eClosingImpl.setSecurityStatus(getSecurityStatus());
		eClosingImpl.setSecurityComments(getSecurityComments());
		eClosingImpl.setIdOption1(getIdOption1());
		eClosingImpl.setIdOption2(getIdOption2());
		eClosingImpl.setIdOption3(getIdOption3());
		eClosingImpl.setIdOption4(getIdOption4());
		eClosingImpl.setIdOption5(getIdOption5());
		eClosingImpl.setIdOption6(getIdOption6());
		eClosingImpl.setIdOption7(getIdOption7());
		eClosingImpl.setIdOption8(getIdOption8());
		eClosingImpl.setIdOption9(getIdOption9());
		eClosingImpl.setIdHrFee(getIdHrFee());
		eClosingImpl.setIdFinanceFee(getIdFinanceFee());
		eClosingImpl.setIdStatus(getIdStatus());
		eClosingImpl.setIdComments(getIdComments());
		eClosingImpl.setHtdOption1(getHtdOption1());
		eClosingImpl.setHtdHrFee(getHtdHrFee());
		eClosingImpl.setHtdFinanceFee(getHtdFinanceFee());
		eClosingImpl.setHtdStatus(getHtdStatus());
		eClosingImpl.setHtdComments(getHtdComments());
		eClosingImpl.setHdOption1(getHdOption1());
		eClosingImpl.setHdOption2(getHdOption2());
		eClosingImpl.setHdOption2Text(getHdOption2Text());
		eClosingImpl.setHdOption3(getHdOption3());
		eClosingImpl.setHdOption3Money(getHdOption3Money());
		eClosingImpl.setHdOption4(getHdOption4());
		eClosingImpl.setHdOption4Money(getHdOption4Money());
		eClosingImpl.setHdStatus(getHdStatus());
		eClosingImpl.setHdComments(getHdComments());
		eClosingImpl.setHdleaveText(getHdleaveText());
		eClosingImpl.setFdOption1(getFdOption1());
		eClosingImpl.setFdOption2(getFdOption2());
		eClosingImpl.setFdOption3(getFdOption3());
		eClosingImpl.setFdOption4(getFdOption4());
		eClosingImpl.setFdOption4Text(getFdOption4Text());
		eClosingImpl.setFdStatus(getFdStatus());
		eClosingImpl.setFdComments(getFdComments());
		eClosingImpl.setApplicantAgent(getApplicantAgent());
		eClosingImpl.setApproverAgent(getApproverAgent());
		eClosingImpl.setProcessType(getProcessType());
		eClosingImpl.setSubProcessType(getSubProcessType());
		eClosingImpl.setStatus(getStatus());
		eClosingImpl.setStatusByUserId(getStatusByUserId());
		eClosingImpl.setStatusByUserName(getStatusByUserName());
		eClosingImpl.setStatusDate(getStatusDate());

		eClosingImpl.resetOriginalValues();

		return eClosingImpl;
	}

	@Override
	public int compareTo(EClosing eClosing) {
		int value = 0;

		if (getEclosingId() < eClosing.getEclosingId()) {
			value = -1;
		}
		else if (getEclosingId() > eClosing.getEclosingId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof EClosing)) {
			return false;
		}

		EClosing eClosing = (EClosing)obj;

		long primaryKey = eClosing.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		EClosingModelImpl eClosingModelImpl = this;

		eClosingModelImpl._originalUserId = eClosingModelImpl._userId;

		eClosingModelImpl._setOriginalUserId = false;

		eClosingModelImpl._originalStatus = eClosingModelImpl._status;

		eClosingModelImpl._setOriginalStatus = false;

		eClosingModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<EClosing> toCacheModel() {
		EClosingCacheModel eClosingCacheModel = new EClosingCacheModel();

		eClosingCacheModel.eclosingId = getEclosingId();

		eClosingCacheModel.groupId = getGroupId();

		eClosingCacheModel.companyId = getCompanyId();

		eClosingCacheModel.userId = getUserId();

		eClosingCacheModel.userName = getUserName();

		String userName = eClosingCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			eClosingCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			eClosingCacheModel.createDate = createDate.getTime();
		}
		else {
			eClosingCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			eClosingCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			eClosingCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		eClosingCacheModel.ticketNo = getTicketNo();

		String ticketNo = eClosingCacheModel.ticketNo;

		if ((ticketNo != null) && (ticketNo.length() == 0)) {
			eClosingCacheModel.ticketNo = null;
		}

		eClosingCacheModel.staffCode = getStaffCode();

		eClosingCacheModel.staffName = getStaffName();

		String staffName = eClosingCacheModel.staffName;

		if ((staffName != null) && (staffName.length() == 0)) {
			eClosingCacheModel.staffName = null;
		}

		eClosingCacheModel.company = getCompany();

		String company = eClosingCacheModel.company;

		if ((company != null) && (company.length() == 0)) {
			eClosingCacheModel.company = null;
		}

		eClosingCacheModel.division = getDivision();

		String division = eClosingCacheModel.division;

		if ((division != null) && (division.length() == 0)) {
			eClosingCacheModel.division = null;
		}

		eClosingCacheModel.department = getDepartment();

		String department = eClosingCacheModel.department;

		if ((department != null) && (department.length() == 0)) {
			eClosingCacheModel.department = null;
		}

		eClosingCacheModel.costCenter = getCostCenter();

		String costCenter = eClosingCacheModel.costCenter;

		if ((costCenter != null) && (costCenter.length() == 0)) {
			eClosingCacheModel.costCenter = null;
		}

		eClosingCacheModel.functionName = getFunctionName();

		String functionName = eClosingCacheModel.functionName;

		if ((functionName != null) && (functionName.length() == 0)) {
			eClosingCacheModel.functionName = null;
		}

		eClosingCacheModel.positionCode = getPositionCode();

		String positionCode = eClosingCacheModel.positionCode;

		if ((positionCode != null) && (positionCode.length() == 0)) {
			eClosingCacheModel.positionCode = null;
		}

		eClosingCacheModel.employeeGroupId = getEmployeeGroupId();

		String employeeGroupId = eClosingCacheModel.employeeGroupId;

		if ((employeeGroupId != null) && (employeeGroupId.length() == 0)) {
			eClosingCacheModel.employeeGroupId = null;
		}

		eClosingCacheModel.employeeGroupName = getEmployeeGroupName();

		String employeeGroupName = eClosingCacheModel.employeeGroupName;

		if ((employeeGroupName != null) && (employeeGroupName.length() == 0)) {
			eClosingCacheModel.employeeGroupName = null;
		}

		eClosingCacheModel.privateEmailAddress = getPrivateEmailAddress();

		String privateEmailAddress = eClosingCacheModel.privateEmailAddress;

		if ((privateEmailAddress != null) &&
				(privateEmailAddress.length() == 0)) {
			eClosingCacheModel.privateEmailAddress = null;
		}

		Date startingDate = getStartingDate();

		if (startingDate != null) {
			eClosingCacheModel.startingDate = startingDate.getTime();
		}
		else {
			eClosingCacheModel.startingDate = Long.MIN_VALUE;
		}

		Date lastWorkingDay = getLastWorkingDay();

		if (lastWorkingDay != null) {
			eClosingCacheModel.lastWorkingDay = lastWorkingDay.getTime();
		}
		else {
			eClosingCacheModel.lastWorkingDay = Long.MIN_VALUE;
		}

		Date finishContractDate = getFinishContractDate();

		if (finishContractDate != null) {
			eClosingCacheModel.finishContractDate = finishContractDate.getTime();
		}
		else {
			eClosingCacheModel.finishContractDate = Long.MIN_VALUE;
		}

		eClosingCacheModel.seatOfficeNumber = getSeatOfficeNumber();

		String seatOfficeNumber = eClosingCacheModel.seatOfficeNumber;

		if ((seatOfficeNumber != null) && (seatOfficeNumber.length() == 0)) {
			eClosingCacheModel.seatOfficeNumber = null;
		}

		eClosingCacheModel.permanentAddress = getPermanentAddress();

		String permanentAddress = eClosingCacheModel.permanentAddress;

		if ((permanentAddress != null) && (permanentAddress.length() == 0)) {
			eClosingCacheModel.permanentAddress = null;
		}

		eClosingCacheModel.dmOption1 = getDmOption1();

		eClosingCacheModel.dmOption2 = getDmOption2();

		eClosingCacheModel.dmStatus = getDmStatus();

		String dmStatus = eClosingCacheModel.dmStatus;

		if ((dmStatus != null) && (dmStatus.length() == 0)) {
			eClosingCacheModel.dmStatus = null;
		}

		eClosingCacheModel.dmComments = getDmComments();

		String dmComments = eClosingCacheModel.dmComments;

		if ((dmComments != null) && (dmComments.length() == 0)) {
			eClosingCacheModel.dmComments = null;
		}

		eClosingCacheModel.adOption1 = getAdOption1();

		eClosingCacheModel.adOption2 = getAdOption2();

		eClosingCacheModel.adOption3 = getAdOption3();

		eClosingCacheModel.adOption4 = getAdOption4();

		eClosingCacheModel.adFinanceFee = getAdFinanceFee();

		eClosingCacheModel.adStatus = getAdStatus();

		String adStatus = eClosingCacheModel.adStatus;

		if ((adStatus != null) && (adStatus.length() == 0)) {
			eClosingCacheModel.adStatus = null;
		}

		eClosingCacheModel.adComments = getAdComments();

		String adComments = eClosingCacheModel.adComments;

		if ((adComments != null) && (adComments.length() == 0)) {
			eClosingCacheModel.adComments = null;
		}

		eClosingCacheModel.fsOption1 = getFsOption1();

		eClosingCacheModel.fsStatus = getFsStatus();

		String fsStatus = eClosingCacheModel.fsStatus;

		if ((fsStatus != null) && (fsStatus.length() == 0)) {
			eClosingCacheModel.fsStatus = null;
		}

		eClosingCacheModel.fsComments = getFsComments();

		String fsComments = eClosingCacheModel.fsComments;

		if ((fsComments != null) && (fsComments.length() == 0)) {
			eClosingCacheModel.fsComments = null;
		}

		eClosingCacheModel.flcOption1 = getFlcOption1();

		eClosingCacheModel.flcOption2 = getFlcOption2();

		eClosingCacheModel.flcStatus = getFlcStatus();

		String flcStatus = eClosingCacheModel.flcStatus;

		if ((flcStatus != null) && (flcStatus.length() == 0)) {
			eClosingCacheModel.flcStatus = null;
		}

		eClosingCacheModel.flcComments = getFlcComments();

		String flcComments = eClosingCacheModel.flcComments;

		if ((flcComments != null) && (flcComments.length() == 0)) {
			eClosingCacheModel.flcComments = null;
		}

		eClosingCacheModel.securityOption1 = getSecurityOption1();

		eClosingCacheModel.securityFinanceFee = getSecurityFinanceFee();

		eClosingCacheModel.securityStatus = getSecurityStatus();

		String securityStatus = eClosingCacheModel.securityStatus;

		if ((securityStatus != null) && (securityStatus.length() == 0)) {
			eClosingCacheModel.securityStatus = null;
		}

		eClosingCacheModel.securityComments = getSecurityComments();

		String securityComments = eClosingCacheModel.securityComments;

		if ((securityComments != null) && (securityComments.length() == 0)) {
			eClosingCacheModel.securityComments = null;
		}

		eClosingCacheModel.idOption1 = getIdOption1();

		eClosingCacheModel.idOption2 = getIdOption2();

		eClosingCacheModel.idOption3 = getIdOption3();

		eClosingCacheModel.idOption4 = getIdOption4();

		eClosingCacheModel.idOption5 = getIdOption5();

		eClosingCacheModel.idOption6 = getIdOption6();

		eClosingCacheModel.idOption7 = getIdOption7();

		eClosingCacheModel.idOption8 = getIdOption8();

		eClosingCacheModel.idOption9 = getIdOption9();

		eClosingCacheModel.idHrFee = getIdHrFee();

		eClosingCacheModel.idFinanceFee = getIdFinanceFee();

		eClosingCacheModel.idStatus = getIdStatus();

		String idStatus = eClosingCacheModel.idStatus;

		if ((idStatus != null) && (idStatus.length() == 0)) {
			eClosingCacheModel.idStatus = null;
		}

		eClosingCacheModel.idComments = getIdComments();

		String idComments = eClosingCacheModel.idComments;

		if ((idComments != null) && (idComments.length() == 0)) {
			eClosingCacheModel.idComments = null;
		}

		eClosingCacheModel.htdOption1 = getHtdOption1();

		eClosingCacheModel.htdHrFee = getHtdHrFee();

		eClosingCacheModel.htdFinanceFee = getHtdFinanceFee();

		eClosingCacheModel.htdStatus = getHtdStatus();

		String htdStatus = eClosingCacheModel.htdStatus;

		if ((htdStatus != null) && (htdStatus.length() == 0)) {
			eClosingCacheModel.htdStatus = null;
		}

		eClosingCacheModel.htdComments = getHtdComments();

		String htdComments = eClosingCacheModel.htdComments;

		if ((htdComments != null) && (htdComments.length() == 0)) {
			eClosingCacheModel.htdComments = null;
		}

		eClosingCacheModel.hdOption1 = getHdOption1();

		eClosingCacheModel.hdOption2 = getHdOption2();

		eClosingCacheModel.hdOption2Text = getHdOption2Text();

		String hdOption2Text = eClosingCacheModel.hdOption2Text;

		if ((hdOption2Text != null) && (hdOption2Text.length() == 0)) {
			eClosingCacheModel.hdOption2Text = null;
		}

		eClosingCacheModel.hdOption3 = getHdOption3();

		eClosingCacheModel.hdOption3Money = getHdOption3Money();

		eClosingCacheModel.hdOption4 = getHdOption4();

		eClosingCacheModel.hdOption4Money = getHdOption4Money();

		eClosingCacheModel.hdStatus = getHdStatus();

		String hdStatus = eClosingCacheModel.hdStatus;

		if ((hdStatus != null) && (hdStatus.length() == 0)) {
			eClosingCacheModel.hdStatus = null;
		}

		eClosingCacheModel.hdComments = getHdComments();

		String hdComments = eClosingCacheModel.hdComments;

		if ((hdComments != null) && (hdComments.length() == 0)) {
			eClosingCacheModel.hdComments = null;
		}

		eClosingCacheModel.hdleaveText = getHdleaveText();

		String hdleaveText = eClosingCacheModel.hdleaveText;

		if ((hdleaveText != null) && (hdleaveText.length() == 0)) {
			eClosingCacheModel.hdleaveText = null;
		}

		eClosingCacheModel.fdOption1 = getFdOption1();

		eClosingCacheModel.fdOption2 = getFdOption2();

		eClosingCacheModel.fdOption3 = getFdOption3();

		eClosingCacheModel.fdOption4 = getFdOption4();

		eClosingCacheModel.fdOption4Text = getFdOption4Text();

		String fdOption4Text = eClosingCacheModel.fdOption4Text;

		if ((fdOption4Text != null) && (fdOption4Text.length() == 0)) {
			eClosingCacheModel.fdOption4Text = null;
		}

		eClosingCacheModel.fdStatus = getFdStatus();

		String fdStatus = eClosingCacheModel.fdStatus;

		if ((fdStatus != null) && (fdStatus.length() == 0)) {
			eClosingCacheModel.fdStatus = null;
		}

		eClosingCacheModel.fdComments = getFdComments();

		String fdComments = eClosingCacheModel.fdComments;

		if ((fdComments != null) && (fdComments.length() == 0)) {
			eClosingCacheModel.fdComments = null;
		}

		eClosingCacheModel.applicantAgent = getApplicantAgent();

		eClosingCacheModel.approverAgent = getApproverAgent();

		eClosingCacheModel.processType = getProcessType();

		String processType = eClosingCacheModel.processType;

		if ((processType != null) && (processType.length() == 0)) {
			eClosingCacheModel.processType = null;
		}

		eClosingCacheModel.subProcessType = getSubProcessType();

		String subProcessType = eClosingCacheModel.subProcessType;

		if ((subProcessType != null) && (subProcessType.length() == 0)) {
			eClosingCacheModel.subProcessType = null;
		}

		eClosingCacheModel.status = getStatus();

		eClosingCacheModel.statusByUserId = getStatusByUserId();

		eClosingCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = eClosingCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			eClosingCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			eClosingCacheModel.statusDate = statusDate.getTime();
		}
		else {
			eClosingCacheModel.statusDate = Long.MIN_VALUE;
		}

		return eClosingCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(179);

		sb.append("{eclosingId=");
		sb.append(getEclosingId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", ticketNo=");
		sb.append(getTicketNo());
		sb.append(", staffCode=");
		sb.append(getStaffCode());
		sb.append(", staffName=");
		sb.append(getStaffName());
		sb.append(", company=");
		sb.append(getCompany());
		sb.append(", division=");
		sb.append(getDivision());
		sb.append(", department=");
		sb.append(getDepartment());
		sb.append(", costCenter=");
		sb.append(getCostCenter());
		sb.append(", functionName=");
		sb.append(getFunctionName());
		sb.append(", positionCode=");
		sb.append(getPositionCode());
		sb.append(", employeeGroupId=");
		sb.append(getEmployeeGroupId());
		sb.append(", employeeGroupName=");
		sb.append(getEmployeeGroupName());
		sb.append(", privateEmailAddress=");
		sb.append(getPrivateEmailAddress());
		sb.append(", startingDate=");
		sb.append(getStartingDate());
		sb.append(", lastWorkingDay=");
		sb.append(getLastWorkingDay());
		sb.append(", finishContractDate=");
		sb.append(getFinishContractDate());
		sb.append(", seatOfficeNumber=");
		sb.append(getSeatOfficeNumber());
		sb.append(", permanentAddress=");
		sb.append(getPermanentAddress());
		sb.append(", dmOption1=");
		sb.append(getDmOption1());
		sb.append(", dmOption2=");
		sb.append(getDmOption2());
		sb.append(", dmStatus=");
		sb.append(getDmStatus());
		sb.append(", dmComments=");
		sb.append(getDmComments());
		sb.append(", adOption1=");
		sb.append(getAdOption1());
		sb.append(", adOption2=");
		sb.append(getAdOption2());
		sb.append(", adOption3=");
		sb.append(getAdOption3());
		sb.append(", adOption4=");
		sb.append(getAdOption4());
		sb.append(", adFinanceFee=");
		sb.append(getAdFinanceFee());
		sb.append(", adStatus=");
		sb.append(getAdStatus());
		sb.append(", adComments=");
		sb.append(getAdComments());
		sb.append(", fsOption1=");
		sb.append(getFsOption1());
		sb.append(", fsStatus=");
		sb.append(getFsStatus());
		sb.append(", fsComments=");
		sb.append(getFsComments());
		sb.append(", flcOption1=");
		sb.append(getFlcOption1());
		sb.append(", flcOption2=");
		sb.append(getFlcOption2());
		sb.append(", flcStatus=");
		sb.append(getFlcStatus());
		sb.append(", flcComments=");
		sb.append(getFlcComments());
		sb.append(", securityOption1=");
		sb.append(getSecurityOption1());
		sb.append(", securityFinanceFee=");
		sb.append(getSecurityFinanceFee());
		sb.append(", securityStatus=");
		sb.append(getSecurityStatus());
		sb.append(", securityComments=");
		sb.append(getSecurityComments());
		sb.append(", idOption1=");
		sb.append(getIdOption1());
		sb.append(", idOption2=");
		sb.append(getIdOption2());
		sb.append(", idOption3=");
		sb.append(getIdOption3());
		sb.append(", idOption4=");
		sb.append(getIdOption4());
		sb.append(", idOption5=");
		sb.append(getIdOption5());
		sb.append(", idOption6=");
		sb.append(getIdOption6());
		sb.append(", idOption7=");
		sb.append(getIdOption7());
		sb.append(", idOption8=");
		sb.append(getIdOption8());
		sb.append(", idOption9=");
		sb.append(getIdOption9());
		sb.append(", idHrFee=");
		sb.append(getIdHrFee());
		sb.append(", idFinanceFee=");
		sb.append(getIdFinanceFee());
		sb.append(", idStatus=");
		sb.append(getIdStatus());
		sb.append(", idComments=");
		sb.append(getIdComments());
		sb.append(", htdOption1=");
		sb.append(getHtdOption1());
		sb.append(", htdHrFee=");
		sb.append(getHtdHrFee());
		sb.append(", htdFinanceFee=");
		sb.append(getHtdFinanceFee());
		sb.append(", htdStatus=");
		sb.append(getHtdStatus());
		sb.append(", htdComments=");
		sb.append(getHtdComments());
		sb.append(", hdOption1=");
		sb.append(getHdOption1());
		sb.append(", hdOption2=");
		sb.append(getHdOption2());
		sb.append(", hdOption2Text=");
		sb.append(getHdOption2Text());
		sb.append(", hdOption3=");
		sb.append(getHdOption3());
		sb.append(", hdOption3Money=");
		sb.append(getHdOption3Money());
		sb.append(", hdOption4=");
		sb.append(getHdOption4());
		sb.append(", hdOption4Money=");
		sb.append(getHdOption4Money());
		sb.append(", hdStatus=");
		sb.append(getHdStatus());
		sb.append(", hdComments=");
		sb.append(getHdComments());
		sb.append(", hdleaveText=");
		sb.append(getHdleaveText());
		sb.append(", fdOption1=");
		sb.append(getFdOption1());
		sb.append(", fdOption2=");
		sb.append(getFdOption2());
		sb.append(", fdOption3=");
		sb.append(getFdOption3());
		sb.append(", fdOption4=");
		sb.append(getFdOption4());
		sb.append(", fdOption4Text=");
		sb.append(getFdOption4Text());
		sb.append(", fdStatus=");
		sb.append(getFdStatus());
		sb.append(", fdComments=");
		sb.append(getFdComments());
		sb.append(", applicantAgent=");
		sb.append(getApplicantAgent());
		sb.append(", approverAgent=");
		sb.append(getApproverAgent());
		sb.append(", processType=");
		sb.append(getProcessType());
		sb.append(", subProcessType=");
		sb.append(getSubProcessType());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", statusByUserId=");
		sb.append(getStatusByUserId());
		sb.append(", statusByUserName=");
		sb.append(getStatusByUserName());
		sb.append(", statusDate=");
		sb.append(getStatusDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(271);

		sb.append("<model><model-name>");
		sb.append("com.e.closing.model.EClosing");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>eclosingId</column-name><column-value><![CDATA[");
		sb.append(getEclosingId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ticketNo</column-name><column-value><![CDATA[");
		sb.append(getTicketNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>staffCode</column-name><column-value><![CDATA[");
		sb.append(getStaffCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>staffName</column-name><column-value><![CDATA[");
		sb.append(getStaffName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>company</column-name><column-value><![CDATA[");
		sb.append(getCompany());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>division</column-name><column-value><![CDATA[");
		sb.append(getDivision());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>department</column-name><column-value><![CDATA[");
		sb.append(getDepartment());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>costCenter</column-name><column-value><![CDATA[");
		sb.append(getCostCenter());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>functionName</column-name><column-value><![CDATA[");
		sb.append(getFunctionName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>positionCode</column-name><column-value><![CDATA[");
		sb.append(getPositionCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>employeeGroupId</column-name><column-value><![CDATA[");
		sb.append(getEmployeeGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>employeeGroupName</column-name><column-value><![CDATA[");
		sb.append(getEmployeeGroupName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>privateEmailAddress</column-name><column-value><![CDATA[");
		sb.append(getPrivateEmailAddress());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>startingDate</column-name><column-value><![CDATA[");
		sb.append(getStartingDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lastWorkingDay</column-name><column-value><![CDATA[");
		sb.append(getLastWorkingDay());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>finishContractDate</column-name><column-value><![CDATA[");
		sb.append(getFinishContractDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>seatOfficeNumber</column-name><column-value><![CDATA[");
		sb.append(getSeatOfficeNumber());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>permanentAddress</column-name><column-value><![CDATA[");
		sb.append(getPermanentAddress());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dmOption1</column-name><column-value><![CDATA[");
		sb.append(getDmOption1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dmOption2</column-name><column-value><![CDATA[");
		sb.append(getDmOption2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dmStatus</column-name><column-value><![CDATA[");
		sb.append(getDmStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dmComments</column-name><column-value><![CDATA[");
		sb.append(getDmComments());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>adOption1</column-name><column-value><![CDATA[");
		sb.append(getAdOption1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>adOption2</column-name><column-value><![CDATA[");
		sb.append(getAdOption2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>adOption3</column-name><column-value><![CDATA[");
		sb.append(getAdOption3());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>adOption4</column-name><column-value><![CDATA[");
		sb.append(getAdOption4());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>adFinanceFee</column-name><column-value><![CDATA[");
		sb.append(getAdFinanceFee());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>adStatus</column-name><column-value><![CDATA[");
		sb.append(getAdStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>adComments</column-name><column-value><![CDATA[");
		sb.append(getAdComments());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fsOption1</column-name><column-value><![CDATA[");
		sb.append(getFsOption1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fsStatus</column-name><column-value><![CDATA[");
		sb.append(getFsStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fsComments</column-name><column-value><![CDATA[");
		sb.append(getFsComments());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>flcOption1</column-name><column-value><![CDATA[");
		sb.append(getFlcOption1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>flcOption2</column-name><column-value><![CDATA[");
		sb.append(getFlcOption2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>flcStatus</column-name><column-value><![CDATA[");
		sb.append(getFlcStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>flcComments</column-name><column-value><![CDATA[");
		sb.append(getFlcComments());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>securityOption1</column-name><column-value><![CDATA[");
		sb.append(getSecurityOption1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>securityFinanceFee</column-name><column-value><![CDATA[");
		sb.append(getSecurityFinanceFee());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>securityStatus</column-name><column-value><![CDATA[");
		sb.append(getSecurityStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>securityComments</column-name><column-value><![CDATA[");
		sb.append(getSecurityComments());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idOption1</column-name><column-value><![CDATA[");
		sb.append(getIdOption1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idOption2</column-name><column-value><![CDATA[");
		sb.append(getIdOption2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idOption3</column-name><column-value><![CDATA[");
		sb.append(getIdOption3());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idOption4</column-name><column-value><![CDATA[");
		sb.append(getIdOption4());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idOption5</column-name><column-value><![CDATA[");
		sb.append(getIdOption5());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idOption6</column-name><column-value><![CDATA[");
		sb.append(getIdOption6());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idOption7</column-name><column-value><![CDATA[");
		sb.append(getIdOption7());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idOption8</column-name><column-value><![CDATA[");
		sb.append(getIdOption8());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idOption9</column-name><column-value><![CDATA[");
		sb.append(getIdOption9());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idHrFee</column-name><column-value><![CDATA[");
		sb.append(getIdHrFee());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idFinanceFee</column-name><column-value><![CDATA[");
		sb.append(getIdFinanceFee());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idStatus</column-name><column-value><![CDATA[");
		sb.append(getIdStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idComments</column-name><column-value><![CDATA[");
		sb.append(getIdComments());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>htdOption1</column-name><column-value><![CDATA[");
		sb.append(getHtdOption1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>htdHrFee</column-name><column-value><![CDATA[");
		sb.append(getHtdHrFee());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>htdFinanceFee</column-name><column-value><![CDATA[");
		sb.append(getHtdFinanceFee());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>htdStatus</column-name><column-value><![CDATA[");
		sb.append(getHtdStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>htdComments</column-name><column-value><![CDATA[");
		sb.append(getHtdComments());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hdOption1</column-name><column-value><![CDATA[");
		sb.append(getHdOption1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hdOption2</column-name><column-value><![CDATA[");
		sb.append(getHdOption2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hdOption2Text</column-name><column-value><![CDATA[");
		sb.append(getHdOption2Text());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hdOption3</column-name><column-value><![CDATA[");
		sb.append(getHdOption3());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hdOption3Money</column-name><column-value><![CDATA[");
		sb.append(getHdOption3Money());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hdOption4</column-name><column-value><![CDATA[");
		sb.append(getHdOption4());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hdOption4Money</column-name><column-value><![CDATA[");
		sb.append(getHdOption4Money());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hdStatus</column-name><column-value><![CDATA[");
		sb.append(getHdStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hdComments</column-name><column-value><![CDATA[");
		sb.append(getHdComments());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hdleaveText</column-name><column-value><![CDATA[");
		sb.append(getHdleaveText());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fdOption1</column-name><column-value><![CDATA[");
		sb.append(getFdOption1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fdOption2</column-name><column-value><![CDATA[");
		sb.append(getFdOption2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fdOption3</column-name><column-value><![CDATA[");
		sb.append(getFdOption3());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fdOption4</column-name><column-value><![CDATA[");
		sb.append(getFdOption4());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fdOption4Text</column-name><column-value><![CDATA[");
		sb.append(getFdOption4Text());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fdStatus</column-name><column-value><![CDATA[");
		sb.append(getFdStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fdComments</column-name><column-value><![CDATA[");
		sb.append(getFdComments());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>applicantAgent</column-name><column-value><![CDATA[");
		sb.append(getApplicantAgent());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>approverAgent</column-name><column-value><![CDATA[");
		sb.append(getApproverAgent());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>processType</column-name><column-value><![CDATA[");
		sb.append(getProcessType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>subProcessType</column-name><column-value><![CDATA[");
		sb.append(getSubProcessType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserId</column-name><column-value><![CDATA[");
		sb.append(getStatusByUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserName</column-name><column-value><![CDATA[");
		sb.append(getStatusByUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusDate</column-name><column-value><![CDATA[");
		sb.append(getStatusDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = EClosing.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			EClosing.class
		};
	private long _eclosingId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _ticketNo;
	private int _staffCode;
	private String _staffName;
	private String _company;
	private String _division;
	private String _department;
	private String _costCenter;
	private String _functionName;
	private String _positionCode;
	private String _employeeGroupId;
	private String _employeeGroupName;
	private String _privateEmailAddress;
	private Date _startingDate;
	private Date _lastWorkingDay;
	private Date _finishContractDate;
	private String _seatOfficeNumber;
	private String _permanentAddress;
	private boolean _dmOption1;
	private boolean _dmOption2;
	private String _dmStatus;
	private String _dmComments;
	private boolean _adOption1;
	private boolean _adOption2;
	private boolean _adOption3;
	private boolean _adOption4;
	private double _adFinanceFee;
	private String _adStatus;
	private String _adComments;
	private boolean _fsOption1;
	private String _fsStatus;
	private String _fsComments;
	private boolean _flcOption1;
	private boolean _flcOption2;
	private String _flcStatus;
	private String _flcComments;
	private boolean _securityOption1;
	private double _securityFinanceFee;
	private String _securityStatus;
	private String _securityComments;
	private boolean _idOption1;
	private boolean _idOption2;
	private boolean _idOption3;
	private boolean _idOption4;
	private boolean _idOption5;
	private boolean _idOption6;
	private boolean _idOption7;
	private boolean _idOption8;
	private boolean _idOption9;
	private double _idHrFee;
	private double _idFinanceFee;
	private String _idStatus;
	private String _idComments;
	private boolean _htdOption1;
	private double _htdHrFee;
	private double _htdFinanceFee;
	private String _htdStatus;
	private String _htdComments;
	private boolean _hdOption1;
	private boolean _hdOption2;
	private String _hdOption2Text;
	private boolean _hdOption3;
	private double _hdOption3Money;
	private boolean _hdOption4;
	private double _hdOption4Money;
	private String _hdStatus;
	private String _hdComments;
	private String _hdleaveText;
	private boolean _fdOption1;
	private boolean _fdOption2;
	private boolean _fdOption3;
	private boolean _fdOption4;
	private String _fdOption4Text;
	private String _fdStatus;
	private String _fdComments;
	private boolean _applicantAgent;
	private boolean _approverAgent;
	private String _processType;
	private String _subProcessType;
	private int _status;
	private int _originalStatus;
	private boolean _setOriginalStatus;
	private long _statusByUserId;
	private String _statusByUserUuid;
	private String _statusByUserName;
	private Date _statusDate;
	private long _columnBitmask;
	private EClosing _escapedModel;
}