/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.e.onboarding.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Distribution service. Represents a row in the &quot;vgcapon_Distribution&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.e.onboarding.model.impl.DistributionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.e.onboarding.model.impl.DistributionImpl}.
 * </p>
 *
 * @author sanguine
 * @see Distribution
 * @see com.e.onboarding.model.impl.DistributionImpl
 * @see com.e.onboarding.model.impl.DistributionModelImpl
 * @generated
 */
public interface DistributionModel extends BaseModel<Distribution>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a distribution model instance should use the {@link Distribution} interface instead.
	 */

	/**
	 * Returns the primary key of this distribution.
	 *
	 * @return the primary key of this distribution
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this distribution.
	 *
	 * @param primaryKey the primary key of this distribution
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the distribution ID of this distribution.
	 *
	 * @return the distribution ID of this distribution
	 */
	public long getDistributionId();

	/**
	 * Sets the distribution ID of this distribution.
	 *
	 * @param distributionId the distribution ID of this distribution
	 */
	public void setDistributionId(long distributionId);

	/**
	 * Returns the group ID of this distribution.
	 *
	 * @return the group ID of this distribution
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this distribution.
	 *
	 * @param groupId the group ID of this distribution
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this distribution.
	 *
	 * @return the company ID of this distribution
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this distribution.
	 *
	 * @param companyId the company ID of this distribution
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this distribution.
	 *
	 * @return the user ID of this distribution
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this distribution.
	 *
	 * @param userId the user ID of this distribution
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this distribution.
	 *
	 * @return the user uuid of this distribution
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this distribution.
	 *
	 * @param userUuid the user uuid of this distribution
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this distribution.
	 *
	 * @return the user name of this distribution
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this distribution.
	 *
	 * @param userName the user name of this distribution
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this distribution.
	 *
	 * @return the create date of this distribution
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this distribution.
	 *
	 * @param createDate the create date of this distribution
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this distribution.
	 *
	 * @return the modified date of this distribution
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this distribution.
	 *
	 * @param modifiedDate the modified date of this distribution
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the email address of this distribution.
	 *
	 * @return the email address of this distribution
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this distribution.
	 *
	 * @param emailAddress the email address of this distribution
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Returns the name of this distribution.
	 *
	 * @return the name of this distribution
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this distribution.
	 *
	 * @param name the name of this distribution
	 */
	public void setName(String name);

	/**
	 * Returns the comments of this distribution.
	 *
	 * @return the comments of this distribution
	 */
	@AutoEscape
	public String getComments();

	/**
	 * Sets the comments of this distribution.
	 *
	 * @param comments the comments of this distribution
	 */
	public void setComments(String comments);

	/**
	 * Returns the type of this distribution.
	 *
	 * @return the type of this distribution
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this distribution.
	 *
	 * @param type the type of this distribution
	 */
	public void setType(String type);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.e.onboarding.model.Distribution distribution);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.e.onboarding.model.Distribution> toCacheModel();

	@Override
	public com.e.onboarding.model.Distribution toEscapedModel();

	@Override
	public com.e.onboarding.model.Distribution toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}