/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.e.onboarding.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.model.WorkflowedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EOnBoarding service. Represents a row in the &quot;vgcapon_EOnBoarding&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.e.onboarding.model.impl.EOnBoardingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.e.onboarding.model.impl.EOnBoardingImpl}.
 * </p>
 *
 * @author sanguine
 * @see EOnBoarding
 * @see com.e.onboarding.model.impl.EOnBoardingImpl
 * @see com.e.onboarding.model.impl.EOnBoardingModelImpl
 * @generated
 */
public interface EOnBoardingModel extends BaseModel<EOnBoarding>, GroupedModel,
	WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e on boarding model instance should use the {@link EOnBoarding} interface instead.
	 */

	/**
	 * Returns the primary key of this e on boarding.
	 *
	 * @return the primary key of this e on boarding
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e on boarding.
	 *
	 * @param primaryKey the primary key of this e on boarding
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the e on boarding ID of this e on boarding.
	 *
	 * @return the e on boarding ID of this e on boarding
	 */
	public long getEOnBoardingId();

	/**
	 * Sets the e on boarding ID of this e on boarding.
	 *
	 * @param eOnBoardingId the e on boarding ID of this e on boarding
	 */
	public void setEOnBoardingId(long eOnBoardingId);

	/**
	 * Returns the ticket no of this e on boarding.
	 *
	 * @return the ticket no of this e on boarding
	 */
	@AutoEscape
	public String getTicketNo();

	/**
	 * Sets the ticket no of this e on boarding.
	 *
	 * @param ticketNo the ticket no of this e on boarding
	 */
	public void setTicketNo(String ticketNo);

	/**
	 * Returns the process type of this e on boarding.
	 *
	 * @return the process type of this e on boarding
	 */
	@AutoEscape
	public String getProcessType();

	/**
	 * Sets the process type of this e on boarding.
	 *
	 * @param processType the process type of this e on boarding
	 */
	public void setProcessType(String processType);

	/**
	 * Returns the sub type of this e on boarding.
	 *
	 * @return the sub type of this e on boarding
	 */
	@AutoEscape
	public String getSubType();

	/**
	 * Sets the sub type of this e on boarding.
	 *
	 * @param subType the sub type of this e on boarding
	 */
	public void setSubType(String subType);

	/**
	 * Returns the group ID of this e on boarding.
	 *
	 * @return the group ID of this e on boarding
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this e on boarding.
	 *
	 * @param groupId the group ID of this e on boarding
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this e on boarding.
	 *
	 * @return the company ID of this e on boarding
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this e on boarding.
	 *
	 * @param companyId the company ID of this e on boarding
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this e on boarding.
	 *
	 * @return the user ID of this e on boarding
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this e on boarding.
	 *
	 * @param userId the user ID of this e on boarding
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this e on boarding.
	 *
	 * @return the user uuid of this e on boarding
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this e on boarding.
	 *
	 * @param userUuid the user uuid of this e on boarding
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this e on boarding.
	 *
	 * @return the user name of this e on boarding
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this e on boarding.
	 *
	 * @param userName the user name of this e on boarding
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this e on boarding.
	 *
	 * @return the create date of this e on boarding
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this e on boarding.
	 *
	 * @param createDate the create date of this e on boarding
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this e on boarding.
	 *
	 * @return the modified date of this e on boarding
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this e on boarding.
	 *
	 * @param modifiedDate the modified date of this e on boarding
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the submitted date of this e on boarding.
	 *
	 * @return the submitted date of this e on boarding
	 */
	public Date getSubmittedDate();

	/**
	 * Sets the submitted date of this e on boarding.
	 *
	 * @param submittedDate the submitted date of this e on boarding
	 */
	public void setSubmittedDate(Date submittedDate);

	/**
	 * Returns the modified user ID of this e on boarding.
	 *
	 * @return the modified user ID of this e on boarding
	 */
	public long getModifiedUserId();

	/**
	 * Sets the modified user ID of this e on boarding.
	 *
	 * @param modifiedUserId the modified user ID of this e on boarding
	 */
	public void setModifiedUserId(long modifiedUserId);

	/**
	 * Returns the modified user uuid of this e on boarding.
	 *
	 * @return the modified user uuid of this e on boarding
	 * @throws SystemException if a system exception occurred
	 */
	public String getModifiedUserUuid() throws SystemException;

	/**
	 * Sets the modified user uuid of this e on boarding.
	 *
	 * @param modifiedUserUuid the modified user uuid of this e on boarding
	 */
	public void setModifiedUserUuid(String modifiedUserUuid);

	/**
	 * Returns the modified user name of this e on boarding.
	 *
	 * @return the modified user name of this e on boarding
	 */
	@AutoEscape
	public String getModifiedUserName();

	/**
	 * Sets the modified user name of this e on boarding.
	 *
	 * @param modifiedUserName the modified user name of this e on boarding
	 */
	public void setModifiedUserName(String modifiedUserName);

	/**
	 * Returns the status of this e on boarding.
	 *
	 * @return the status of this e on boarding
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this e on boarding.
	 *
	 * @param status the status of this e on boarding
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this e on boarding.
	 *
	 * @return the status by user ID of this e on boarding
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this e on boarding.
	 *
	 * @param statusByUserId the status by user ID of this e on boarding
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this e on boarding.
	 *
	 * @return the status by user uuid of this e on boarding
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getStatusByUserUuid() throws SystemException;

	/**
	 * Sets the status by user uuid of this e on boarding.
	 *
	 * @param statusByUserUuid the status by user uuid of this e on boarding
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this e on boarding.
	 *
	 * @return the status by user name of this e on boarding
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this e on boarding.
	 *
	 * @param statusByUserName the status by user name of this e on boarding
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this e on boarding.
	 *
	 * @return the status date of this e on boarding
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this e on boarding.
	 *
	 * @param statusDate the status date of this e on boarding
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the staff code of this e on boarding.
	 *
	 * @return the staff code of this e on boarding
	 */
	@AutoEscape
	public String getStaffCode();

	/**
	 * Sets the staff code of this e on boarding.
	 *
	 * @param staffCode the staff code of this e on boarding
	 */
	public void setStaffCode(String staffCode);

	/**
	 * Returns the last name of this e on boarding.
	 *
	 * @return the last name of this e on boarding
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this e on boarding.
	 *
	 * @param lastName the last name of this e on boarding
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the first name of this e on boarding.
	 *
	 * @return the first name of this e on boarding
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this e on boarding.
	 *
	 * @param firstName the first name of this e on boarding
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the name of this e on boarding.
	 *
	 * @return the name of this e on boarding
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this e on boarding.
	 *
	 * @param name the name of this e on boarding
	 */
	public void setName(String name);

	/**
	 * Returns the gender of this e on boarding.
	 *
	 * @return the gender of this e on boarding
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this e on boarding.
	 *
	 * @param gender the gender of this e on boarding
	 */
	public void setGender(String gender);

	/**
	 * Returns the birthday of this e on boarding.
	 *
	 * @return the birthday of this e on boarding
	 */
	public Date getBirthday();

	/**
	 * Sets the birthday of this e on boarding.
	 *
	 * @param birthday the birthday of this e on boarding
	 */
	public void setBirthday(Date birthday);

	/**
	 * Returns the photo path of this e on boarding.
	 *
	 * @return the photo path of this e on boarding
	 */
	@AutoEscape
	public String getPhotoPath();

	/**
	 * Sets the photo path of this e on boarding.
	 *
	 * @param photoPath the photo path of this e on boarding
	 */
	public void setPhotoPath(String photoPath);

	/**
	 * Returns the contract type of this e on boarding.
	 *
	 * @return the contract type of this e on boarding
	 */
	@AutoEscape
	public String getContractType();

	/**
	 * Sets the contract type of this e on boarding.
	 *
	 * @param contractType the contract type of this e on boarding
	 */
	public void setContractType(String contractType);

	/**
	 * Returns the work location of this e on boarding.
	 *
	 * @return the work location of this e on boarding
	 */
	@AutoEscape
	public String getWorkLocation();

	/**
	 * Sets the work location of this e on boarding.
	 *
	 * @param workLocation the work location of this e on boarding
	 */
	public void setWorkLocation(String workLocation);

	/**
	 * Returns the division of this e on boarding.
	 *
	 * @return the division of this e on boarding
	 */
	@AutoEscape
	public String getDivision();

	/**
	 * Sets the division of this e on boarding.
	 *
	 * @param division the division of this e on boarding
	 */
	public void setDivision(String division);

	/**
	 * Returns the office site of this e on boarding.
	 *
	 * @return the office site of this e on boarding
	 */
	@AutoEscape
	public String getOfficeSite();

	/**
	 * Sets the office site of this e on boarding.
	 *
	 * @param officeSite the office site of this e on boarding
	 */
	public void setOfficeSite(String officeSite);

	/**
	 * Returns the department of this e on boarding.
	 *
	 * @return the department of this e on boarding
	 */
	@AutoEscape
	public String getDepartment();

	/**
	 * Sets the department of this e on boarding.
	 *
	 * @param department the department of this e on boarding
	 */
	public void setDepartment(String department);

	/**
	 * Returns the starting date of this e on boarding.
	 *
	 * @return the starting date of this e on boarding
	 */
	public Date getStartingDate();

	/**
	 * Sets the starting date of this e on boarding.
	 *
	 * @param startingDate the starting date of this e on boarding
	 */
	public void setStartingDate(Date startingDate);

	/**
	 * Returns the position code of this e on boarding.
	 *
	 * @return the position code of this e on boarding
	 */
	@AutoEscape
	public String getPositionCode();

	/**
	 * Sets the position code of this e on boarding.
	 *
	 * @param positionCode the position code of this e on boarding
	 */
	public void setPositionCode(String positionCode);

	/**
	 * Returns the service length of this e on boarding.
	 *
	 * @return the service length of this e on boarding
	 */
	@AutoEscape
	public String getServiceLength();

	/**
	 * Sets the service length of this e on boarding.
	 *
	 * @param serviceLength the service length of this e on boarding
	 */
	public void setServiceLength(String serviceLength);

	/**
	 * Returns the function name of this e on boarding.
	 *
	 * @return the function name of this e on boarding
	 */
	@AutoEscape
	public String getFunctionName();

	/**
	 * Sets the function name of this e on boarding.
	 *
	 * @param functionName the function name of this e on boarding
	 */
	public void setFunctionName(String functionName);

	/**
	 * Returns the report to of this e on boarding.
	 *
	 * @return the report to of this e on boarding
	 */
	@AutoEscape
	public String getReportTo();

	/**
	 * Sets the report to of this e on boarding.
	 *
	 * @param reportTo the report to of this e on boarding
	 */
	public void setReportTo(String reportTo);

	/**
	 * Returns the report to staff name of this e on boarding.
	 *
	 * @return the report to staff name of this e on boarding
	 */
	@AutoEscape
	public String getReportToStaffName();

	/**
	 * Sets the report to staff name of this e on boarding.
	 *
	 * @param reportToStaffName the report to staff name of this e on boarding
	 */
	public void setReportToStaffName(String reportToStaffName);

	/**
	 * Returns the title of this e on boarding.
	 *
	 * @return the title of this e on boarding
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this e on boarding.
	 *
	 * @param title the title of this e on boarding
	 */
	public void setTitle(String title);

	/**
	 * Returns the cost center of this e on boarding.
	 *
	 * @return the cost center of this e on boarding
	 */
	@AutoEscape
	public String getCostCenter();

	/**
	 * Sets the cost center of this e on boarding.
	 *
	 * @param costCenter the cost center of this e on boarding
	 */
	public void setCostCenter(String costCenter);

	/**
	 * Returns the it related hardware of this e on boarding.
	 *
	 * @return the it related hardware of this e on boarding
	 */
	public boolean getItRelatedHardware();

	/**
	 * Returns <code>true</code> if this e on boarding is it related hardware.
	 *
	 * @return <code>true</code> if this e on boarding is it related hardware; <code>false</code> otherwise
	 */
	public boolean isItRelatedHardware();

	/**
	 * Sets whether this e on boarding is it related hardware.
	 *
	 * @param itRelatedHardware the it related hardware of this e on boarding
	 */
	public void setItRelatedHardware(boolean itRelatedHardware);

	/**
	 * Returns the company car of this e on boarding.
	 *
	 * @return the company car of this e on boarding
	 */
	public boolean getCompanyCar();

	/**
	 * Returns <code>true</code> if this e on boarding is company car.
	 *
	 * @return <code>true</code> if this e on boarding is company car; <code>false</code> otherwise
	 */
	public boolean isCompanyCar();

	/**
	 * Sets whether this e on boarding is company car.
	 *
	 * @param companyCar the company car of this e on boarding
	 */
	public void setCompanyCar(boolean companyCar);

	/**
	 * Returns the replacement of this e on boarding.
	 *
	 * @return the replacement of this e on boarding
	 */
	public boolean getReplacement();

	/**
	 * Returns <code>true</code> if this e on boarding is replacement.
	 *
	 * @return <code>true</code> if this e on boarding is replacement; <code>false</code> otherwise
	 */
	public boolean isReplacement();

	/**
	 * Sets whether this e on boarding is replacement.
	 *
	 * @param replacement the replacement of this e on boarding
	 */
	public void setReplacement(boolean replacement);

	/**
	 * Returns the name of replaced person of this e on boarding.
	 *
	 * @return the name of replaced person of this e on boarding
	 */
	@AutoEscape
	public String getNameOfReplacedPerson();

	/**
	 * Sets the name of replaced person of this e on boarding.
	 *
	 * @param nameOfReplacedPerson the name of replaced person of this e on boarding
	 */
	public void setNameOfReplacedPerson(String nameOfReplacedPerson);

	/**
	 * Returns the contact info of this e on boarding.
	 *
	 * @return the contact info of this e on boarding
	 */
	@AutoEscape
	public String getContactInfo();

	/**
	 * Sets the contact info of this e on boarding.
	 *
	 * @param contactInfo the contact info of this e on boarding
	 */
	public void setContactInfo(String contactInfo);

	/**
	 * Returns the comments of this e on boarding.
	 *
	 * @return the comments of this e on boarding
	 */
	@AutoEscape
	public String getComments();

	/**
	 * Sets the comments of this e on boarding.
	 *
	 * @param comments the comments of this e on boarding
	 */
	public void setComments(String comments);

	/**
	 * Returns the is applicant agent of this e on boarding.
	 *
	 * @return the is applicant agent of this e on boarding
	 */
	public boolean getIsApplicantAgent();

	/**
	 * Returns <code>true</code> if this e on boarding is is applicant agent.
	 *
	 * @return <code>true</code> if this e on boarding is is applicant agent; <code>false</code> otherwise
	 */
	public boolean isIsApplicantAgent();

	/**
	 * Sets whether this e on boarding is is applicant agent.
	 *
	 * @param isApplicantAgent the is applicant agent of this e on boarding
	 */
	public void setIsApplicantAgent(boolean isApplicantAgent);

	/**
	 * Returns the is approver agent of this e on boarding.
	 *
	 * @return the is approver agent of this e on boarding
	 */
	public boolean getIsApproverAgent();

	/**
	 * Returns <code>true</code> if this e on boarding is is approver agent.
	 *
	 * @return <code>true</code> if this e on boarding is is approver agent; <code>false</code> otherwise
	 */
	public boolean isIsApproverAgent();

	/**
	 * Sets whether this e on boarding is is approver agent.
	 *
	 * @param isApproverAgent the is approver agent of this e on boarding
	 */
	public void setIsApproverAgent(boolean isApproverAgent);

	/**
	 * Returns the admin entitlement of this e on boarding.
	 *
	 * @return the admin entitlement of this e on boarding
	 */
	@AutoEscape
	public String getAdminEntitlement();

	/**
	 * Sets the admin entitlement of this e on boarding.
	 *
	 * @param adminEntitlement the admin entitlement of this e on boarding
	 */
	public void setAdminEntitlement(String adminEntitlement);

	/**
	 * Returns the admin seat no of this e on boarding.
	 *
	 * @return the admin seat no of this e on boarding
	 */
	@AutoEscape
	public String getAdminSeatNo();

	/**
	 * Sets the admin seat no of this e on boarding.
	 *
	 * @param adminSeatNo the admin seat no of this e on boarding
	 */
	public void setAdminSeatNo(String adminSeatNo);

	/**
	 * Returns the admin tasks of this e on boarding.
	 *
	 * @return the admin tasks of this e on boarding
	 */
	@AutoEscape
	public String getAdminTasks();

	/**
	 * Sets the admin tasks of this e on boarding.
	 *
	 * @param adminTasks the admin tasks of this e on boarding
	 */
	public void setAdminTasks(String adminTasks);

	/**
	 * Returns the admin status of this e on boarding.
	 *
	 * @return the admin status of this e on boarding
	 */
	@AutoEscape
	public String getAdminStatus();

	/**
	 * Sets the admin status of this e on boarding.
	 *
	 * @param adminStatus the admin status of this e on boarding
	 */
	public void setAdminStatus(String adminStatus);

	/**
	 * Returns the admin comments of this e on boarding.
	 *
	 * @return the admin comments of this e on boarding
	 */
	@AutoEscape
	public String getAdminComments();

	/**
	 * Sets the admin comments of this e on boarding.
	 *
	 * @param adminComments the admin comments of this e on boarding
	 */
	public void setAdminComments(String adminComments);

	/**
	 * Returns the security tasks of this e on boarding.
	 *
	 * @return the security tasks of this e on boarding
	 */
	@AutoEscape
	public String getSecurityTasks();

	/**
	 * Sets the security tasks of this e on boarding.
	 *
	 * @param securityTasks the security tasks of this e on boarding
	 */
	public void setSecurityTasks(String securityTasks);

	/**
	 * Returns the security status of this e on boarding.
	 *
	 * @return the security status of this e on boarding
	 */
	@AutoEscape
	public String getSecurityStatus();

	/**
	 * Sets the security status of this e on boarding.
	 *
	 * @param securityStatus the security status of this e on boarding
	 */
	public void setSecurityStatus(String securityStatus);

	/**
	 * Returns the security comments of this e on boarding.
	 *
	 * @return the security comments of this e on boarding
	 */
	@AutoEscape
	public String getSecurityComments();

	/**
	 * Sets the security comments of this e on boarding.
	 *
	 * @param securityComments the security comments of this e on boarding
	 */
	public void setSecurityComments(String securityComments);

	/**
	 * Returns the itp tasks of this e on boarding.
	 *
	 * @return the itp tasks of this e on boarding
	 */
	@AutoEscape
	public String getItpTasks();

	/**
	 * Sets the itp tasks of this e on boarding.
	 *
	 * @param itpTasks the itp tasks of this e on boarding
	 */
	public void setItpTasks(String itpTasks);

	/**
	 * Returns the itp status of this e on boarding.
	 *
	 * @return the itp status of this e on boarding
	 */
	@AutoEscape
	public String getItpStatus();

	/**
	 * Sets the itp status of this e on boarding.
	 *
	 * @param itpStatus the itp status of this e on boarding
	 */
	public void setItpStatus(String itpStatus);

	/**
	 * Returns the ipt comments of this e on boarding.
	 *
	 * @return the ipt comments of this e on boarding
	 */
	@AutoEscape
	public String getIptComments();

	/**
	 * Sets the ipt comments of this e on boarding.
	 *
	 * @param iptComments the ipt comments of this e on boarding
	 */
	public void setIptComments(String iptComments);

	/**
	 * Returns the finance tasks of this e on boarding.
	 *
	 * @return the finance tasks of this e on boarding
	 */
	@AutoEscape
	public String getFinanceTasks();

	/**
	 * Sets the finance tasks of this e on boarding.
	 *
	 * @param financeTasks the finance tasks of this e on boarding
	 */
	public void setFinanceTasks(String financeTasks);

	/**
	 * Returns the finance status of this e on boarding.
	 *
	 * @return the finance status of this e on boarding
	 */
	@AutoEscape
	public String getFinanceStatus();

	/**
	 * Sets the finance status of this e on boarding.
	 *
	 * @param financeStatus the finance status of this e on boarding
	 */
	public void setFinanceStatus(String financeStatus);

	/**
	 * Returns the finance comments of this e on boarding.
	 *
	 * @return the finance comments of this e on boarding
	 */
	@AutoEscape
	public String getFinanceComments();

	/**
	 * Sets the finance comments of this e on boarding.
	 *
	 * @param financeComments the finance comments of this e on boarding
	 */
	public void setFinanceComments(String financeComments);

	/**
	 * @deprecated As of 6.1.0, replaced by {@link #isApproved()}
	 */
	@Override
	public boolean getApproved();

	/**
	 * Returns <code>true</code> if this e on boarding is approved.
	 *
	 * @return <code>true</code> if this e on boarding is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this e on boarding is denied.
	 *
	 * @return <code>true</code> if this e on boarding is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this e on boarding is a draft.
	 *
	 * @return <code>true</code> if this e on boarding is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this e on boarding is expired.
	 *
	 * @return <code>true</code> if this e on boarding is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this e on boarding is inactive.
	 *
	 * @return <code>true</code> if this e on boarding is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this e on boarding is incomplete.
	 *
	 * @return <code>true</code> if this e on boarding is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this e on boarding is pending.
	 *
	 * @return <code>true</code> if this e on boarding is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this e on boarding is scheduled.
	 *
	 * @return <code>true</code> if this e on boarding is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.e.onboarding.model.EOnBoarding eOnBoarding);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.e.onboarding.model.EOnBoarding> toCacheModel();

	@Override
	public com.e.onboarding.model.EOnBoarding toEscapedModel();

	@Override
	public com.e.onboarding.model.EOnBoarding toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}