/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.seatoffice.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import com.seatoffice.model.SeatOffice;

import com.seatoffice.service.SeatOfficeService;
import com.seatoffice.service.persistence.SeatOfficePersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the seat office remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.seatoffice.service.impl.SeatOfficeServiceImpl}.
 * </p>
 *
 * @author Alice.zou
 * @see com.seatoffice.service.impl.SeatOfficeServiceImpl
 * @see com.seatoffice.service.SeatOfficeServiceUtil
 * @generated
 */
public abstract class SeatOfficeServiceBaseImpl extends BaseServiceImpl
	implements SeatOfficeService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.seatoffice.service.SeatOfficeServiceUtil} to access the seat office remote service.
	 */

	/**
	 * Returns the seat office local service.
	 *
	 * @return the seat office local service
	 */
	public com.seatoffice.service.SeatOfficeLocalService getSeatOfficeLocalService() {
		return seatOfficeLocalService;
	}

	/**
	 * Sets the seat office local service.
	 *
	 * @param seatOfficeLocalService the seat office local service
	 */
	public void setSeatOfficeLocalService(
		com.seatoffice.service.SeatOfficeLocalService seatOfficeLocalService) {
		this.seatOfficeLocalService = seatOfficeLocalService;
	}

	/**
	 * Returns the seat office remote service.
	 *
	 * @return the seat office remote service
	 */
	public com.seatoffice.service.SeatOfficeService getSeatOfficeService() {
		return seatOfficeService;
	}

	/**
	 * Sets the seat office remote service.
	 *
	 * @param seatOfficeService the seat office remote service
	 */
	public void setSeatOfficeService(
		com.seatoffice.service.SeatOfficeService seatOfficeService) {
		this.seatOfficeService = seatOfficeService;
	}

	/**
	 * Returns the seat office persistence.
	 *
	 * @return the seat office persistence
	 */
	public SeatOfficePersistence getSeatOfficePersistence() {
		return seatOfficePersistence;
	}

	/**
	 * Sets the seat office persistence.
	 *
	 * @param seatOfficePersistence the seat office persistence
	 */
	public void setSeatOfficePersistence(
		SeatOfficePersistence seatOfficePersistence) {
		this.seatOfficePersistence = seatOfficePersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return SeatOffice.class;
	}

	protected String getModelClassName() {
		return SeatOffice.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = seatOfficePersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.seatoffice.service.SeatOfficeLocalService.class)
	protected com.seatoffice.service.SeatOfficeLocalService seatOfficeLocalService;
	@BeanReference(type = com.seatoffice.service.SeatOfficeService.class)
	protected com.seatoffice.service.SeatOfficeService seatOfficeService;
	@BeanReference(type = SeatOfficePersistence.class)
	protected SeatOfficePersistence seatOfficePersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private SeatOfficeServiceClpInvoker _clpInvoker = new SeatOfficeServiceClpInvoker();
}