create table VgcApon_BtApplication (
	businessTripApplicationId bigint not null primary key,
	ticketNo varchar(75) null,
	processType varchar(75) null,
	subType varchar(75) null,
	printName varchar(75) null,
	staffCode bigint,
	companyName varchar(75) null,
	division varchar(75) null,
	department varchar(75) null,
	costCenter varchar(75) null,
	personalID varchar(75) null,
	passportNo varchar(75) null,
	officePhone varchar(75) null,
	mobilePhone varchar(75) null,
	email varchar(75) null,
	officeSite varchar(75) null,
	approverId bigint,
	approverName varchar(75) null,
	isCrossDepartment boolean,
	targetDepartmentId bigint,
	targetDepartmentName varchar(75) null,
	targetCostCenter varchar(75) null,
	targetDepartmentApproverId bigint,
	targetDepartmentApproverName varchar(75) null,
	tripType integer,
	departureDate date null,
	returnDate date null,
	purposeOfTheTrip varchar(512) null,
	visitCountriesCities varchar(75) null,
	advancePayment double,
	currency_ varchar(75) null,
	paymentMethods varchar(75) null,
	totalCostRmb double,
	totalCostEur double,
	hotelTotalCostRmb double,
	hotelTotalCostEur double,
	carRentalTotalCostRmb double,
	carRentalTotalCostEur double,
	remark varchar(512) null,
	status integer,
	sapStatus integer,
	statusByUserId bigint,
	statusByUserName varchar(75) null,
	statusDate date null,
	isApplicantAgent boolean,
	isApproverAgent boolean,
	groupId bigint,
	userId bigint,
	userName varchar(75) null,
	createDate date null,
	modifiedDate date null,
	submittedDate date null,
	companyId bigint
);

create table VgcApon_BtReimbursement (
	businessTripReimbursementId bigint not null primary key,
	ticketNo varchar(75) null,
	bussinessTirpTicketNo varchar(75) null,
	processType varchar(75) null,
	subType varchar(75) null,
	printName varchar(75) null,
	staffCode bigint,
	companyName varchar(75) null,
	division varchar(75) null,
	department varchar(75) null,
	costCenter varchar(75) null,
	personalID varchar(75) null,
	passportNo varchar(75) null,
	officePhone varchar(75) null,
	mobilePhone varchar(75) null,
	email varchar(75) null,
	officeSite varchar(75) null,
	approverId bigint,
	approverName varchar(75) null,
	isCrossDepartment boolean,
	targetDepartmentId bigint,
	targetDepartmentName varchar(75) null,
	targetCostCenter varchar(75) null,
	targetDepartmentApproverId bigint,
	targetDepartmentApproverName varchar(75) null,
	tripType integer,
	departureDate date null,
	returnDate date null,
	purposeOfTheTrip varchar(512) null,
	visitCountriesCities varchar(75) null,
	advancePayment double,
	currency_ varchar(75) null,
	paymentMethods varchar(75) null,
	totalCostRmb double,
	totalCostEur double,
	hotelTotalCostRmb double,
	hotelTotalCostEur double,
	carRentalTotalCostRmb double,
	carRentalTotalCostEur double,
	totalTravelExpenseRmb double,
	totalTravelExpenseEur double,
	costListInlandTotalRmb double,
	costListForeignTotalEur double,
	costListForeignTotalRmb double,
	remark varchar(512) null,
	status integer,
	sapStatus integer,
	statusByUserId bigint,
	statusByUserName varchar(75) null,
	statusDate date null,
	isApplicantAgent boolean,
	isApproverAgent boolean,
	groupId bigint,
	userId bigint,
	userName varchar(75) null,
	createDate date null,
	modifiedDate date null,
	submittedDate date null,
	companyId bigint
);

create table vgcapon_BtCarRentalInfo (
	btCarRentalInfoId bigint not null primary key,
	businessTripPkId bigint,
	ticketNo varchar(75) null,
	pickupLocation varchar(75) null,
	pickupDate date null,
	dropoffLocation varchar(75) null,
	dropoffDate date null,
	carType varchar(75) null,
	typeOfRental varchar(75) null,
	price double,
	currency_ varchar(75) null,
	tripType varchar(75) null
);

create table vgcapon_BtCostList (
	btCostListId bigint not null primary key,
	businessTripPkId bigint,
	ticketNo varchar(75) null,
	item varchar(75) null,
	type_ varchar(75) null,
	invoiceAmount double,
	invoiceCurrency varchar(75) null,
	country varchar(75) null,
	city varchar(75) null,
	ifPayInRmb boolean,
	paymentCurrency varchar(75) null,
	paymentAmount double,
	paymentMothed varchar(75) null
);

create table vgcapon_BtExchangeRate (
	btExchangeRateId bigint not null primary key,
	firstCurrency varchar(75) null,
	secondCurrency varchar(75) null,
	firToSecExchangeRate double,
	secToFirExchangeRate double,
	userId bigint,
	userName varchar(75) null,
	createDate date null,
	modifiedDate date null,
	status integer
);

create table vgcapon_BtFlightTrainInfo (
	btFlightTrainInfoId bigint not null primary key,
	businessTripPkId bigint,
	ticketNo varchar(75) null,
	type_ varchar(75) null,
	fromCity varchar(75) null,
	toCity varchar(75) null,
	departureDate date null,
	departureFlight varchar(75) null,
	departureTime date null,
	classInfo varchar(75) null,
	price double,
	currency_ varchar(75) null,
	tripType varchar(75) null
);

create table vgcapon_BtHotelInfo (
	btHotelInfoId bigint not null primary key,
	businessTripPkId bigint,
	ticketNo varchar(75) null,
	city varchar(75) null,
	cityType varchar(75) null,
	hotel varchar(75) null,
	checkIn date null,
	checkOut date null,
	roomCategory varchar(75) null,
	price double,
	currency_ varchar(75) null,
	otherReasonInfo varchar(512) null,
	isNotBookedFromTA boolean,
	isOverBudget integer,
	othersSpecify varchar(512) null,
	tripType varchar(75) null
);

create table vgcapon_BtTrainInfo (
	btTrainInfoId bigint not null primary key,
	businessTripPkId bigint,
	ticketNo varchar(75) null,
	fromCity varchar(75) null,
	toCity varchar(75) null,
	departureDate date null,
	departureTrain varchar(75) null,
	classInfo varchar(75) null,
	price double,
	currency_ varchar(75) null,
	tripType varchar(75) null
);

create table vgcapon_BtTravelExpense (
	btTravelExpenseId bigint not null primary key,
	businessTripPkId bigint,
	ticketNo varchar(75) null,
	date_ date null,
	departure date null,
	arrival date null,
	fromCity varchar(75) null,
	toCity varchar(75) null,
	isHasBreakfast boolean,
	isHasLunch boolean,
	isHasDinner boolean,
	country varchar(75) null,
	city varchar(75) null,
	rateOfDma double,
	currency_ varchar(75) null,
	comments varchar(512) null
);
