create table VgcApon_BtApplication (
	businessTripApplicationId bigint not null primary key,
	ticketNo varchar(75) null,
	processType varchar(75) null,
	subType varchar(75) null,
	printName varchar(75) null,
	staffCode bigint,
	companyName varchar(75) null,
	division varchar(75) null,
	department varchar(75) null,
	costCenter varchar(75) null,
	personalID varchar(75) null,
	passportNo varchar(75) null,
	officePhone varchar(75) null,
	mobilePhone varchar(75) null,
	email varchar(75) null,
	officeSite varchar(75) null,
	approverId bigint,
	approverName varchar(75) null,
	isCrossDepartment tinyint,
	targetDepartmentId bigint,
	targetDepartmentName varchar(75) null,
	targetCostCenter varchar(75) null,
	targetDepartmentApproverId bigint,
	targetDepartmentApproverName varchar(75) null,
	tripType integer,
	departureDate timestamp null,
	returnDate timestamp null,
	purposeOfTheTrip varchar(512) null,
	visitCountriesCities varchar(75) null,
	advancePayment float,
	currency_ varchar(75) null,
	paymentMethods varchar(75) null,
	totalCostRmb float,
	totalCostEur float,
	hotelTotalCostRmb float,
	hotelTotalCostEur float,
	carRentalTotalCostRmb float,
	carRentalTotalCostEur float,
	remark varchar(512) null,
	status integer,
	sapStatus integer,
	statusByUserId bigint,
	statusByUserName varchar(75) null,
	statusDate timestamp null,
	isApplicantAgent tinyint,
	isApproverAgent tinyint,
	groupId bigint,
	userId bigint,
	userName varchar(75) null,
	createDate timestamp null,
	modifiedDate timestamp null,
	submittedDate timestamp null,
	companyId bigint
);

create table VgcApon_BtReimbursement (
	businessTripReimbursementId bigint not null primary key,
	ticketNo varchar(75) null,
	bussinessTirpTicketNo varchar(75) null,
	processType varchar(75) null,
	subType varchar(75) null,
	printName varchar(75) null,
	staffCode bigint,
	companyName varchar(75) null,
	division varchar(75) null,
	department varchar(75) null,
	costCenter varchar(75) null,
	personalID varchar(75) null,
	passportNo varchar(75) null,
	officePhone varchar(75) null,
	mobilePhone varchar(75) null,
	email varchar(75) null,
	officeSite varchar(75) null,
	approverId bigint,
	approverName varchar(75) null,
	isCrossDepartment tinyint,
	targetDepartmentId bigint,
	targetDepartmentName varchar(75) null,
	targetCostCenter varchar(75) null,
	targetDepartmentApproverId bigint,
	targetDepartmentApproverName varchar(75) null,
	tripType integer,
	departureDate timestamp null,
	returnDate timestamp null,
	purposeOfTheTrip varchar(512) null,
	visitCountriesCities varchar(75) null,
	advancePayment float,
	currency_ varchar(75) null,
	paymentMethods varchar(75) null,
	totalCostRmb float,
	totalCostEur float,
	hotelTotalCostRmb float,
	hotelTotalCostEur float,
	carRentalTotalCostRmb float,
	carRentalTotalCostEur float,
	totalTravelExpenseRmb float,
	totalTravelExpenseEur float,
	costListInlandTotalRmb float,
	costListForeignTotalEur float,
	costListForeignTotalRmb float,
	remark varchar(512) null,
	status integer,
	sapStatus integer,
	statusByUserId bigint,
	statusByUserName varchar(75) null,
	statusDate timestamp null,
	isApplicantAgent tinyint,
	isApproverAgent tinyint,
	groupId bigint,
	userId bigint,
	userName varchar(75) null,
	createDate timestamp null,
	modifiedDate timestamp null,
	submittedDate timestamp null,
	companyId bigint
);

create table vgcapon_BtCarRentalInfo (
	btCarRentalInfoId bigint not null primary key,
	businessTripPkId bigint,
	ticketNo varchar(75) null,
	pickupLocation varchar(75) null,
	pickupDate timestamp null,
	dropoffLocation varchar(75) null,
	dropoffDate timestamp null,
	carType varchar(75) null,
	typeOfRental varchar(75) null,
	price float,
	currency_ varchar(75) null,
	tripType varchar(75) null
);

create table vgcapon_BtCostList (
	btCostListId bigint not null primary key,
	businessTripPkId bigint,
	ticketNo varchar(75) null,
	item varchar(75) null,
	type_ varchar(75) null,
	invoiceAmount float,
	invoiceCurrency varchar(75) null,
	country varchar(75) null,
	city varchar(75) null,
	ifPayInRmb tinyint,
	paymentCurrency varchar(75) null,
	paymentAmount float,
	paymentMothed varchar(75) null
);

create table vgcapon_BtExchangeRate (
	btExchangeRateId bigint not null primary key,
	firstCurrency varchar(75) null,
	secondCurrency varchar(75) null,
	firToSecExchangeRate float,
	secToFirExchangeRate float,
	userId bigint,
	userName varchar(75) null,
	createDate timestamp null,
	modifiedDate timestamp null,
	status integer
);

create table vgcapon_BtFlightTrainInfo (
	btFlightTrainInfoId bigint not null primary key,
	businessTripPkId bigint,
	ticketNo varchar(75) null,
	type_ varchar(75) null,
	fromCity varchar(75) null,
	toCity varchar(75) null,
	departureDate timestamp null,
	departureFlight varchar(75) null,
	departureTime timestamp null,
	classInfo varchar(75) null,
	price float,
	currency_ varchar(75) null,
	tripType varchar(75) null
);

create table vgcapon_BtHotelInfo (
	btHotelInfoId bigint not null primary key,
	businessTripPkId bigint,
	ticketNo varchar(75) null,
	city varchar(75) null,
	cityType varchar(75) null,
	hotel varchar(75) null,
	checkIn timestamp null,
	checkOut timestamp null,
	roomCategory varchar(75) null,
	price float,
	currency_ varchar(75) null,
	otherReasonInfo varchar(512) null,
	isNotBookedFromTA tinyint,
	isOverBudget integer,
	othersSpecify varchar(512) null,
	tripType varchar(75) null
);

create table vgcapon_BtTrainInfo (
	btTrainInfoId bigint not null primary key,
	businessTripPkId bigint,
	ticketNo varchar(75) null,
	fromCity varchar(75) null,
	toCity varchar(75) null,
	departureDate timestamp null,
	departureTrain varchar(75) null,
	classInfo varchar(75) null,
	price float,
	currency_ varchar(75) null,
	tripType varchar(75) null
);

create table vgcapon_BtTravelExpense (
	btTravelExpenseId bigint not null primary key,
	businessTripPkId bigint,
	ticketNo varchar(75) null,
	date_ timestamp null,
	departure timestamp null,
	arrival timestamp null,
	fromCity varchar(75) null,
	toCity varchar(75) null,
	isHasBreakfast tinyint,
	isHasLunch tinyint,
	isHasDinner tinyint,
	country varchar(75) null,
	city varchar(75) null,
	rateOfDma float,
	currency_ varchar(75) null,
	comments varchar(512) null
);
