create table vgcapon_CompanyCarManagement (
	companyCarManagementId LONG not null primary key,
	createDate DATE null,
	modifiedDate DATE null,
	carNo VARCHAR(75) null,
	carType VARCHAR(75) null,
	contractType VARCHAR(75) null,
	gradeType VARCHAR(75) null,
	grade VARCHAR(75) null,
	carBrand VARCHAR(75) null,
	carModel VARCHAR(75) null,
	carCategory VARCHAR(75) null
);

create table vgcapon_FirstCompanyCar (
	firstCompanyCarId LONG not null primary key,
	ticketNo VARCHAR(75) null,
	groupId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	submittedDate DATE null,
	companyId LONG,
	name VARCHAR(75) null,
	staffCode LONG,
	division VARCHAR(75) null,
	department VARCHAR(75) null,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	companyName VARCHAR(75) null,
	statusDate DATE null,
	contactNo VARCHAR(75) null,
	workingLocation VARCHAR(75) null,
	officeSite VARCHAR(75) null,
	currentCarModel VARCHAR(75) null,
	currentCarColor VARCHAR(75) null,
	currentPlateNumber VARCHAR(75) null,
	acquiringDate DATE null,
	expectedCarModel VARCHAR(75) null,
	expectedCarColor VARCHAR(75) null,
	expectedLastPlateNumber VARCHAR(75) null,
	positionCostCenterId VARCHAR(75) null,
	employeeGroupId VARCHAR(75) null,
	contractEndDate DATE null,
	mobilePhone VARCHAR(75) null,
	officePhone VARCHAR(75) null,
	email VARCHAR(75) null,
	isApplicantAgent BOOLEAN,
	isApproverAgent BOOLEAN,
	drivingLicenseInformation INTEGER,
	estimatedObtainingDate DATE null,
	comments VARCHAR(512) null,
	childrenNumber INTEGER,
	processType VARCHAR(75) null,
	subType VARCHAR(75) null
);

create table vgcapon_SecondCompanyCar (
	secondCompanyCarId LONG not null primary key,
	ticketNo VARCHAR(75) null,
	groupId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	submittedDate DATE null,
	companyId LONG,
	name VARCHAR(75) null,
	staffCode LONG,
	division VARCHAR(75) null,
	department VARCHAR(75) null,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	companyName VARCHAR(75) null,
	statusDate DATE null,
	contactNo VARCHAR(75) null,
	workingLocation VARCHAR(75) null,
	officeSite VARCHAR(75) null,
	currentCarModel VARCHAR(75) null,
	currentCarColor VARCHAR(75) null,
	currentPlateNumber VARCHAR(75) null,
	acquiringDate DATE null,
	expectedCarModel VARCHAR(75) null,
	expectedCarColor VARCHAR(75) null,
	expectedLastPlateNumber VARCHAR(75) null,
	positionCostCenterId VARCHAR(75) null,
	employeeGroupId VARCHAR(75) null,
	contractEndDate DATE null,
	mobilePhone VARCHAR(75) null,
	officePhone VARCHAR(75) null,
	email VARCHAR(75) null,
	isApplicantAgent BOOLEAN,
	isApproverAgent BOOLEAN,
	drivingLicenseInformation INTEGER,
	estimatedObtainingDate DATE null,
	comments VARCHAR(512) null,
	processType VARCHAR(75) null,
	subType VARCHAR(75) null
);