create table vgcapon_ETransfer (
	eTransferId LONG not null primary key,
	groupId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	companyId LONG,
	ticketNo VARCHAR(75) null,
	staffName VARCHAR(75) null,
	currentStaffCode VARCHAR(75) null,
	contractType VARCHAR(75) null,
	newStaffCode VARCHAR(75) null,
	PassedLL INTEGER,
	AttendedSLT INTEGER,
	currentCompany VARCHAR(75) null,
	currentDivision VARCHAR(75) null,
	currentDepartment VARCHAR(75) null,
	currentFunctionName VARCHAR(75) null,
	currentCostCenter VARCHAR(75) null,
	currentReportingTo VARCHAR(75) null,
	otherAgreementIfAny VARCHAR(75) null,
	currentOfficeSite VARCHAR(75) null,
	currentPositionCode VARCHAR(75) null,
	receivingStaffCode VARCHAR(75) null,
	receivingCompany VARCHAR(75) null,
	receivingDivision VARCHAR(75) null,
	receivingDepartment VARCHAR(75) null,
	newFunctionName VARCHAR(75) null,
	newCostCenter VARCHAR(75) null,
	newReportingTo VARCHAR(75) null,
	effectiveDate DATE null,
	newOfficeSite VARCHAR(75) null,
	sapPositionCode VARCHAR(75) null,
	replacement VARCHAR(75) null,
	functionGrade VARCHAR(75) null,
	budgetTypeOfPosition INTEGER,
	chinaSixty INTEGER,
	targetPDSupervisor INTEGER,
	processType VARCHAR(75) null,
	subProcessType VARCHAR(75) null,
	submittedDate DATE null,
	comments VARCHAR(75) null,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null
);

create table vgcapon_HeadcountCI (
	headcountCiId LONG not null primary key,
	groupId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	companyId LONG,
	ticketNo VARCHAR(75) null,
	hostCompany VARCHAR(75) null,
	reasonFApplication1 INTEGER,
	reasonFApplication2 VARCHAR(75) null,
	sapPositionCode VARCHAR(75) null,
	division VARCHAR(75) null,
	department VARCHAR(75) null,
	functionName VARCHAR(75) null,
	functionGrade VARCHAR(75) null,
	reportsTo VARCHAR(75) null,
	costCenter VARCHAR(75) null,
	budgetType INTEGER,
	chinaSixty INTEGER,
	legalCategory INTEGER,
	reason VARCHAR(75) null,
	submittedDate DATE null,
	candidateName VARCHAR(75) null,
	desiredStartingDate DATE null,
	comments VARCHAR(250) null,
	processType VARCHAR(75) null,
	subProcessType VARCHAR(75) null,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null
);

create table vgcapon_HeadcountLE (
	headcountLeId LONG not null primary key,
	groupId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	companyId LONG,
	ticketNo VARCHAR(75) null,
	hostCompany VARCHAR(75) null,
	applicationType1 INTEGER,
	applicationType2 VARCHAR(75) null,
	sapPositionCode VARCHAR(75) null,
	division VARCHAR(75) null,
	department VARCHAR(75) null,
	functionName VARCHAR(75) null,
	functionGrade VARCHAR(75) null,
	reportsTo VARCHAR(75) null,
	chinaSixty INTEGER,
	costCenter VARCHAR(75) null,
	positionType INTEGER,
	disciplinaryRS INTEGER,
	approvedHeadcount BOOLEAN,
	submittedDate DATE null,
	contractType VARCHAR(75) null,
	candidateName VARCHAR(75) null,
	desiredStartingDate DATE null,
	comments VARCHAR(250) null,
	processType VARCHAR(75) null,
	subProcessType VARCHAR(75) null,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null
);