/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.seatoffice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.model.WorkflowedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SeatOffice service. Represents a row in the &quot;vgcapon_SeatOffice&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.seatoffice.model.impl.SeatOfficeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.seatoffice.model.impl.SeatOfficeImpl}.
 * </p>
 *
 * @author Alice.zou
 * @see SeatOffice
 * @see com.seatoffice.model.impl.SeatOfficeImpl
 * @see com.seatoffice.model.impl.SeatOfficeModelImpl
 * @generated
 */
public interface SeatOfficeModel extends BaseModel<SeatOffice>, GroupedModel,
	WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a seat office model instance should use the {@link SeatOffice} interface instead.
	 */

	/**
	 * Returns the primary key of this seat office.
	 *
	 * @return the primary key of this seat office
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this seat office.
	 *
	 * @param primaryKey the primary key of this seat office
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the seat ID of this seat office.
	 *
	 * @return the seat ID of this seat office
	 */
	public long getSeatId();

	/**
	 * Sets the seat ID of this seat office.
	 *
	 * @param seatId the seat ID of this seat office
	 */
	public void setSeatId(long seatId);

	/**
	 * Returns the group ID of this seat office.
	 *
	 * @return the group ID of this seat office
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this seat office.
	 *
	 * @param groupId the group ID of this seat office
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this seat office.
	 *
	 * @return the user ID of this seat office
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this seat office.
	 *
	 * @param userId the user ID of this seat office
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this seat office.
	 *
	 * @return the user uuid of this seat office
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this seat office.
	 *
	 * @param userUuid the user uuid of this seat office
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this seat office.
	 *
	 * @return the user name of this seat office
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this seat office.
	 *
	 * @param userName the user name of this seat office
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this seat office.
	 *
	 * @return the create date of this seat office
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this seat office.
	 *
	 * @param createDate the create date of this seat office
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this seat office.
	 *
	 * @return the modified date of this seat office
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this seat office.
	 *
	 * @param modifiedDate the modified date of this seat office
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the company ID of this seat office.
	 *
	 * @return the company ID of this seat office
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this seat office.
	 *
	 * @param companyId the company ID of this seat office
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the ticket no of this seat office.
	 *
	 * @return the ticket no of this seat office
	 */
	@AutoEscape
	public String getTicketNo();

	/**
	 * Sets the ticket no of this seat office.
	 *
	 * @param ticketNo the ticket no of this seat office
	 */
	public void setTicketNo(String ticketNo);

	/**
	 * Returns the staff name of this seat office.
	 *
	 * @return the staff name of this seat office
	 */
	@AutoEscape
	public String getStaffName();

	/**
	 * Sets the staff name of this seat office.
	 *
	 * @param staffName the staff name of this seat office
	 */
	public void setStaffName(String staffName);

	/**
	 * Returns the staff code of this seat office.
	 *
	 * @return the staff code of this seat office
	 */
	public long getStaffCode();

	/**
	 * Sets the staff code of this seat office.
	 *
	 * @param staffCode the staff code of this seat office
	 */
	public void setStaffCode(long staffCode);

	/**
	 * Returns the company name of this seat office.
	 *
	 * @return the company name of this seat office
	 */
	@AutoEscape
	public String getCompanyName();

	/**
	 * Sets the company name of this seat office.
	 *
	 * @param companyName the company name of this seat office
	 */
	public void setCompanyName(String companyName);

	/**
	 * Returns the division of this seat office.
	 *
	 * @return the division of this seat office
	 */
	@AutoEscape
	public String getDivision();

	/**
	 * Sets the division of this seat office.
	 *
	 * @param division the division of this seat office
	 */
	public void setDivision(String division);

	/**
	 * Returns the department of this seat office.
	 *
	 * @return the department of this seat office
	 */
	@AutoEscape
	public String getDepartment();

	/**
	 * Sets the department of this seat office.
	 *
	 * @param department the department of this seat office
	 */
	public void setDepartment(String department);

	/**
	 * Returns the cost center of this seat office.
	 *
	 * @return the cost center of this seat office
	 */
	@AutoEscape
	public String getCostCenter();

	/**
	 * Sets the cost center of this seat office.
	 *
	 * @param costCenter the cost center of this seat office
	 */
	public void setCostCenter(String costCenter);

	/**
	 * Returns the office phone of this seat office.
	 *
	 * @return the office phone of this seat office
	 */
	@AutoEscape
	public String getOfficePhone();

	/**
	 * Sets the office phone of this seat office.
	 *
	 * @param officePhone the office phone of this seat office
	 */
	public void setOfficePhone(String officePhone);

	/**
	 * Returns the mobile phone of this seat office.
	 *
	 * @return the mobile phone of this seat office
	 */
	@AutoEscape
	public String getMobilePhone();

	/**
	 * Sets the mobile phone of this seat office.
	 *
	 * @param mobilePhone the mobile phone of this seat office
	 */
	public void setMobilePhone(String mobilePhone);

	/**
	 * Returns the office site of this seat office.
	 *
	 * @return the office site of this seat office
	 */
	@AutoEscape
	public String getOfficeSite();

	/**
	 * Sets the office site of this seat office.
	 *
	 * @param officeSite the office site of this seat office
	 */
	public void setOfficeSite(String officeSite);

	/**
	 * Returns the current category of this seat office.
	 *
	 * @return the current category of this seat office
	 */
	public long getCurrentCategory();

	/**
	 * Sets the current category of this seat office.
	 *
	 * @param currentCategory the current category of this seat office
	 */
	public void setCurrentCategory(long currentCategory);

	/**
	 * Returns the current seat no of this seat office.
	 *
	 * @return the current seat no of this seat office
	 */
	@AutoEscape
	public String getCurrentSeatNo();

	/**
	 * Sets the current seat no of this seat office.
	 *
	 * @param currentSeatNo the current seat no of this seat office
	 */
	public void setCurrentSeatNo(String currentSeatNo);

	/**
	 * Returns the moving date of this seat office.
	 *
	 * @return the moving date of this seat office
	 */
	public Date getMovingDate();

	/**
	 * Sets the moving date of this seat office.
	 *
	 * @param movingDate the moving date of this seat office
	 */
	public void setMovingDate(Date movingDate);

	/**
	 * Returns the expected seat no of this seat office.
	 *
	 * @return the expected seat no of this seat office
	 */
	@AutoEscape
	public String getExpectedSeatNo();

	/**
	 * Sets the expected seat no of this seat office.
	 *
	 * @param expectedSeatNo the expected seat no of this seat office
	 */
	public void setExpectedSeatNo(String expectedSeatNo);

	/**
	 * Returns the reason for change of this seat office.
	 *
	 * @return the reason for change of this seat office
	 */
	@AutoEscape
	public String getReasonForChange();

	/**
	 * Sets the reason for change of this seat office.
	 *
	 * @param reasonForChange the reason for change of this seat office
	 */
	public void setReasonForChange(String reasonForChange);

	/**
	 * Returns the office key of this seat office.
	 *
	 * @return the office key of this seat office
	 */
	public boolean getOfficeKey();

	/**
	 * Returns <code>true</code> if this seat office is office key.
	 *
	 * @return <code>true</code> if this seat office is office key; <code>false</code> otherwise
	 */
	public boolean isOfficeKey();

	/**
	 * Sets whether this seat office is office key.
	 *
	 * @param officeKey the office key of this seat office
	 */
	public void setOfficeKey(boolean officeKey);

	/**
	 * Returns the plant of this seat office.
	 *
	 * @return the plant of this seat office
	 */
	public boolean getPlant();

	/**
	 * Returns <code>true</code> if this seat office is plant.
	 *
	 * @return <code>true</code> if this seat office is plant; <code>false</code> otherwise
	 */
	public boolean isPlant();

	/**
	 * Sets whether this seat office is plant.
	 *
	 * @param plant the plant of this seat office
	 */
	public void setPlant(boolean plant);

	/**
	 * Returns the telephone and ext no of this seat office.
	 *
	 * @return the telephone and ext no of this seat office
	 */
	public boolean getTelephoneAndExtNo();

	/**
	 * Returns <code>true</code> if this seat office is telephone and ext no.
	 *
	 * @return <code>true</code> if this seat office is telephone and ext no; <code>false</code> otherwise
	 */
	public boolean isTelephoneAndExtNo();

	/**
	 * Sets whether this seat office is telephone and ext no.
	 *
	 * @param telephoneAndExtNo the telephone and ext no of this seat office
	 */
	public void setTelephoneAndExtNo(boolean telephoneAndExtNo);

	/**
	 * Returns the name plate of this seat office.
	 *
	 * @return the name plate of this seat office
	 */
	public boolean getNamePlate();

	/**
	 * Returns <code>true</code> if this seat office is name plate.
	 *
	 * @return <code>true</code> if this seat office is name plate; <code>false</code> otherwise
	 */
	public boolean isNamePlate();

	/**
	 * Sets whether this seat office is name plate.
	 *
	 * @param namePlate the name plate of this seat office
	 */
	public void setNamePlate(boolean namePlate);

	/**
	 * Returns the cabinet of this seat office.
	 *
	 * @return the cabinet of this seat office
	 */
	public boolean getCabinet();

	/**
	 * Returns <code>true</code> if this seat office is cabinet.
	 *
	 * @return <code>true</code> if this seat office is cabinet; <code>false</code> otherwise
	 */
	public boolean isCabinet();

	/**
	 * Sets whether this seat office is cabinet.
	 *
	 * @param cabinet the cabinet of this seat office
	 */
	public void setCabinet(boolean cabinet);

	/**
	 * Returns the is on behalf of of this seat office.
	 *
	 * @return the is on behalf of of this seat office
	 */
	public boolean getIsOnBehalfOf();

	/**
	 * Returns <code>true</code> if this seat office is is on behalf of.
	 *
	 * @return <code>true</code> if this seat office is is on behalf of; <code>false</code> otherwise
	 */
	public boolean isIsOnBehalfOf();

	/**
	 * Sets whether this seat office is is on behalf of.
	 *
	 * @param isOnBehalfOf the is on behalf of of this seat office
	 */
	public void setIsOnBehalfOf(boolean isOnBehalfOf);

	/**
	 * Returns the now category of this seat office.
	 *
	 * @return the now category of this seat office
	 */
	public long getNowCategory();

	/**
	 * Sets the now category of this seat office.
	 *
	 * @param nowCategory the now category of this seat office
	 */
	public void setNowCategory(long nowCategory);

	/**
	 * Returns the new seat no of this seat office.
	 *
	 * @return the new seat no of this seat office
	 */
	@AutoEscape
	public String getNewSeatNo();

	/**
	 * Sets the new seat no of this seat office.
	 *
	 * @param newSeatNo the new seat no of this seat office
	 */
	public void setNewSeatNo(String newSeatNo);

	/**
	 * Returns the workspace ID of this seat office.
	 *
	 * @return the workspace ID of this seat office
	 */
	public long getWorkspaceId();

	/**
	 * Sets the workspace ID of this seat office.
	 *
	 * @param workspaceId the workspace ID of this seat office
	 */
	public void setWorkspaceId(long workspaceId);

	/**
	 * Returns the seat status of this seat office.
	 *
	 * @return the seat status of this seat office
	 */
	@AutoEscape
	public String getSeatStatus();

	/**
	 * Sets the seat status of this seat office.
	 *
	 * @param seatStatus the seat status of this seat office
	 */
	public void setSeatStatus(String seatStatus);

	/**
	 * Returns the sg of this seat office.
	 *
	 * @return the sg of this seat office
	 */
	@AutoEscape
	public String getSg();

	/**
	 * Sets the sg of this seat office.
	 *
	 * @param sg the sg of this seat office
	 */
	public void setSg(String sg);

	/**
	 * Returns the leading mark of this seat office.
	 *
	 * @return the leading mark of this seat office
	 */
	@AutoEscape
	public String getLeadingMark();

	/**
	 * Sets the leading mark of this seat office.
	 *
	 * @param leadingMark the leading mark of this seat office
	 */
	public void setLeadingMark(String leadingMark);

	/**
	 * Returns the position flag of this seat office.
	 *
	 * @return the position flag of this seat office
	 */
	@AutoEscape
	public String getPositionFlag();

	/**
	 * Sets the position flag of this seat office.
	 *
	 * @param positionFlag the position flag of this seat office
	 */
	public void setPositionFlag(String positionFlag);

	/**
	 * Returns the is applicant agent of this seat office.
	 *
	 * @return the is applicant agent of this seat office
	 */
	public boolean getIsApplicantAgent();

	/**
	 * Returns <code>true</code> if this seat office is is applicant agent.
	 *
	 * @return <code>true</code> if this seat office is is applicant agent; <code>false</code> otherwise
	 */
	public boolean isIsApplicantAgent();

	/**
	 * Sets whether this seat office is is applicant agent.
	 *
	 * @param isApplicantAgent the is applicant agent of this seat office
	 */
	public void setIsApplicantAgent(boolean isApplicantAgent);

	/**
	 * Returns the is approver agent of this seat office.
	 *
	 * @return the is approver agent of this seat office
	 */
	public boolean getIsApproverAgent();

	/**
	 * Returns <code>true</code> if this seat office is is approver agent.
	 *
	 * @return <code>true</code> if this seat office is is approver agent; <code>false</code> otherwise
	 */
	public boolean isIsApproverAgent();

	/**
	 * Sets whether this seat office is is approver agent.
	 *
	 * @param isApproverAgent the is approver agent of this seat office
	 */
	public void setIsApproverAgent(boolean isApproverAgent);

	/**
	 * Returns the candidate name of this seat office.
	 *
	 * @return the candidate name of this seat office
	 */
	@AutoEscape
	public String getCandidateName();

	/**
	 * Sets the candidate name of this seat office.
	 *
	 * @param candidateName the candidate name of this seat office
	 */
	public void setCandidateName(String candidateName);

	/**
	 * Returns the desired starting date of this seat office.
	 *
	 * @return the desired starting date of this seat office
	 */
	public Date getDesiredStartingDate();

	/**
	 * Sets the desired starting date of this seat office.
	 *
	 * @param desiredStartingDate the desired starting date of this seat office
	 */
	public void setDesiredStartingDate(Date desiredStartingDate);

	/**
	 * Returns the comments of this seat office.
	 *
	 * @return the comments of this seat office
	 */
	@AutoEscape
	public String getComments();

	/**
	 * Sets the comments of this seat office.
	 *
	 * @param comments the comments of this seat office
	 */
	public void setComments(String comments);

	/**
	 * Returns the contract type of this seat office.
	 *
	 * @return the contract type of this seat office
	 */
	@AutoEscape
	public String getContractType();

	/**
	 * Sets the contract type of this seat office.
	 *
	 * @param contractType the contract type of this seat office
	 */
	public void setContractType(String contractType);

	/**
	 * Returns the process type of this seat office.
	 *
	 * @return the process type of this seat office
	 */
	@AutoEscape
	public String getProcessType();

	/**
	 * Sets the process type of this seat office.
	 *
	 * @param processType the process type of this seat office
	 */
	public void setProcessType(String processType);

	/**
	 * Returns the sub process type of this seat office.
	 *
	 * @return the sub process type of this seat office
	 */
	@AutoEscape
	public String getSubProcessType();

	/**
	 * Sets the sub process type of this seat office.
	 *
	 * @param subProcessType the sub process type of this seat office
	 */
	public void setSubProcessType(String subProcessType);

	/**
	 * Returns the status of this seat office.
	 *
	 * @return the status of this seat office
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this seat office.
	 *
	 * @param status the status of this seat office
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this seat office.
	 *
	 * @return the status by user ID of this seat office
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this seat office.
	 *
	 * @param statusByUserId the status by user ID of this seat office
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this seat office.
	 *
	 * @return the status by user uuid of this seat office
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getStatusByUserUuid() throws SystemException;

	/**
	 * Sets the status by user uuid of this seat office.
	 *
	 * @param statusByUserUuid the status by user uuid of this seat office
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this seat office.
	 *
	 * @return the status by user name of this seat office
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this seat office.
	 *
	 * @param statusByUserName the status by user name of this seat office
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this seat office.
	 *
	 * @return the status date of this seat office
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this seat office.
	 *
	 * @param statusDate the status date of this seat office
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * @deprecated As of 6.1.0, replaced by {@link #isApproved()}
	 */
	@Override
	public boolean getApproved();

	/**
	 * Returns <code>true</code> if this seat office is approved.
	 *
	 * @return <code>true</code> if this seat office is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this seat office is denied.
	 *
	 * @return <code>true</code> if this seat office is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this seat office is a draft.
	 *
	 * @return <code>true</code> if this seat office is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this seat office is expired.
	 *
	 * @return <code>true</code> if this seat office is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this seat office is inactive.
	 *
	 * @return <code>true</code> if this seat office is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this seat office is incomplete.
	 *
	 * @return <code>true</code> if this seat office is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this seat office is pending.
	 *
	 * @return <code>true</code> if this seat office is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this seat office is scheduled.
	 *
	 * @return <code>true</code> if this seat office is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.seatoffice.model.SeatOffice seatOffice);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.seatoffice.model.SeatOffice> toCacheModel();

	@Override
	public com.seatoffice.model.SeatOffice toEscapedModel();

	@Override
	public com.seatoffice.model.SeatOffice toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}