/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.e.leave.service.base;

import com.e.leave.model.ELeave;
import com.e.leave.service.ELeaveService;
import com.e.leave.service.persistence.ELeaveInfoPersistence;
import com.e.leave.service.persistence.ELeavePersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the e leave remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.e.leave.service.impl.ELeaveServiceImpl}.
 * </p>
 *
 * @author EZEYIFE
 * @see com.e.leave.service.impl.ELeaveServiceImpl
 * @see com.e.leave.service.ELeaveServiceUtil
 * @generated
 */
public abstract class ELeaveServiceBaseImpl extends BaseServiceImpl
	implements ELeaveService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.e.leave.service.ELeaveServiceUtil} to access the e leave remote service.
	 */

	/**
	 * Returns the e leave local service.
	 *
	 * @return the e leave local service
	 */
	public com.e.leave.service.ELeaveLocalService getELeaveLocalService() {
		return eLeaveLocalService;
	}

	/**
	 * Sets the e leave local service.
	 *
	 * @param eLeaveLocalService the e leave local service
	 */
	public void setELeaveLocalService(
		com.e.leave.service.ELeaveLocalService eLeaveLocalService) {
		this.eLeaveLocalService = eLeaveLocalService;
	}

	/**
	 * Returns the e leave remote service.
	 *
	 * @return the e leave remote service
	 */
	public com.e.leave.service.ELeaveService getELeaveService() {
		return eLeaveService;
	}

	/**
	 * Sets the e leave remote service.
	 *
	 * @param eLeaveService the e leave remote service
	 */
	public void setELeaveService(
		com.e.leave.service.ELeaveService eLeaveService) {
		this.eLeaveService = eLeaveService;
	}

	/**
	 * Returns the e leave persistence.
	 *
	 * @return the e leave persistence
	 */
	public ELeavePersistence getELeavePersistence() {
		return eLeavePersistence;
	}

	/**
	 * Sets the e leave persistence.
	 *
	 * @param eLeavePersistence the e leave persistence
	 */
	public void setELeavePersistence(ELeavePersistence eLeavePersistence) {
		this.eLeavePersistence = eLeavePersistence;
	}

	/**
	 * Returns the e leave info local service.
	 *
	 * @return the e leave info local service
	 */
	public com.e.leave.service.ELeaveInfoLocalService getELeaveInfoLocalService() {
		return eLeaveInfoLocalService;
	}

	/**
	 * Sets the e leave info local service.
	 *
	 * @param eLeaveInfoLocalService the e leave info local service
	 */
	public void setELeaveInfoLocalService(
		com.e.leave.service.ELeaveInfoLocalService eLeaveInfoLocalService) {
		this.eLeaveInfoLocalService = eLeaveInfoLocalService;
	}

	/**
	 * Returns the e leave info remote service.
	 *
	 * @return the e leave info remote service
	 */
	public com.e.leave.service.ELeaveInfoService getELeaveInfoService() {
		return eLeaveInfoService;
	}

	/**
	 * Sets the e leave info remote service.
	 *
	 * @param eLeaveInfoService the e leave info remote service
	 */
	public void setELeaveInfoService(
		com.e.leave.service.ELeaveInfoService eLeaveInfoService) {
		this.eLeaveInfoService = eLeaveInfoService;
	}

	/**
	 * Returns the e leave info persistence.
	 *
	 * @return the e leave info persistence
	 */
	public ELeaveInfoPersistence getELeaveInfoPersistence() {
		return eLeaveInfoPersistence;
	}

	/**
	 * Sets the e leave info persistence.
	 *
	 * @param eLeaveInfoPersistence the e leave info persistence
	 */
	public void setELeaveInfoPersistence(
		ELeaveInfoPersistence eLeaveInfoPersistence) {
		this.eLeaveInfoPersistence = eLeaveInfoPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return ELeave.class;
	}

	protected String getModelClassName() {
		return ELeave.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = eLeavePersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.e.leave.service.ELeaveLocalService.class)
	protected com.e.leave.service.ELeaveLocalService eLeaveLocalService;
	@BeanReference(type = com.e.leave.service.ELeaveService.class)
	protected com.e.leave.service.ELeaveService eLeaveService;
	@BeanReference(type = ELeavePersistence.class)
	protected ELeavePersistence eLeavePersistence;
	@BeanReference(type = com.e.leave.service.ELeaveInfoLocalService.class)
	protected com.e.leave.service.ELeaveInfoLocalService eLeaveInfoLocalService;
	@BeanReference(type = com.e.leave.service.ELeaveInfoService.class)
	protected com.e.leave.service.ELeaveInfoService eLeaveInfoService;
	@BeanReference(type = ELeaveInfoPersistence.class)
	protected ELeaveInfoPersistence eLeaveInfoPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private ELeaveServiceClpInvoker _clpInvoker = new ELeaveServiceClpInvoker();
}